export const VIZ_IDS = [
  "osi-explorer",
  "tcp-simulator",
  "dns-simulator",
  "http-simulator",
  "algorithm-visualizer",
  "bst-explorer",
  "graph-search",
  "dijkstra",
  "hash-collisions",
  "cpu-scheduler",
  "process-states",
  "paging-simulator",
  "page-replacement",
  "deadlock-simulator",
  "cpu-pipeline",
  "sql-playground",
  "bplus-tree",
  "transaction-simulator",
  "cache-simulator",
  "load-balancer",
  "consistent-hashing",
  "distributed-simulator",
  "compiler-explorer",
  "dfa-simulator",
  "neural-net",
  "linux-terminal",
  "stack-queue",
  "routing-simulator",
  "memory-map",
] as const;

export function hasViz(id: string | undefined): id is string {
  return Boolean(id && (VIZ_IDS as readonly string[]).includes(id));
}
