import { iq, T } from "../helpers";
import type { Topic } from "../types";

export const FLAGSHIP: Topic[] = [
  T({
    slug: "osi-model",
    section: "networks",
    title: "OSI Model",
    summary:
      "A seven-layer model of network communication, from the physical medium up to application messages, used as the shared vocabulary of networking.",
    level: "beginner",
    prereqs: ["what-is-networking"],
    related: ["tcp-ip-model", "osi-vs-tcpip", "l7-application", "l4-transport", "l3-network", "l2-data-link"],
    next: "l7-application",
    tags: ["networks", "osi", "layers"],
    viz: "osi-explorer",
    lab: "osi-explorer",
    what: "The Open Systems Interconnection model is an ISO standard (ISO/IEC 7498) that splits communication into seven layers. Each layer offers a service to the layer above and uses the layer below. It is a teaching and troubleshooting map — the internet’s running stack is TCP/IP, which cuts the same job into four layers.",
    why: "Without a shared layering, every conversation about a failure becomes a fight about whose job it was. The OSI model lets you ask: is this a cable, a MAC table, a route, a TCP handshake, or an HTTP header? That question is how you debug, how you interview, and how you design.",
    mental:
      "Picture a letter. You write words (application), agree on a language and envelope format (presentation/session), the post office guarantees the letter (transport), routing takes it across cities (network), trucks hop between stations (data link), and the road actually exists (physical). Encapsulation is putting a new wrapper on at each floor going down; decapsulation is unwrapping going up on the other side.",
    points: [
      "Layer 7 Application — application data and protocols people name: HTTP, DNS, SMTP, SSH, DHCP.",
      "Layer 6 Presentation — encoding, compression, encryption. In TCP/IP this is folded into the application (TLS is the usual example).",
      "Layer 5 Session — establishing, managing, and tearing down a dialog. Thin on the internet; RPC and NetBIOS made it more explicit.",
      "Layer 4 Transport — process-to-process. Ports, segments/datagrams, reliability and congestion control (TCP) or not (UDP).",
      "Layer 3 Network — host-to-host across hops. IP packets, logical addresses, routing, ICMP.",
      "Layer 2 Data Link — hop-to-hop frames. MAC addresses, Ethernet, switches, error detection.",
      "Layer 1 Physical — bits on a medium. Connectors, signaling, fiber, copper, radio.",
      "A layer should not need the internals of the layers below — only their service. That is the point of the split.",
    ],
    steps: [
      "A browser wants https://example.com/index.html.",
      "Application: HTTP request bytes. Presentation/session (in practice, TLS + HTTP): encrypt and frame a record.",
      "Transport: TCP wraps a segment, source and dest ports, sequence numbers.",
      "Network: IP wraps a packet, source and dest IP, TTL.",
      "Data link: Ethernet wraps a frame, source and dest MAC, EtherType 0x0800.",
      "Physical: the frame is serialized onto the wire as bits.",
      "Each hop on the path strips L2, looks at L3, wraps a new L2 for the next hop. Only the endpoints unwrap L4–L7.",
    ],
    implementation:
      "Nothing in the kernel is literally 'the OSI module'. Linux has sockets (L4 interface), an IP stack (L3), netdevices and qdiscs (L2/L1). Wireshark’s packet view is the closest everyday OSI diagram: Frame / Ethernet / IP / TCP / TLS / HTTP stacked on one capture.",
    complexity: {
      tradeoffs: [
        "Seven layers are better for teaching; four (TCP/IP) match implementations.",
        "Strict layering can waste bytes (headers at every layer) and hide cross-layer optimizations (QUIC merging transport+crypto+streams).",
        "Real products punch holes: middleboxes inspect HTTP, NATs rewrite L3/L4, CDNs terminate TLS.",
      ],
    },
    usage: [
      "Troubleshooting: 'ping works, TCP does not' is an L3 vs L4 split.",
      "Certification and interviews: name the PDU, address, and device at each layer.",
      "Design: decide whether a feature belongs in the app, the transport, or the network.",
    ],
    mistakes: [
      "Treating OSI as what the internet runs. It is not. TCP/IP is.",
      "Putting TLS exclusively in layer 6 as if the RFCs agreed. TLS is an application-layer protocol over TCP (or a transport in QUIC).",
      "Saying a router 'works at layer 3' and stopping. A router has L1 ports, L2 encapsulations, and often L4 ACLs.",
      "Confusing PDU names: data / segment / packet / frame / bits.",
    ],
    interview: [
      iq("Name the seven OSI layers in order, top to bottom.", "Application, Presentation, Session, Transport, Network, Data Link, Physical.", "beginner"),
      iq("What is the PDU at each of layers 4, 3, and 2?", "Segment (TCP) or datagram (UDP) at L4, packet at L3, frame at L2. Application data sits above.", "beginner"),
      iq("Which layer uses MAC addresses? Which uses IP addresses? Which uses ports?", "MAC: data link. IP: network. Ports: transport.", "beginner"),
      iq("A switch vs a router — which layers?", "A switch forwards on L2 (MAC). A router forwards on L3 (IP). A multilayer switch can do both.", "intermediate"),
      iq("Walk encapsulation of an HTTP GET.", "HTTP bytes → TCP segment (ports, seq) → IP packet (IPs, TTL) → Ethernet frame (MACs) → bits. Reverse on the receiver, and at each hop only L2 is rewritten.", "intermediate", "Where does TLS sit in that story?"),
      iq("Why does the OSI session layer feel empty on the internet?", "TCP already gives a byte-stream session, and applications (HTTP/2 streams, TLS sessions) absorbed the rest. The function exists; it is not a separate protocol suite.", "advanced"),
    ],
    extra: [
      {
        type: "table",
        headers: ["Layer", "Name", "PDU", "Address", "Examples", "Devices"],
        rows: [
          ["7", "Application", "Data", "app identity / URL", "HTTP, DNS, SMTP, SSH", "Hosts, gateways (L7)"],
          ["6", "Presentation", "Data", "—", "TLS, encodings, codecs", "Hosts"],
          ["5", "Session", "Data", "session id", "RPC dialogs, NetBIOS", "Hosts"],
          ["4", "Transport", "Segment / Datagram", "Port", "TCP, UDP, QUIC", "Hosts, L4 LBs"],
          ["3", "Network", "Packet", "IP", "IPv4/IPv6, ICMP, OSPF", "Routers"],
          ["2", "Data Link", "Frame", "MAC", "Ethernet, Wi-Fi, PPP", "Switches, AP, bridge"],
          ["1", "Physical", "Bits", "—", "1000BASE-T, fiber, radio", "Hubs, repeaters, NICs"],
        ],
      },
      {
        type: "callout",
        kind: "tip",
        title: "A mnemonic that does not insult anyone",
        text: "All People Seem To Need Data Processing — Application → Physical. Use it once, then use the PDU names until they stick.",
      },
      { type: "viz", id: "osi-explorer" },
      {
        type: "callout",
        kind: "interview",
        title: "If they only ask one follow-up",
        text: "They will ask you to place a failure. 'DNS works, the page does not' is L7/L4. 'ARP does not resolve' is L2/L3. 'Link light is down' is L1.",
      },
    ],
  }),
  T({
    slug: "tcp-handshake",
    section: "networks",
    title: "TCP Handshake",
    summary: "Three segments that create a TCP connection: SYN, SYN-ACK, ACK — exchanging initial sequence numbers and options.",
    level: "beginner",
    prereqs: ["tcp"],
    related: ["tcp-teardown", "ports", "http"],
    next: "tcp-teardown",
    viz: "tcp-simulator",
    lab: "tcp-simulator",
    what: "TCP is connection-oriented. Before either side sends application data, they run a three-way handshake so both agree that a connection exists and both know the other's starting sequence number.",
    why: "Almost every HTTP/1.1 and TLS session on TCP begins here. Connection latency (one RTT before data, plus more for TLS) is this handshake. SYN floods are this handshake abused.",
    mental:
      "Two people picking a numbering system before they talk. 'I will start at 42' / 'I heard 42, I will start at 99' / 'I heard 99.' After that, every byte has a number and losses can be named.",
    points: [
      "Client sends SYN with its initial sequence number (ISN) and options (window scale, SACK, MSS).",
      "Server replies SYN-ACK with its own ISN and acknowledges client ISN+1. The TCB (transmission control block) is created, or a SYN cookie is used.",
      "Client sends ACK of server ISN+1. The connection is ESTABLISHED on both sides (server already was after the ACK arrives).",
      "Data can be piggybacked on that third ACK, but browsers usually wait (and then do TLS).",
      "Each SYN consumes state. Unanswered SYNs are how SYN floods fill a backlog.",
    ],
    steps: [
      "Client: flags=SYN, seq=x, options=MSS, WS, SACK-permitted, TSval.",
      "Server: flags=SYN+ACK, seq=y, ack=x+1.",
      "Client: flags=ACK, seq=x+1, ack=y+1.",
      "Both state machines sit in ESTABLISHED. Application write() now produces segments with payload.",
    ],
    code: {
      lang: "text",
      title: "A capture in words",
      code: `C → S  SYN     seq=1000        win=65535  mss=1460
S → C  SYN-ACK seq=5000 ack=1001
C → S  ACK     seq=1001 ack=5001
C → S  PSH-ACK seq=1001 ack=5001  "GET / HTTP/1.1..."`,
    },
    mistakes: [
      "Calling it a 'three-way handshake of HTTP'. HTTP may reuse a connection; the handshake is TCP's.",
      "Forgetting that sequence numbers count bytes, not segments.",
      "Assuming the server is ESTABLISHED after SYN-ACK. It is SYN-RECEIVED until the ACK arrives (unless you are hand-waving).",
    ],
    usage: ["Every TCP connect()", "Load balancer health and connection tracking", "Diagnosing 'connection timed out' vs 'connection reset'"],
    interview: [
      iq("Draw the three-way handshake with sequence numbers.", "SYN seq=x; SYN-ACK seq=y ack=x+1; ACK seq=x+1 ack=y+1.", "beginner"),
      iq("Why three ways, not two?", "Both sides must advertise an ISN and learn the other. Two ways would leave one side unsure the peer received its ISN.", "intermediate"),
      iq("What is a SYN cookie?", "A server that encodes the SYN state into the ISN so it does not store a TCB until the ACK arrives — a SYN-flood defense.", "advanced"),
    ],
    extra: [{ type: "viz", id: "tcp-simulator" }],
  }),
  T({
    slug: "dns",
    section: "networks",
    title: "DNS",
    summary: "A distributed, hierarchical lookup system that maps names to records — most often IP addresses.",
    level: "beginner",
    prereqs: ["l7-application"],
    related: ["http", "dhcp", "udp"],
    next: "http",
    viz: "dns-simulator",
    lab: "dns-simulator",
    what: "The Domain Name System is a tree of zones. A resolver starts at a root, is referred to a TLD, is referred to an authoritative name server, and caches the answer under a TTL.",
    why: "Humans use names; packets use addresses. DNS is the seam. When it is slow or wrong, 'the internet is down' for everyone who cannot read an IP.",
    mental:
      "A phone book that is sharded by suffix and cached everywhere. You do not call the root with every lookup — your stub asks a recursive resolver, which walks the tree once and remembers.",
    points: [
      "Stub resolver (in the OS) → recursive resolver (ISP, 8.8.8.8, 1.1.1.1) → root → TLD → authoritative.",
      "Record types: A, AAAA, CNAME, MX, NS, TXT, SRV. The type is part of the question.",
      "UDP/53 for small answers; TCP/53 for large ones and zone transfers.",
      "TTLs are a consistency/performance knob. Low TTL: faster failover, more queries.",
      "DNS is not authentic by default. DNSSEC signs records; DoH/DoT hide queries from the path.",
    ],
    steps: [
      "Browser asks OS for example.com A.",
      "OS stub asks 1.1.1.1 (or whatever DHCP handed out).",
      "Resolver, if cold: queries a root for .com NS, then .com for example.com NS, then those NS for A.",
      "Answer comes back with TTL. Everyone along the path may cache it.",
      "Browser then opens TCP to that IP (and may query again for IPv6 AAAA).",
    ],
    mistakes: [
      "Assuming DNS 'returns the nearest server'. That is anycast or a CDN's geo-DNS policy, not the protocol.",
      "Forgetting CNAME chains and the extra lookups they cause.",
      "Using a 5-second TTL on a record that 10k clients will stampede.",
    ],
    usage: ["Every URL bar", "Service discovery (SRV, and now HTTPS/SVCB records)", "Email (MX)"],
    interview: [
      iq("Walk a recursive lookup for www.example.com.", "Stub → recursive → root (com NS) → TLD (example.com NS) → authoritative (A/AAAA). Caches at each hop according to TTL.", "beginner"),
      iq("A vs CNAME vs NS?", "A maps a name to IPv4. CNAME aliases a name to another name. NS names the authoritative servers for a zone.", "intermediate"),
      iq("Why can DNS use UDP?", "Questions and answers are usually small and idempotent. Loss is handled by timeout-and-retry. Truncated answers retry over TCP.", "intermediate"),
    ],
    extra: [{ type: "viz", id: "dns-simulator" }],
  }),
  T({
    slug: "http",
    section: "networks",
    title: "HTTP",
    summary: "The application protocol of the web: a request-response exchange of methods, targets, headers, and bodies.",
    level: "beginner",
    prereqs: ["tcp", "dns"],
    related: ["https", "rest", "browser-architecture"],
    next: "https",
    viz: "http-simulator",
    lab: "http-simulator",
    what: "HTTP is a stateless application protocol. A client sends a request line, headers, and optional body; a server replies with a status, headers, and optional body. Versions: 1.0, 1.1 (persistent connections, pipelining), 2 (binary, multiplexed streams), 3 (over QUIC/UDP).",
    why: "Browsers, APIs, scrapers, health checks — if it speaks to a web service, it speaks HTTP. Caching, auth, and content negotiation are all headers you have to get right.",
    mental:
      "A letter with a verb and a path, plus sticky notes (headers). The connection that carries the letter is TCP (or QUIC). HTTP itself does not remember you; cookies and tokens do.",
    points: [
      "Methods: GET (safe, idempotent), HEAD, POST, PUT (idempotent), PATCH, DELETE (idempotent), OPTIONS.",
      "Status classes: 1xx informational, 2xx success, 3xx redirect, 4xx client, 5xx server.",
      "Headers are the control plane: Cache-Control, Authorization, Content-Type, CORS, cookies.",
      "HTTP/1.1 is text. HTTP/2 is framed and multiplexed. HTTP/3 moves the transport to QUIC.",
      "Stateless protocol, stateful applications — sessions live in cookies, tokens, or servers.",
    ],
    steps: [
      "Resolve the host (DNS).",
      "TCP connect (and TLS if https).",
      "Send: GET /path HTTP/1.1 plus Host and other headers.",
      "Read status and headers; decode the body (content-length or chunked).",
      "Reuse the connection (keep-alive) or close.",
    ],
    code: {
      lang: "http",
      title: "A minimal request and response",
      code: `GET /hello HTTP/1.1
Host: example.com
Accept: text/plain

HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 5

hello`,
    },
    mistakes: [
      "Using GET for state changes (they get cached, prefetched, logged).",
      "Treating status 200 as the only success; 201/204 exist for a reason.",
      "Putting secrets in query strings — they land in logs and Referer.",
    ],
    usage: ["Browsers", "REST/JSON APIs", "Webhooks and health checks"],
    interview: [
      iq("Idempotent vs safe?", "Safe methods do not change server state (GET, HEAD). Idempotent methods can be retried with the same effect (GET, PUT, DELETE). POST is neither.", "intermediate"),
      iq("What does Host exist for?", "Name-based virtual hosting: many names, one IP. HTTP/1.1 made Host required.", "beginner"),
      iq("HTTP/2 vs 1.1 in one sentence.", "HTTP/2 multiplexes concurrent streams over one TCP connection with binary frames, killing head-of-line blocking at the HTTP layer (not at TCP).", "advanced"),
    ],
    extra: [{ type: "viz", id: "http-simulator" }],
  }),
  T({
    slug: "tcp",
    section: "networks",
    title: "TCP",
    summary: "A reliable, ordered, congestion-controlled byte stream between two ports on two hosts.",
    level: "beginner",
    prereqs: ["l4-transport", "ip"],
    related: ["udp", "tcp-handshake", "congestion-control"],
    next: "udp",
    viz: "tcp-simulator",
    lab: "tcp-simulator",
    what: "The Transmission Control Protocol turns best-effort IP packets into a stream that, under ordinary loss, delivers every byte once, in order. It does this with sequence numbers, acknowledgements, retransmission, flow control (window), and congestion control.",
    why: "Files, HTTP, SSH, email — anything that would be wrong if a byte went missing — sits on TCP. Knowing what TCP guarantees (and that it does not guarantee timely delivery) is the difference between a network bug and an application bug.",
    mental:
      "A numbered conveyor belt with receipts. If a box is missing, you ask again. If the receiver's loading dock is full, you slow down. If the highway is jammed, you also slow down — that second brake is congestion control.",
    points: [
      "Connection-oriented: handshake, data, teardown.",
      "Reliable and ordered: retransmit, reorder buffer, cumulative ACKs, SACK.",
      "Flow control: advertised window. Congestion control: cwnd, ssthresh, slow start, AIMD.",
      "Ports multiplex a host. A 4-tuple (src IP, dst IP, src port, dst port) is a connection.",
      "TCP does not keep message boundaries. Two write()s can arrive as one read(), and vice versa.",
    ],
    mistakes: [
      "Assuming a send() corresponds to one recv(). It is a stream.",
      "Confusing flow control (protect the receiver) with congestion control (protect the network).",
      "Believing TCP 'guarantees delivery'. It guarantees that if the connection stays up, bytes arrive. A reset or timeout is a failure.",
    ],
    usage: ["HTTP/1.1 and HTTP/2", "SSH, SMTP, most databases' wire protocols"],
    interview: [
      iq("TCP vs UDP in two contrasts.", "TCP: connection, reliability, order, congestion control. UDP: datagrams, no connection, no retransmission, app-owned reliability.", "beginner"),
      iq("What is the 4-tuple?", "Source IP, destination IP, source port, destination port. NAT rewrites parts of it; that's why NAT is hard.", "intermediate"),
    ],
    extra: [{ type: "viz", id: "tcp-simulator" }],
  }),
  T({
    slug: "deadlocks",
    section: "os",
    title: "Deadlocks",
    summary: "A set of processes forever waiting for resources the others hold. Four Coffman conditions, and three ways out.",
    level: "intermediate",
    prereqs: ["mutex", "semaphore"],
    related: ["deadlock-prevention", "bankers-algorithm", "distributed-locks"],
    next: "deadlock-prevention",
    viz: "deadlock-simulator",
    lab: "deadlock-simulator",
    what: "A deadlock is a circular wait: P1 holds A and wants B, P2 holds B and wants A, and nobody will drop what they hold. No progress, no exception — just silence.",
    why: "Locks, database rows, and distributed leases all deadlock. If you cannot name the four conditions, you cannot choose a prevention strategy on purpose.",
    mental:
      "Two people in a corridor, each too polite to step back, each holding a box the other needs. The resource-allocation graph has a cycle.",
    points: [
      "Coffman: mutual exclusion, hold-and-wait, no preemption, circular wait. All four required.",
      "Prevention: break a condition (lock ordering breaks circular wait; allocate-all-at-once breaks hold-and-wait).",
      "Avoidance: Banker's algorithm admits a request only if a safe sequence still exists.",
      "Detection: find a cycle, then abort a victim. Databases do this; OS kernels usually do not for user mutexes.",
      "Livelock is not deadlock: everyone is running, nobody is progressing.",
    ],
    steps: [
      "Draw processes and resource instances.",
      "Add request and assignment edges.",
      "A cycle in a single-instance graph is a deadlock. Multi-instance needs a more careful reduction.",
      "Pick a strategy: prevent, avoid, detect-and-recover, or ostrich (common in user-space mutexes).",
    ],
    mistakes: [
      "Locking A then B in one thread and B then A in another. Order your locks globally.",
      "Calling a slow system 'deadlocked' without a cycle. It may be a convoy, an I/O wait, or a leak.",
      "Using timeouts as the only distributed deadlock strategy without fencing tokens.",
    ],
    usage: ["pthread mutexes", "InnoDB row locks", "Distributed lock managers"],
    interview: [
      iq("Four Coffman conditions?", "Mutual exclusion, hold and wait, no preemption, circular wait.", "beginner"),
      iq("How does lock ordering prevent deadlock?", "It makes a cycle impossible: all threads acquire locks in the same global order, so a wait-for cycle cannot form.", "intermediate"),
      iq("Deadlock vs starvation vs livelock?", "Deadlock: circular wait, no progress. Starvation: some process never gets the resource. Livelock: activity without progress.", "intermediate"),
    ],
    extra: [{ type: "viz", id: "deadlock-simulator" }],
  }),
  T({
    slug: "cpu-scheduling",
    section: "os",
    title: "CPU Scheduling",
    summary: "The policy that picks the next ready thread to run. Fairness, latency, and throughput are in tension.",
    level: "intermediate",
    prereqs: ["process-states", "context-switching"],
    related: ["fcfs", "sjf", "round-robin", "priority-scheduling"],
    next: "fcfs",
    viz: "cpu-scheduler",
    lab: "cpu-scheduler",
    what: "Whenever the CPU is about to sit idle or a scheduling event fires (quantum, wake, fork, yield), the scheduler chooses a ready thread. Preemptive schedulers can steal the CPU from a running thread; cooperative ones wait to be given it back.",
    why: "Interactive latency, batch throughput, and fairness are different objective functions. Linux CFS, real-time FIFO/RR, and a toy FCFS exam question are all answers to different questions.",
    mental:
      "A receptionist with a rule for who goes next. FCFS is a queue. RR is a queue with a kitchen timer. SJF is 'shortest appointment first' — optimal average wait if you can see the future.",
    points: [
      "Metrics: waiting time, turnaround, response time, CPU utilization, throughput.",
      "FCFS: simple, convoy effect.",
      "SJF / SRTF: best average wait; starvation of long jobs; need a burst predictor.",
      "Round robin: quantum too small → context-switch thrash; too large → FCFS.",
      "Priority: aging to avoid starvation. Multilevel feedback queues combine several of the above.",
    ],
    mistakes: [
      "Optimizing the average and ignoring the tail. Humans feel p99.",
      "A 1ms quantum on a machine whose context switch is 0.3ms — you are measuring the scheduler, not the work.",
    ],
    usage: ["OS kernels", "Thread pools and executors", "Distributed job queues (a cousin, not the same)"],
    interview: [
      iq("Why can SJF starve?", "A stream of short jobs keeps skipping a long one. Aging or a guaranteed slice fixes it.", "intermediate"),
      iq("Effect of a very small RR quantum?", "Response time looks snappy until context-switch overhead eats the CPU.", "beginner"),
    ],
    extra: [{ type: "viz", id: "cpu-scheduler" }],
  }),
  T({
    slug: "hash-tables",
    section: "dsa",
    title: "Hash Tables",
    summary: "Average O(1) insert and lookup by hashing a key to a bucket, then resolving collisions.",
    level: "intermediate",
    prereqs: ["arrays"],
    related: ["hash-maps", "sets", "randomized-algorithms"],
    next: "hash-maps",
    viz: "hash-collisions",
    lab: "hash-collisions",
    what: "A hash table stores key/value pairs in an array of buckets. A hash function maps keys to bucket indices. When two keys share a bucket, a collision strategy (chaining or open addressing) keeps both.",
    why: "Dictionaries, sets, caches, database hash indexes, and compiler symbol tables are hash tables. Interviews assume you can implement one and discuss load factor.",
    mental:
      "A row of cubbies and a rule for which cubby a name belongs in. When two names share a cubby, you either hang a chain of boxes or you walk to the next empty cubby.",
    points: [
      "Expected O(1) only with a good hash and a bounded load factor α = n / buckets.",
      "Chaining: bucket holds a list (or tree). Simple deletes. Cache-unfriendly.",
      "Open addressing: linear/quadratic probing, Robin Hood, cuckoo. Better cache behavior, fussier deletes.",
      "Resizing (rehashing) amortizes to O(1) if you grow by a constant factor.",
      "Security: untrusted keys need a keyed hash or you eat a collision DoS.",
    ],
    complexity: {
      time: "Average O(1) lookup/insert/delete; worst O(n) if everything collides",
      space: "O(n)",
      tradeoffs: ["Faster than trees for exact lookup, no order", "Worst-case and iteration order are the costs"],
    },
    mistakes: [
      "Using a mutable object as a key and then mutating it.",
      "Forgetting to override hashCode with equals (Java) or __hash__ with __eq__ (Python).",
      "Treating O(1) as a guarantee rather than an average.",
    ],
    usage: ["Language dict/map/set", "Caches", "Joins in query engines (hash join)"],
    code: {
      lang: "python",
      title: "Chaining in a handful of lines",
      code: `class HashMap:
    def __init__(self, m=8):
        self.b = [[] for _ in range(m)]
    def _i(self, k):
        return hash(k) % len(self.b)
    def set(self, k, v):
        i = self._i(k)
        for p in self.b[i]:
            if p[0] == k:
                p[1] = v
                return
        self.b[i].append([k, v])
    def get(self, k):
        for p in self.b[self._i(k)]:
            if p[0] == k:
                return p[1]`,
    },
    interview: [
      iq("Chaining vs open addressing?", "Chaining: easy delete, memory per node, degrades to lists. Open addressing: packed array, clustering, tombstones on delete.", "intermediate"),
      iq("What is load factor?", "n / number of buckets. Grow when it exceeds a threshold (0.7 is a common open-addressing default).", "beginner"),
    ],
    extra: [{ type: "viz", id: "hash-collisions" }],
  }),
  T({
    slug: "sorting",
    section: "dsa",
    title: "Sorting",
    summary: "Putting elements in order. Comparison sorts cannot beat n log n in the worst case; the constants and stability still matter.",
    level: "beginner",
    prereqs: ["arrays", "asymptotic-notation"],
    related: ["divide-conquer", "heaps", "binary-search"],
    next: "binary-search",
    viz: "algorithm-visualizer",
    lab: "algorithm-visualizer",
    what: "A sort permutation arranges elements so that each is ≤ the next under a total order. Stable sorts keep equal keys in their original relative order.",
    why: "Sorted data makes search, merge, sweep-line, and many greedy algorithms possible. Libraries hide the algorithm; interviews and kernels still care which one.",
    mental:
      "Every comparison gives one bit of information about an unknown permutation. There are n! permutations, so comparison sorts need ~ n log n comparisons in the worst case.",
    points: [
      "Insertion sort: O(n²), O(n) on nearly sorted, stable, tiny constant — fast for small n (and the bottom of Timsort/Introsort).",
      "Mergesort: O(n log n) always, stable, extra O(n) memory.",
      "Heapsort: O(n log n) always, in-place, not stable.",
      "Quicksort: O(n log n) average, O(n²) worst, in-place-ish; introsort bails to heap on a bad partition.",
      "Counting/radix: not comparison-based; linear when keys are integers in a range.",
    ],
    complexity: {
      time: "O(n log n) typical comparison sort",
      space: "O(1) to O(n) depending on algorithm",
      tradeoffs: ["Stability vs in-place", "Worst-case guarantee vs average-case speed", "Branchy vs sequential memory"],
    },
    usage: ["std::sort / list.sort", "Database ORDER BY and merge joins", "Inverted-index construction"],
    interview: [
      iq("Why n log n lower bound?", "A comparison tree that distinguishes n! leaves has height at least log2(n!) ~ n log n by Stirling.", "advanced"),
      iq("When is insertion sort the right sort?", "Tiny arrays, or nearly-sorted input. Also as the base case of a hybrid.", "beginner"),
      iq("Is quicksort stable?", "The usual in-place Lomuto/Hoare versions are not. Stability needs extra care (or a different algorithm).", "intermediate"),
    ],
    extra: [{ type: "viz", id: "algorithm-visualizer" }],
  }),
  T({
    slug: "binary-search",
    section: "dsa",
    title: "Binary Search",
    summary: "Repeatedly halve a monotonic search space until the answer is forced.",
    level: "beginner",
    prereqs: ["arrays", "searching"],
    related: ["sorting", "two-pointers"],
    next: "two-pointers",
    viz: "algorithm-visualizer",
    lab: "algorithm-visualizer",
    what: "If a predicate is false for a prefix of the search space and true after (or the array is sorted), you can throw away half of the remaining candidates per step.",
    why: "O(log n) is the difference between scanning a billion rows and touching 30. The same idea searches answer space ('binary search on the answer') not just arrays.",
    mental:
      "A dictionary: open the middle, decide left or right. The invariant is 'the answer, if it exists, is still in [lo, hi]'.",
    points: [
      "Array must be sorted (or the predicate monotonic).",
      "Overflow-safe mid: lo + (hi - lo) // 2, not (lo+hi)/2 on fixed-width ints.",
      "Off-by-one lives in the inclusive/exclusive bounds. Pick a convention and keep it.",
      "Lower bound vs upper bound vs exact match are three slightly different loops.",
    ],
    complexity: { time: "O(log n)", space: "O(1) iterative", tradeoffs: ["Needs sorted or monotonic data"] },
    code: {
      lang: "python",
      title: "Lower bound",
      code: `def lower_bound(a, x):
    lo, hi = 0, len(a)
    while lo < hi:
        mid = lo + (hi - lo) // 2
        if a[mid] < x:
            lo = mid + 1
        else:
            hi = mid
    return lo`,
    },
    mistakes: [
      "Forgetting the array must be sorted.",
      "Infinite loops from mid not moving (usually exclusive bound + wrong compare).",
    ],
    usage: ["std::lower_bound", "Finding a version that broke a test", "Parametric search on a monotonic cost"],
    interview: [
      iq("Time complexity and the condition it needs?", "O(log n) comparisons on a sorted array or monotonic predicate.", "beginner"),
      iq("Find the first True in a boolean array that is FFFTTT.", "Lower-bound binary search on the predicate. Classic 'search on the answer' setup.", "intermediate"),
    ],
    extra: [{ type: "viz", id: "algorithm-visualizer" }],
  }),
  T({
    slug: "bst",
    section: "dsa",
    title: "Binary Search Trees",
    summary: "A binary tree with left < node < right, so ordered operations run in time proportional to height.",
    level: "intermediate",
    prereqs: ["binary-trees"],
    related: ["avl-trees", "red-black-trees"],
    next: "avl-trees",
    viz: "bst-explorer",
    lab: "bst-explorer",
    what: "A BST stores comparable keys so that an in-order traversal is sorted. Search, min, max, successor, insert, and delete follow a path from the root — O(h).",
    why: "Ordered maps and sets, policy-based data, and the intuition behind tree indexes. Unbalanced, h = n and you have a linked list. Balanced (AVL, red-black, B-tree), h = Θ(log n).",
    mental:
      "Each node is a question: 'smaller? go left. larger? go right.' The tree is a freeze-frame of those questions.",
    points: [
      "Search compares and branches. Duplicate policy is a design choice (ban, count, or multiset).",
      "Insert walks to a null and hangs a node. Delete has three cases: leaf, one child, two children (splice successor).",
      "In-order = sorted. Pre-order and post-order are for copying and deleting structure.",
      "Balance is not free: rotations restore height; B-trees change the branching factor for disks.",
    ],
    complexity: {
      time: "O(h) per op; O(log n) if balanced, O(n) if not",
      space: "O(n)",
      tradeoffs: ["Order statistics vs hash tables' average O(1)", "Balance maintenance vs simplicity"],
    },
    mistakes: [
      "Inserting sorted keys into an unbalanced BST and calling it O(log n).",
      "Deleting a two-child node without a consistent successor/predecessor rule.",
    ],
    usage: ["std::map / TreeMap", "Database memory-resident trees (the on-disk cousin is B+)", "Set operations that need order"],
    interview: [
      iq("When is a BST O(n)?", "When it degenerates (sorted inserts without balancing).", "beginner"),
      iq("Delete a node with two children.", "Replace with in-order successor (min of right subtree) or predecessor, then delete that node.", "intermediate"),
    ],
    extra: [{ type: "viz", id: "bst-explorer" }],
  }),
  T({
    slug: "bfs",
    section: "dsa",
    title: "Breadth-First Search",
    summary: "Explore vertices in order of distance from a source, using a queue. Shortest paths in unweighted graphs.",
    level: "intermediate",
    prereqs: ["graphs", "queue"],
    related: ["dfs", "dijkstra"],
    next: "dfs",
    viz: "graph-search",
    lab: "graph-search",
    what: "BFS starts at a source, visits neighbors, then their neighbors, never revisiting. The first time you reach a node is a shortest path in hop count.",
    why: "Unweighted shortest path, bipartiteness, connected components in unweighted graphs, and the mental model of a wavefront. Many 'levels' problems are BFS.",
    mental: "A ripple in a pond. The queue holds the current wavefront. Distance[v] is the time the ripple hits v.",
    points: [
      "Mark visited when you enqueue (not when you dequeue) to avoid duplicate queue entries.",
      "Parent pointers reconstruct the path.",
      "On a tree, BFS by levels is just a queue; on a graph, visited is mandatory.",
      "0-1 BFS (deque) handles edges of weight 0 or 1.",
    ],
    complexity: { time: "O(V+E)", space: "O(V)", tradeoffs: ["Needs a queue of up to Θ(V)", "Not for positive weighted edges — that is Dijkstra"] },
    mistakes: ["Using BFS for weighted shortest paths", "Marking visited on dequeue and exploding the queue"],
    usage: ["Social-network distance", "Flood fill", "Shortest path in grids"],
    interview: [
      iq("Why is the first hit the shortest?", "All edges have the same cost, so nodes are dequeued in nondecreasing distance.", "intermediate"),
      iq("BFS vs Dijkstra?", "BFS is Dijkstra with a queue instead of a heap, legal when every edge weight is 1.", "intermediate"),
    ],
    extra: [{ type: "viz", id: "graph-search" }],
  }),
  T({
    slug: "dijkstra",
    section: "dsa",
    title: "Dijkstra's Algorithm",
    summary: "Single-source shortest paths on nonnegative weights, growing a settled set with a priority queue.",
    level: "intermediate",
    prereqs: ["graphs", "priority-queues", "bfs"],
    related: ["bellman-ford", "bfs"],
    next: "bellman-ford",
    viz: "dijkstra",
    lab: "dijkstra",
    what: "Dijkstra repeatedly settles the unsettled vertex with the smallest tentative distance, then relaxes its outgoing edges. Nonnegative weights make the greedy choice safe.",
    why: "Maps, routing, network delay, and any 'cheapest path' with nonnegative costs. It is the weighted cousin of BFS.",
    mental:
      "You always expand the closest frontier node. Because remaining edges are not negative, nothing later can undercut a settled node.",
    points: [
      "Initialize dist[s]=0, others ∞. Min-heap of (dist, node).",
      "Pop the smallest; skip if it is a stale heap entry.",
      "Relax neighbors: if dist[u]+w < dist[v], update and push.",
      "Negative edges break the greedy proof — use Bellman-Ford.",
      "With a binary heap: O((V+E) log V). Fibonacci: O(E + V log V).",
    ],
    complexity: { time: "O((V+E) log V) binary heap", space: "O(V)", tradeoffs: ["Fast for sparse nonnegative graphs", "No negative edges"] },
    mistakes: ["Running Dijkstra on a graph with a negative edge", "Forgetting stale heap entries and 'decreasing key'"],
    usage: ["OSPF-style routing (conceptual)", "Game maps", "Network latency"],
    interview: [
      iq("Why nonnegative?", "Once a node is popped as minimum, no path through an unsettled node can be cheaper, because those remaining pieces cost ≥ 0.", "advanced"),
      iq("How does BFS relate?", "BFS is Dijkstra when every weight is 1; a FIFO queue is a valid priority queue in that special case.", "intermediate"),
    ],
    extra: [{ type: "viz", id: "dijkstra" }],
  }),
  T({
    slug: "asymptotic-notation",
    section: "dsa",
    title: "Big-O, Theta, Omega",
    summary: "Notation for how time and space grow as input size n tends to infinity: upper, tight, and lower bounds.",
    level: "beginner",
    prereqs: ["functions"],
    related: ["sorting", "recurrence-relations"],
    next: "searching",
    what: "Big-O is an upper bound, Ω a lower bound, Θ a tight bound — all up to constant factors and for large n. They describe functions, not machines.",
    why: "It is the shared language for algorithm cost. 'Is this fast?' is meaningless; 'this is O(n log n) comparisons' is a claim you can check.",
    mental:
      "Ignore the furniture (constants, lower-order terms) and keep the shape. n² eventually beats 1000 n, no matter how embarrassed n² looks at n=3.",
    points: [
      "f = O(g) if f(n) ≤ c g(n) for some c>0 and all large n.",
      "f = Ω(g) if f is at least a constant times g for large n.",
      "f = Θ(g) if f is both O(g) and Ω(g).",
      "Worst / average / best case are different functions you might bound.",
      "Logarithms grow slower than every positive power. Exponentials grow faster than every polynomial.",
    ],
    extra: [
      {
        type: "table",
        headers: ["Name", "Typical", "Example"],
        rows: [
          ["O(1)", "constant", "Hash table expected lookup"],
          ["O(log n)", "logarithmic", "Binary search"],
          ["O(n)", "linear", "Scan an array"],
          ["O(n log n)", "linearithmic", "Mergesort"],
          ["O(n²)", "quadratic", "Naive double loop"],
          ["O(2ⁿ)", "exponential", "Subset enumeration"],
        ],
      },
    ],
    mistakes: [
      "Saying 'the algorithm is O(n²) so it cannot be O(n³)' — O is an upper bound; O(n²) implies O(n³).",
      "Dropping the average/worst distinction for quicksort or hash tables.",
    ],
    usage: ["Every algorithm discussion", "Capacity planning (roughly)", "Interview warm-ups"],
    interview: [
      iq("Is binary search O(n)?", "Yes, because O is an upper bound — but Θ(log n) is the tight statement you actually want.", "intermediate"),
      iq("Order these: n!, 2ⁿ, n², n log n, log n.", "log n < n log n < n² < 2ⁿ < n! (for large n).", "beginner"),
    ],
  }),
  T({
    slug: "processes",
    section: "os",
    title: "Processes",
    summary: "The OS abstraction of a running program: an address space, one or more threads, and kernel bookkeeping.",
    level: "beginner",
    prereqs: ["what-is-os", "memory"],
    related: ["threads", "process-states", "linux-process-model"],
    next: "threads",
    viz: "process-states",
    lab: "process-states",
    what: "A process is the unit of isolation: its own virtual memory, file-descriptor table, credentials, and at least one thread of execution. Creating one is expensive; isolating two from each other is the point.",
    why: "Crash a process, the others live. Security boundaries, resource limits, and 'that service' as a noun — all process-shaped.",
    mental:
      "A process is a house (address space) with one or more people in it (threads). The kernel is the city: it schedules people, meters utilities, and keeps houses from walking into each other.",
    points: [
      "PCB / task_struct: PID, state, registers, mm_struct, files, signal mask.",
      "fork copies; exec replaces the image; wait reaps. Copy-on-write makes fork cheap until a write.",
      "Threads share the house; processes do not (unless they map shared memory on purpose).",
      "Isolation is virtual memory plus kernel-mediated I/O, not a pinky promise.",
    ],
    mistakes: ["Calling a thread a process", "Forgetting zombies: a dead child still occupies a PCB until wait"],
    usage: ["OS isolation", "Browsers (process-per-site)", "Containers as groups of processes"],
    interview: [
      iq("Process vs thread?", "A process is an address space and OS identity. A thread is a schedulable context. Threads in one process share memory; processes do not by default.", "beginner"),
      iq("What does fork() return?", "0 in the child, child's PID in the parent, -1 on failure.", "intermediate"),
    ],
    extra: [{ type: "viz", id: "process-states" }],
  }),
  T({
    slug: "paging",
    section: "os",
    title: "Paging",
    summary: "Fixed-size virtual pages mapped onto physical frames through a page table (and a TLB).",
    level: "intermediate",
    prereqs: ["memory-management"],
    related: ["virtual-memory", "page-tables", "tlb"],
    next: "virtual-memory",
    viz: "paging-simulator",
    lab: "paging-simulator",
    what: "Virtual address spaces are chopped into pages (often 4 KiB). Physical memory is chopped into frames of the same size. The page table records which page lives in which frame, or that it is not resident.",
    why: "Paging gives isolation, sparse address spaces, sharing (map the same frame twice), and the ability to overcommit with disk. It is how every modern general-purpose OS presents memory.",
    mental:
      "A library of equal-sized boxes. Your library card (virtual address) names a box and an offset. The catalog (page table) tells the clerk which shelf (frame) that box is on, or that it is in off-site storage (swap).",
    points: [
      "Split the VA: VPN + offset. Walk the page table to a PFN, then PFN+offset.",
      "Multi-level tables keep the catalog sparse. x86-64 is four (or five) levels.",
      "TLB caches recent translations. A miss walks the table; a fault may trap to the OS.",
      "A page fault is not always an error: demand paging, copy-on-write, and growth of the stack/heap use it.",
    ],
    mistakes: ["Mixing page size with frame size — they match", "Thinking swap is required for virtual memory (overcommit is optional; translation is not)"],
    usage: ["Every user process", "mmap of files", "Shared libraries mapped once, used many times"],
    interview: [
      iq("What happens on a TLB miss?", "Hardware (or software, on some ISAs) walks the page table. If the PTE is invalid, the OS gets a page fault.", "intermediate"),
      iq("Why multi-level page tables?", "A flat table for a 48-bit space would be huge. Levels let unused regions take no RAM.", "intermediate"),
    ],
    extra: [{ type: "viz", id: "paging-simulator" }],
  }),
  T({
    slug: "acid",
    section: "dbms",
    title: "ACID",
    summary: "Atomicity, Consistency, Isolation, Durability — the contract a transactional store claims to keep.",
    level: "intermediate",
    prereqs: ["transactions"],
    related: ["isolation-levels", "wal", "cap-theorem"],
    next: "isolation-levels",
    viz: "transaction-simulator",
    lab: "transaction-simulator",
    what: "Atomicity: all of a transaction or none. Consistency: integrity constraints hold after commit. Isolation: concurrent transactions do not produce results that no serial order could. Durability: a committed change survives a crash.",
    why: "Ledgers, inventory, and bookings cannot be 'eventually' correct in the small. ACID is the name of that requirement. Distributed systems then explain how expensive it is.",
    mental:
      "A bank transfer is one story: subtract here, add there. Power fails in the middle — atomicity. Two tellers — isolation. The next morning, the story is still there — durability.",
    points: [
      "Atomicity is undo/redo: WAL + rollback.",
      "Consistency here means constraints (keys, checks), not CAP-consistency.",
      "Isolation is a spectrum: read committed, repeatable read, snapshot, serializable.",
      "Durability is fsync (or equivalent) of the log before commit returns.",
    ],
    mistakes: [
      "Using 'consistent' in the CAP sense while talking about ACID.",
      "Assuming default isolation is serializable (Postgres default is read committed).",
    ],
    usage: ["Relational OLTP", "Payment ledgers", "Any 'this row and that row or neither'"],
    interview: [
      iq("Spell ACID with a one-line each.", "Atomic: all or nothing. Consistent: constraints hold. Isolated: concurrency does not create non-serial effects. Durable: commit means crash-safe.", "beginner"),
      iq("How does a WAL give you A and D?", "D: the log hits disk before commit returns. A: uncommitted changes are in the log as undo (or not replayed on recovery).", "advanced"),
    ],
    extra: [{ type: "viz", id: "transaction-simulator" }],
  }),
  T({
    slug: "sql",
    section: "dbms",
    title: "SQL",
    summary: "A declarative language for describing a result over tables: the engine picks the plan.",
    level: "beginner",
    prereqs: ["relational-databases"],
    related: ["joins", "indexes", "query-optimization"],
    next: "tables",
    viz: "sql-playground",
    lab: "sql-playground",
    what: "SQL lets you say what you want (a relation) rather than how to get it. SELECT, FROM, WHERE, GROUP BY, HAVING, ORDER BY, and JOIN are the everyday core. The optimizer is allowed to reorder and pick indexes as long as the result matches the spec.",
    why: "It is the lingua franca of data. Application code that fights SQL (row-by-row) loses; code that describes sets wins.",
    mental:
      "A pipeline of relational operators: scan, filter, project, join, aggregate, sort. You write a description; EXPLAIN shows the pipeline they chose.",
    points: [
      "Logical processing order is not the written order: FROM/JOIN → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT.",
      "NULL is not a value; it poisons most comparisons. IS NULL exists for a reason.",
      "Joins are predicates, not arrows in an ORM. Know inner vs left.",
      "Indexes are not hints you sprinkle after the query is slow — they are data structures the planner can choose.",
    ],
    code: {
      lang: "sql",
      title: "Filter, join, aggregate",
      code: `SELECT u.country, COUNT(*) AS n, SUM(o.amount) AS revenue
FROM users u
JOIN orders o ON o.user_id = u.id
WHERE o.amount > 0
GROUP BY u.country
HAVING COUNT(*) >= 2
ORDER BY revenue DESC;`,
    },
    mistakes: ["SELECT *" , "Joining in the application loop", "WHERE col = NULL"],
    usage: ["OLTP apps", "Analytics", "Migrations and admin"],
    interview: [
      iq("WHERE vs HAVING?", "WHERE filters rows before grouping. HAVING filters groups after aggregation.", "beginner"),
      iq("What does an inner join drop?", "Rows that do not match the join predicate on the other side.", "beginner"),
    ],
    extra: [{ type: "viz", id: "sql-playground" }],
  }),
  T({
    slug: "transformers",
    section: "deep-learning",
    title: "Transformers",
    summary: "An architecture of stacked self-attention and MLPs, with residuals and normalization, that models sequences without recurrence.",
    level: "advanced",
    prereqs: ["attention", "neural-networks"],
    related: ["tokenization", "pretraining", "positional-encoding"],
    next: "tokens",
    viz: "neural-net",
    lab: "neural-net",
    what: "A transformer block mixes tokens with multi-head self-attention, then applies a position-wise MLP, each with residual connections and layer norm. Stacking blocks, plus positional information, is the model. No recurrence is required.",
    why: "This is the architecture behind modern language, vision, and multimodal models. Training parallelizes across the sequence; inference still pays for every extra token of context.",
    mental:
      "Every token looks at every other token (inside a window), writes a weighted summary, then thinks about that summary with an MLP. Depth is more of those blocks.",
    points: [
      "Self-attention is O(n²) in sequence length for the naive implementation.",
      "Multi-head: several attention patterns in parallel, then concatenated.",
      "Decoder-only models (GPT-style) mask so a token cannot see the future.",
      "Encoder-decoder (original Vaswani) is still the translation template.",
      "Positional encodings inject order; RoPE is the current default in many LLMs.",
    ],
    mistakes: [
      "Calling the tokenizer 'the transformer'.",
      "Ignoring the KV cache when talking about inference cost.",
    ],
    usage: ["LLMs", "Vision transformers", "Speech and multimodal models"],
    interview: [
      iq("Why did transformers beat RNNs for pretraining?", "Attention parallelizes over the sequence during training; RNNs are inherently sequential. Residual blocks also train deeper.", "intermediate"),
      iq("Where does the n² come from?", "Each of n queries dots with n keys. Sparse and linear attention try to dodge that.", "advanced"),
    ],
  }),
  T({
    slug: "cap-theorem",
    section: "system-design",
    title: "CAP Theorem",
    summary: "During a network partition, a replicated store cannot be both linearly consistent and available for all requests.",
    level: "intermediate",
    prereqs: ["consistency-models", "network-partitions"],
    related: ["acid-vs-base", "quorum", "eventual-consistency"],
    next: "acid-vs-base",
    what: "Brewer's conjecture, proved by Gilbert and Lynch: in an asynchronous network that partitions, you cannot have both linearizability and liveness for all operations. You pick which to degrade.",
    why: "It is the most abused slide in system design interviews — and still the right first question: when the network splits, what should a replica do? Error, or a possibly stale/forked answer?",
    mental:
      "Two rooms, a wall between them, both have a copy of a notebook. They cannot agree and keep taking notes. Either they stop writing (availability loses) or they write different stories (linearizability loses).",
    points: [
      "C in CAP is linearizability (a strong single-copy story), not ACID consistency.",
      "Partition is not optional on real WANs. Timeouts are how you notice.",
      "Most systems are neither 'CP' nor 'AP' as a personality — they pick per operation.",
      "Latency and practicality (PACELC) are the sequel: even without a partition, you trade consistency vs latency.",
    ],
    mistakes: [
      "Saying 'Mongo is AP, Postgres is CP' as if that were a complete design.",
      "Using CAP to avoid talking about the actual failure you care about.",
    ],
    usage: ["Replicated databases", "Multi-region services", "Design interviews"],
    interview: [
      iq("State CAP precisely.", "In the presence of a partition, a replicated register cannot be both linearly consistent and available for every request.", "intermediate"),
      iq("Give a CP behavior and an AP behavior.", "CP: a minority replica refuses writes. AP: both sides accept writes and repair later (conflict, CRDT, last-write-wins).", "advanced"),
    ],
  }),
  T({
    slug: "url-shortener",
    section: "system-design",
    title: "URL Shortener",
    summary: "A tiny unique key that 301/302s to a long URL — a classic design interview that still forces real choices.",
    level: "intermediate",
    prereqs: ["hash-tables", "load-balancers"],
    related: ["caches-sd", "twitter"],
    next: "twitter",
    what: "Clients POST a long URL and receive a short key (base62 id or a hash). GET /{key} looks up the long URL and redirects. Reads dwarf writes. Keys must not collide and should not be guessable if the product is private.",
    why: "It is the smallest design that still has capacity math, a data model, a cache, and a failure mode. If you can do this cleanly, longer designs are the same shapes bigger.",
    mental:
      "A hash map with a public HTTP front and a 301. Everything else — IDs, cache, analytics, custom aliases — is product.",
    points: [
      "Requirements: write a mapping, read a redirect, optional expiry and custom aliases, optional analytics.",
      "Capacity: estimate writes/day, reads/day, storage of key+URL, and whether it fits in one primary.",
      "ID: counter + base62 (simple, guessable) vs hash of URL (collisions, not reversible) vs pre-generated keys.",
      "Data: key (PK), long URL, created_at, expiry, user_id. Cache the hot keys (they are Zipf).",
      "Redirect 301 vs 302: 301 caches at the client/CDN — bad if you need analytics on every click or might change the target.",
    ],
    steps: [
      "Functional and non-functional requirements. Ask about custom aliases and preview pages.",
      "Back-of-envelope: 100M new URL/month, 100:1 read/write, ~500 B/row → storage and QPS.",
      "API: POST /v1/links, GET /{key}.",
      "Single-region: load balancer, app, primary+replica DB, Redis for hot keys.",
      "Scale writes with a range-allocated ID service; scale reads with cache + more replicas.",
      "Failures: cache stampede, ID exhaustion, hot key, abused short links.",
    ],
    mistakes: [
      "Jumping to Kafka and Kubernetes for a million rows.",
      "Using 301 then wondering why click counts are wrong.",
      "MD5 of the URL as the key without a collision plan.",
    ],
    usage: ["bit.ly-style products", "Internal aliasing", "The first system-design interview"],
    interview: [
      iq("How do you generate keys?", "A monotonic ID encoded in base62, allocated in ranges so app servers do not share a single SQL counter on every write. Hashing the URL needs a collision strategy and does not produce sequential IDs.", "intermediate"),
      iq("301 or 302?", "302 (or 307) if you need to see every click or change targets. 301 if the mapping is permanent and you want client-side caching.", "intermediate"),
    ],
  }),
  T({
    slug: "python",
    section: "languages",
    title: "Python",
    summary: "A dynamic, garbage-collected language with a readable syntax, a vast ecosystem, and a GIL-shaped concurrency story (CPython).",
    level: "beginner",
    prereqs: ["what-is-programming"],
    related: ["javascript", "garbage-collection"],
    next: "javascript",
    what: "Python is a dynamically typed, interpreted (bytecode VM) language. Everything is an object. Iteration, slicing, and a standard library aimed at 'batteries included' made it the default for scripting, science, and a large fraction of backend services.",
    why: "It is the language of ML, of glue, and of a huge number of interviews. The object model, iterators, and packaging are the parts that still surprise people after the syntax fades.",
    mental:
      "Names in namespaces pointing at objects on a heap. Indentation is block structure. The CPython GIL means one bytecode-executing thread at a time; I/O and C extensions release it.",
    points: [
      "Names, objects, mutability. Lists vs tuples vs dicts vs sets.",
      "Functions are objects; closures and decorators follow.",
      "Iterators and generators: lazy pipelines.",
      "Packaging: venv, pip, and the import path.",
      "Typing is optional and erased — useful for humans and tools, not the VM.",
    ],
    code: {
      lang: "python",
      title: "A small, idiomatic slice",
      code: `from collections import Counter

def top_k(words: list[str], k: int) -> list[str]:
    counts = Counter(w.lower() for w in words)
    return [w for w, _ in counts.most_common(k)]`,
    },
    mistakes: ["Mutable default arguments", "Assuming threads speed CPU-bound CPython", "Bare except:"],
    usage: ["Data and ML", "Glue and automation", "Web backends (Django, FastAPI)"],
    interview: [
      iq("List vs tuple?", "Lists are mutable sequences. Tuples are immutable (and thus hashable if their items are). Use tuples for fixed records and dict keys.", "beginner"),
      iq("What is the GIL?", "CPython's global interpreter lock: only one thread executes Python bytecode at a time. Use processes or C/SIMD for CPU parallelism.", "intermediate"),
    ],
  }),
  T({
    slug: "dfa",
    section: "theory",
    title: "DFA",
    summary: "A deterministic finite automaton: finitely many states, one next state per (state, symbol), no extra memory.",
    level: "intermediate",
    prereqs: ["regular-expressions"],
    related: ["nfa", "regular-languages"],
    next: "nfa",
    viz: "dfa-simulator",
    lab: "dfa-simulator",
    what: "A DFA is (Q, Σ, δ, q0, F): states, alphabet, transition function, start, accept set. It reads a string left to right and accepts if it lands in F. No stack, no tape — just the current state.",
    why: "Lexers are DFAs. Network IDSes compile patterns to DFAs. The pumping lemma and the Myhill–Nerode theorem describe exactly what this machine can see.",
    mental:
      "A flowchart that is not allowed to doodle in the margins. After each character you are in exactly one bubble.",
    points: [
      "δ is a total function in the textbook DFA (add a dead state if you like partial).",
      "NFAs are more convenient; the subset construction produces an equivalent DFA, possibly 2^n states.",
      "Minimization (Hopcroft) is unique up to renaming — the canonical machine for a regular language.",
      "You cannot count arbitrarily high. 'Same number of a's and b's' is not regular.",
    ],
    mistakes: ["Drawing an NFA and calling it deterministic", "Using a DFA to parse nested parentheses"],
    usage: ["Lexers", "Protocol parsers for regular framed traffic", "Teaching regular languages"],
    interview: [
      iq("DFA vs NFA?", "DFA: one state, one transition. NFA: a set of states, ε-moves allowed. Same languages; NFAs can be exponentially smaller.", "intermediate"),
      iq("Why can't a DFA do balanced parentheses?", "It would need to count unbounded nesting. Finite states can only count modulo a constant.", "advanced"),
    ],
    extra: [{ type: "viz", id: "dfa-simulator" }],
  }),
  T({
    slug: "compiler-design",
    section: "compilers",
    title: "Compiler Design",
    summary: "A pipeline from source characters to machine code: lex, parse, analyze, optimize, emit.",
    level: "intermediate",
    prereqs: ["compiler"],
    related: ["lexer", "parser", "ast", "ir"],
    next: "lexer",
    viz: "compiler-explorer",
    lab: "compiler-explorer",
    what: "A compiler is a staged translator. The front end enforces the language (tokens, tree, types). The middle end rewrites an IR for a cost model. The back end selects instructions and registers for a machine.",
    why: "Every language you use is implemented this way, including the JITs inside V8 and HotSpot. Debugging a confusing error often means knowing which stage produced it.",
    mental:
      "A factory: raw text in, a crate of bytes out. Inspectors at each station reject bad programs; later stations are allowed to change the program only if you cannot tell from the outside.",
    points: [
      "Lex: chars → tokens. Parse: tokens → AST. Semantic analysis: names and types.",
      "IR (often SSA) is where optimization is sane.",
      "Backend: instruction selection, scheduling, register allocation, calling convention.",
      "A compiler plus a runtime (GC, unwinder) is a language implementation.",
    ],
    steps: [
      "Source",
      "Lexer → tokens",
      "Parser → AST",
      "Semantic analysis / type check",
      "IR",
      "Optimization",
      "Machine code",
    ],
    mistakes: ["Calling javac an interpreter", "Assuming -O3 is always faster (and always correct for unsafe languages)"],
    usage: ["Language implementations", "JIT compilers", "Query compilers in databases"],
    interview: [
      iq("Front end vs back end?", "Front end is language-specific (lex, parse, types). Back end is machine-specific (instr sel, regs). IR is the handshake.", "beginner"),
      iq("Why IR instead of optimizing ASTs?", "ASTs still look like the source. IR (especially SSA) makes dataflow obvious and machine-independent optimizations reusable.", "advanced"),
    ],
    extra: [{ type: "viz", id: "compiler-explorer" }, { type: "flow", steps: ["Source", "Lexer", "Tokens", "Parser", "AST", "Types", "IR", "Opt", "Code"] }],
  }),
  T({
    slug: "load-balancers",
    section: "system-design",
    title: "Load Balancers",
    summary: "A front door that spreads requests across backends, hides churn, and health-checks the fleet.",
    level: "intermediate",
    prereqs: ["scalability"],
    related: ["reverse-proxies", "api-gateways", "consistent-hashing"],
    next: "reverse-proxies",
    viz: "load-balancer",
    lab: "load-balancer",
    what: "A load balancer accepts client connections and forwards them to one of several healthy backends using a policy: round-robin, least-connections, random, or hash of a key. It is L4 (TCP packets) or L7 (HTTP routes, TLS, sticky cookies).",
    why: "Horizontal scale, rolling deploys, and a single name for a changing set of machines. Without a health check it is a random outage amplifier.",
    mental:
      "A receptionist with a clipboard of who is in today, handing each visitor to a free teller — or to the same teller if the visitor has a cookie.",
    points: [
      "L4: fast, dumb, connection-based. L7: slow, smart, content-based.",
      "Health checks remove bad backends. Fail-open vs fail-closed is a product decision.",
      "Sticky sessions are a crutch; better to store session in Redis/JWT.",
      "The balancer can itself be scaled (anycast, DNS, or a pair with VRRP).",
    ],
    mistakes: ["No health check", "Load-balancing a stateful service without affinity or shared state"],
    usage: ["Every multi-instance web service", "Kubernetes Services / Ingress", "DNS as a crude global LB"],
    interview: [
      iq("L4 vs L7 load balancer?", "L4 inspects IP/port and forwards TCP. L7 parses HTTP/TLS, can route on path and header, and can terminate TLS.", "intermediate"),
      iq("What happens when a backend dies?", "Health checks fail, it is pulled from the pool, in-flight connections error or drain. New requests go elsewhere.", "beginner"),
    ],
    extra: [{ type: "viz", id: "load-balancer" }],
  }),
  T({
    slug: "virtual-memory",
    section: "os",
    title: "Virtual Memory",
    summary: "Each process sees a private address space, translated by hardware onto RAM and, if you like, disk.",
    level: "intermediate",
    prereqs: ["paging"],
    related: ["page-tables", "page-replacement", "tlb"],
    next: "page-tables",
    viz: "paging-simulator",
    lab: "paging-simulator",
    what: "Virtual memory is the illusion that every process owns a large, private, contiguous address space. The MMU translates; the OS fills in pages on demand, shares them when useful, and can evict them to disk.",
    why: "Without it, programs would have to be relocated by hand, isolation would be cooperative, and mmap would not exist. It is the memory story of every mainstream OS.",
    mental:
      "A process names apartments in a building that is mostly empty. The city (OS) assigns real rooms when someone actually opens a door, and may move furniture to a warehouse (swap) if the city is crowded.",
    points: [
      "Isolation: one process cannot name another's pages (unless shared on purpose).",
      "Relocation: the same binary can run at the same virtual address in every process (ASLR notwithstanding).",
      "Overcommit and demand paging: allocate on first touch.",
      "mmap: files become arrays of bytes in the address space.",
    ],
    mistakes: ["Equating virtual memory with swap", "Assuming malloc immediately consumes RAM"],
    usage: ["Process isolation", "Shared libraries", "File-backed maps"],
    interview: [
      iq("Virtual memory without swap — still virtual?", "Yes. Translation and isolation do not require a paging file. Swap is a policy on top.", "intermediate"),
    ],
    extra: [{ type: "viz", id: "paging-simulator" }],
  }),
  T({
    slug: "attention",
    section: "deep-learning",
    title: "Attention",
    summary: "A weighted sum of values, with weights from a compatibility function between a query and keys.",
    level: "intermediate",
    prereqs: ["neural-networks"],
    related: ["transformers", "positional-encoding"],
    next: "transformers",
    viz: "neural-net",
    what: "Attention produces, for a query vector q, a distribution over keys k_i and then a corresponding mix of values v_i. Scaled dot-product attention is softmax(qKᵀ / √d) V.",
    why: "It is the mixing primitive of transformers. Once you can see 'this token looks at those tokens', the rest of an LLM diagram is plumbing.",
    mental:
      "A query is a question, keys are catalog cards, values are the books. Attention pulls a handful of books in proportion to how well the cards match the question.",
    points: [
      "Self-attention: Q, K, V all come from the same sequence (different projections).",
      "Cross-attention: Q from one sequence, K/V from another (encoder-decoder).",
      "Heads in parallel learn different match patterns.",
      "Softmax is peaked; temperature/scaling (√d) keeps it from saturating at init.",
    ],
    mistakes: ["Thinking attention is a search index (it is a soft weighted average, not a hard retrieval)"],
    usage: ["Transformers", "Aligning source and target in translation", "Perceiver-style architectures"],
    interview: [
      iq("Write the scaled-dot-product formula.", "softmax(QKᵀ / √d_k) V", "intermediate"),
      iq("Why scale by √d?", "Dot products of d-dimensional unit-ish vectors grow like √d; without scaling, softmax saturates and gradients die.", "advanced"),
    ],
  }),
  T({
    slug: "dynamic-programming",
    section: "dsa",
    title: "Dynamic Programming",
    summary: "Solve overlapping subproblems once, store the answer, and build the original problem from them.",
    level: "intermediate",
    prereqs: ["recursion-algo"],
    related: ["greedy", "divide-conquer"],
    next: "bfs",
    what: "DP applies when an optimum (or a count) of a problem is composed of optima of smaller problems, and those smaller problems repeat. Memoized recursion or an explicit table both count.",
    why: "Knapsack, LCS, edit distance, shortest paths in DAGs, and a large fraction of interview problems. Greedy is faster when it works; DP is the general hammer for optimal substructure.",
    mental:
      "A recursive solution that keeps a notebook. The second time you see the same subproblem, you copy the answer instead of recomputing the tree.",
    points: [
      "Two ingredients: optimal substructure, overlapping subproblems.",
      "Top-down (memo) vs bottom-up (table). Same asymptotics, different stack and control.",
      "State design is the whole problem: what is the smallest description that determines the answer?",
      "Time is (number of states) × (work per state).",
    ],
    mistakes: [
      "Memoizing a function whose arguments are not the full state.",
      "Using DP where a greedy proof exists and an O(n) pass would do.",
    ],
    usage: ["Edit distance in diff and DNA", "Resource allocation", "Parsing-adjacent algorithms"],
    code: {
      lang: "python",
      title: "Fibonacci as the mascot (not a real use)",
      code: `from functools import cache

@cache
def fib(n: int) -> int:
    if n < 2:
        return n
    return fib(n - 1) + fib(n - 2)`,
    },
    interview: [
      iq("DP vs divide-and-conquer?", "Both split. D&C subproblems are disjoint (sort halves). DP subproblems overlap (fib, knapsack).", "intermediate"),
      iq("How do you know the state is right?", "If two calls with that state must return the same answer, and every transition stays inside the state space.", "advanced"),
    ],
  }),
  T({
    slug: "linux-fundamentals",
    section: "linux",
    title: "Linux Fundamentals",
    summary: "A Unix-like kernel, a single filesystem tree, processes, and a shell that composes small tools.",
    level: "beginner",
    prereqs: ["what-is-os"],
    related: ["linux-filesystem", "shell", "permissions"],
    next: "linux-filesystem",
    viz: "linux-terminal",
    lab: "linux-terminal",
    what: "Linux is a kernel. A Linux system is that kernel plus a userspace (GNU or otherwise): a C library, a shell, tools, and a package manager. Everything is composed through files, file descriptors, and text where it is reasonable.",
    why: "Servers, containers, Android, and most development machines. If you cannot move around a Unix box, every other backend topic is theoretical.",
    mental:
      "A tree of files, a table of processes, and a kernel in the middle handing out CPU, memory, and descriptors. The shell is how a human speaks that language.",
    points: [
      "Kernel vs userspace vs distribution.",
      "The filesystem as the unifying namespace (/proc, /sys, /dev included).",
      "Users, permissions, and the real/effective IDs.",
      "Processes, signals, and jobs in the shell.",
      "Pipes and redirection as the composition operator.",
    ],
    mistakes: ["Treating the GUI as the OS", "Running everything as root because a permission error appeared"],
    usage: ["Servers", "Containers", "Development environments"],
    interview: [
      iq("What is a distribution?", "The kernel plus a coherent userspace: packages, init, defaults. Ubuntu and Alpine share a kernel family, not a userspace.", "beginner"),
    ],
    extra: [{ type: "viz", id: "linux-terminal" }],
  }),
  T({
    slug: "arrays",
    section: "dsa",
    title: "Arrays",
    summary: "A contiguous block of elements with O(1) index access and O(n) insert in the middle.",
    level: "beginner",
    prereqs: ["memory"],
    related: ["strings-ds", "linked-lists"],
    next: "strings-ds",
    viz: "algorithm-visualizer",
    lab: "algorithm-visualizer",
    what: "An array stores n elements of a known size next to each other in memory. Index i lives at base + i * stride. Random access is a multiply and a load; inserting in the middle is a memmove.",
    why: "It is the default sequence: cache-friendly, simple, and the backing store of dynamic arrays (vectors, ArrayLists) that amortize append to O(1).",
    mental: "A numbered row of lockers. Locker 100 is as easy to open as locker 1. Opening a gap at locker 1 means sliding everyone else down.",
    points: [
      "Access Θ(1), scan Θ(n), insert/delete at an arbitrary index Θ(n).",
      "Dynamic arrays grow by a factor (usually 2); append is amortized Θ(1).",
      "Cache locality makes arrays faster in practice than linked lists for almost all scans.",
      "Strings are arrays of code units with extra rules.",
    ],
    complexity: {
      time: "O(1) index; O(n) insert in middle; amortized O(1) append on a vector",
      space: "O(n)",
      tradeoffs: ["Fast index vs expensive insert", "Fixed vs resizable"],
    },
    mistakes: ["Off-by-one", "Confusing array length with capacity", "Using linked lists 'for performance' on small records"],
    usage: ["Every language's default list", "Buffers", "Tables of records"],
    interview: [
      iq("Array vs linked list insert at head?", "Array: O(n) to shift. Linked list: O(1) pointer swing, if you already hold the head.", "beginner"),
      iq("Why amortized O(1) append?", "Geometric resizing: the occasional O(n) copy is paid for by Θ(n) cheap appends since the last copy.", "intermediate"),
    ],
    extra: [{ type: "viz", id: "algorithm-visualizer" }],
  }),
  T({
    slug: "consistent-hashing",
    section: "system-design",
    title: "Consistent Hashing",
    summary: "Place keys and nodes on a ring so that adding a node moves only a small fraction of keys.",
    level: "advanced",
    prereqs: ["hash-tables", "sharding"],
    related: ["sharding", "load-balancers"],
    next: "circuit-breakers",
    viz: "consistent-hashing",
    lab: "consistent-hashing",
    what: "Map both node identities and keys onto a circle with the same hash. A key belongs to the first node clockwise. When a node joins or leaves, only the keys in its arc move. Virtual nodes (many positions per physical node) smooth load.",
    why: "Caches (memcached), DHTs, and some partitioners cannot afford to reshuffle everything on a membership change. Consistent hashing is the standard answer.",
    mental:
      "A clock. Servers sit at minutes. A key hashes to a minute and walks forward until it hits a server. Add a server at 3:00, and only the keys between the previous server and 3:00 change home.",
    points: [
      "Ordinary modulo hashing reshuffles almost all keys when N changes.",
      "Virtual nodes fix hot spots and uneven hash ranges.",
      "Replication: walk clockwise for R distinct physical nodes.",
      "Need a membership view that is eventually agreed, or you will misroute.",
    ],
    mistakes: ["One position per fat node, then wondering why load is skewed", "Forgetting that a lookup still needs the current ring"],
    usage: ["Distributed caches", "Partitioners", "Some CDNs and DHTs"],
    interview: [
      iq("Why not hash % N?", "When N → N+1, the remainder changes for most keys, so most data moves. Consistent hashing moves ~1/N.", "intermediate"),
      iq("What are virtual nodes for?", "They split a physical node into many ring points so load is even and a departure does not dump a huge arc on one neighbor.", "advanced"),
    ],
    extra: [{ type: "viz", id: "consistent-hashing" }],
  }),
];
