import { iq, T } from "../helpers";
import type { Topic } from "../types";

export const FLAGSHIP: Topic[] = [
  T({
    slug: "memory",
    section: "fundamentals",
    title: "Memory",
    summary: "The addressable store a program reads and writes: code, data, stack, and heap.",
    level: "beginner",
    prereqs: ["loader"],
    related: ["stack", "heap", "pointers"],
    next: "pointers",
    viz: "memory-map",
    lab: "memory-map",
    what: "A process sees a virtual address space. Typical layout: read-only code (text), globals (data/BSS), a heap that grows toward high addresses, and a stack per thread that grows toward the heap. The CPU and OS cooperate via page tables so these addresses are not physical RAM.",
    why: "Every later topic — pointers, recursion, malloc, page faults — is a story about this map. If the map is fuzzy, those pages become slogans.",
    mental:
      "A long numbered street. Code lives in a fenced park. Globals have houses. The heap is new construction spreading up the street. The stack is a tower of sticky notes at the other end, one floor per active function.",
    points: [
      "Text: instructions. Usually executable, not writable (W^X).",
      "Data/BSS: globals and statics. Data is initialized; BSS is zeroed.",
      "Heap: malloc/new. Lifetime decided at run time. Fragmentation and GC live here.",
      "Stack: frames. Automatic variables, return addresses. Fast, limited, per thread.",
      "The gap in the middle is virtual: it costs address space, not RAM, until you touch it.",
    ],
    steps: [
      "A function is called: a frame is pushed (stack grows).",
      "It mallocs a buffer: the heap allocator finds a block (heap grows or reuses).",
      "The function returns: the frame is popped; the buffer is leaked unless freed/owned.",
    ],
    extra: [
      { type: "viz", id: "memory-map" },
      {
        type: "table",
        headers: ["Region", "Lifetime", "Usual bug"],
        rows: [
          ["Code", "Process", "Self-modifying / WX"],
          ["Data", "Process", "Uninitialized read (C)"],
          ["Heap", "Until free/GC", "UAF, leak, double-free"],
          ["Stack", "The frame", "Overflow, dangling pointer to local"],
        ],
      },
    ],
    mistakes: ["Calling 'the stack' the call stack and the data structure without noticing the pun", "Thinking the heap is in the kernel"],
    usage: ["Every process", "Debuggers (info proc mappings)", "Language runtimes"],
    interview: [
      iq("Stack vs heap?", "Stack: automatic, LIFO frames, fast, size-limited. Heap: dynamic lifetime, allocator, slower, flexible.", "beginner"),
      iq("Why can recursion blow the stack?", "Each call adds a frame. Deep or infinite recursion exhausts the mapped stack; the OS delivers SIGSEGV / StackOverflowError.", "intermediate"),
    ],
  }),
  T({
    slug: "dynamic-programming",
    section: "dsa",
    title: "Dynamic Programming",
    summary: "Optimal substructure plus overlapping subproblems: remember the answer instead of recomputing it.",
    level: "intermediate",
    prereqs: ["recursion-algo"],
    related: ["greedy", "shortest-paths"],
    next: "bfs",
    viz: "algorithm-visualizer",
    what: "DP solves a problem by combining solutions to smaller problems, caching each state so overlapping work is O(1) after the first time. Top-down is recursion + memo. Bottom-up is a table filled in dependency order.",
    why: "It is the interview topic people fear. The skill is not 'know knapsack'; it is 'name the state, the transition, and the base'.",
    mental:
      "A tree of recursive calls with the same nodes showing up again. DP is that tree collapsed into a DAG, then evaluated once per node.",
    points: [
      "State: the tuple that is enough to finish the rest of the problem.",
      "Transition: how a state is built from smaller ones.",
      "Base: states you know without a recursive call.",
      "Order: memoization ignores order; tabulation must respect the DAG.",
      "Space: sometimes only the last row is needed (knapsack rolling array).",
    ],
    code: {
      lang: "python",
      title: "0/1 knapsack (values, weights, capacity W)",
      code: `def knapsack(v, w, W):
    n = len(v)
    dp = [0] * (W + 1)
    for i in range(n):
        for cap in range(W, w[i] - 1, -1):
            dp[cap] = max(dp[cap], dp[cap - w[i]] + v[i])
    return dp[W]`,
    },
    complexity: {
      time: "O(number of states × work per state)",
      space: "O(states), sometimes compressible",
      tradeoffs: ["Polynomial if states are polynomial", "State design is the whole problem"],
    },
    mistakes: ["Memoizing a state that is missing a constraint (wrong answers)", "Confusing DP with 'I used an array'"],
    usage: ["Edit distance", "Scheduling", "Parsers (CYK)", "Resource allocation"],
    interview: [
      iq("When is DP legal?", "Optimal substructure (best of bests) and overlapping subproblems (the naive tree repeats nodes).", "intermediate"),
      iq("Memo vs table?", "Memo: recursive, fills only reachable states. Table: iterative, control over order and space.", "beginner"),
    ],
  }),
  T({
    slug: "raft",
    section: "distributed",
    title: "Raft",
    summary: "A consensus protocol designed to be explainable: leader, log, terms, and majority.",
    level: "advanced",
    prereqs: ["consensus"],
    related: ["paxos", "leader-election"],
    next: "paxos",
    viz: "distributed-simulator",
    lab: "distributed-simulator",
    what: "Raft elects a leader, then the leader appends log entries and commits them once a majority has stored them. Terms number the epochs so split votes and old leaders cannot commit. A follower’s log is forced to match the leader’s by construction.",
    why: "etcd, Consul, and many databases’ control planes run Raft. It is the consensus protocol you are most likely to operate — and to be asked to draw.",
    mental:
      "A class elects a captain (majority vote). The captain writes in a numbered notebook. A rule is law when a majority has copied that line. A new captain must have the most up-to-date notebook among the majority that elects them.",
    points: [
      "Leader election: randomized timeouts, RequestVote, majority, term bump.",
      "Log replication: AppendEntries with prevLogIndex/term. Inconsistent tails are overwritten.",
      "Commit: leader commits when a majority has the entry in the current term.",
      "Safety: a leader in term T cannot commit a previous-term entry until a current-term entry is committed (the figure 8 issue).",
      "Membership changes are a special case (joint consensus) — mention, don’t invent.",
    ],
    extra: [{ type: "viz", id: "distributed-simulator" }],
    mistakes: ["Committing on the leader’s disk alone", "Assuming the leader is unique during a partition (two leaders in different terms, only one can get a majority)"],
    usage: ["etcd", "Cockroach/TiKV control", "Kafka KRaft"],
    interview: [
      iq("When is an entry committed?", "When the leader knows a majority of the current configuration has stored it, and the safety rule for the current term is satisfied.", "advanced"),
      iq("Why random election timeouts?", "To make split votes unlikely: one candidate times out first and wins before others start.", "intermediate"),
    ],
  }),
  T({
    slug: "virtual-memory",
    section: "os",
    title: "Virtual Memory",
    summary: "Each process sees its own address space, backed by RAM and disk as needed.",
    level: "intermediate",
    prereqs: ["paging"],
    related: ["page-tables", "page-replacement"],
    next: "page-tables",
    viz: "paging-simulator",
    lab: "paging-simulator",
    what: "Virtual memory is the illusion that every process owns a large, private, contiguous address space. The hardware translates VA → PA through page tables and a TLB. The OS fills the illusion: demand paging, copy-on-write, file-backed maps, swap.",
    why: "Isolation, convenient linking (every process can start at the same VA), and overcommit. It is also why 'out of memory' and 'page fault' are different sentences.",
    mental: "A library card catalog. Your card names a shelf that might be in the reading room (RAM) or in off-site storage (disk). The clerk (page fault handler) fetches as needed.",
    points: [
      "Translation is the always-on part. Swap is optional.",
      "Demand paging: a freshly mmap'd file is not all in RAM.",
      "COW fork: parent and child share frames marked read-only; a write faults and copies.",
      "The working set must fit or you thrash.",
    ],
    extra: [{ type: "viz", id: "paging-simulator" }],
    mistakes: ["Equating virtual memory with swap", "Thinking a page fault is always a bug"],
    usage: ["Every user process", "mmap", "Shared libraries"],
    interview: [
      iq("Is swap required for virtual memory?", "No. Translation and isolation work without swap. Swap is a way to overcommit RAM.", "intermediate"),
      iq("What is copy-on-write fork?", "Parent and child share physical pages marked read-only. A write triggers a fault; the OS copies the page and resumes.", "intermediate"),
    ],
  }),
  T({
    slug: "indexes",
    section: "dbms",
    title: "Indexes",
    summary: "Auxiliary structures (usually B+ trees) that make predicates cheap at the cost of writes and space.",
    level: "intermediate",
    prereqs: ["sql", "bplus-trees"],
    related: ["query-optimization", "b-trees"],
    next: "views",
    viz: "bplus-tree",
    lab: "bplus-tree",
    what: "An index is a data structure maintained with a table so a predicate (equality, range) can find rows without a full scan. Clustered indexes are the table; secondary indexes point at keys or row ids. Hash indexes help equality, not ranges.",
    why: "The difference between 10 ms and 10 s. Also the difference between a fast write and a slow one: every index is extra work on INSERT/UPDATE/DELETE.",
    mental: "The card catalog, not the shelves. You still have to maintain both when a book moves.",
    points: [
      "B+ tree: ranges and ordered scans. The default.",
      "Selectivity: an index on 'gender' is often useless; an index on 'email' is not.",
      "Covering: if the index has every column you need, you never touch the heap.",
      "Write amplification: each extra index is another structure to update.",
    ],
    extra: [{ type: "viz", id: "bplus-tree" }],
    mistakes: ["Indexing every column", "Prefix wildcards (LIKE '%foo') that cannot use a B-tree", "Forgetting composite index column order"],
    usage: ["OLTP lookups", "Joins (nested loop + index)", "Unique constraints"],
    interview: [
      iq("Why does an index slow writes?", "Each insert/update/delete must maintain the index structure (splits, leaf writes) in the same transaction.", "beginner"),
      iq("Leftmost prefix rule?", "A composite index (a,b,c) supports predicates on a, a+b, a+b+c — not b alone.", "intermediate"),
    ],
  }),
  T({
    slug: "consistent-hashing",
    section: "system-design",
    title: "Consistent Hashing",
    summary: "A ring so that adding a node moves only a 1/n fraction of keys — plus virtual nodes.",
    level: "advanced",
    prereqs: ["hash-tables", "sharding"],
    related: ["sharding"],
    next: "circuit-breakers",
    viz: "consistent-hashing",
    lab: "consistent-hashing",
    what: "Map both keys and nodes onto a circle (hash modulo a large space). A key belongs to the first node clockwise. When a node joins or leaves, only its neighbors’ keys move — unlike hash(key) % N, which reshuffles everything.",
    why: "Caches (memcached), Dynamo-style stores, and load balancing with sticky backends. Virtual nodes (many positions per server) keep load even.",
    mental: "A clock. Servers sit at minutes. A key lands on a second and walks forward until it hits a server. Add a server: it only steals the arc behind it.",
    points: [
      "hash(key) % N is not consistent: N→N+1 moves almost all keys.",
      "Virtual nodes: each physical server owns many points, so one departure does not dump a giant arc on one neighbor.",
      "Replication: walk clockwise for the next N-1 distinct owners (the preference list).",
    ],
    extra: [{ type: "viz", id: "consistent-hashing" }],
    mistakes: ["No virtual nodes, then one fat server", "Forgetting that hash collisions of nodes need a tie-break"],
    usage: ["Distributed caches", "Partitioned streams", "Some L7 load balancers"],
    interview: [
      iq("What problem does it solve vs modulo N?", "Minimizing key movement when the node set changes. Only O(K/N) keys move when a node is added.", "intermediate"),
      iq("Why virtual nodes?", "Smooth load. A real server occupies many ring points so capacity and failure are even.", "intermediate"),
    ],
  }),
  T({
    slug: "round-robin",
    section: "os",
    title: "Round Robin",
    summary: "Time slices in a cycle. The quantum is the whole design.",
    level: "beginner",
    prereqs: ["cpu-scheduling", "queue"],
    related: ["fcfs", "priority-scheduling"],
    next: "priority-scheduling",
    viz: "cpu-scheduler",
    lab: "cpu-scheduler",
    what: "Ready threads sit in a FIFO. Each runs for at most one quantum, then is preempted to the tail. Fair in the sense of equal CPU over a long window; response time depends on n × quantum.",
    why: "It is the first preemptive scheduler people implement, and the quantum question is a real engineering knob (too small: context-switch tax; too large: FCFS in disguise).",
    mental: "A talking stick with a kitchen timer.",
    points: [
      "Quantum q. n runnable threads → a thread waits about (n-1)q between slices.",
      "I/O-bound threads often yield before q; they look snappy.",
      "CPU-bound threads are sliced; they need other policies (priority, CFS vruntime) for fairness in work, not just time.",
    ],
    extra: [{ type: "viz", id: "cpu-scheduler" }],
    mistakes: ["q = 1ms on a machine whose switch costs 0.3ms", "Calling RR 'optimal' — it is not SJF"],
    usage: ["Time-sharing Unix", "Interview Gantt charts", "Cooperative thread pools with a time slice"],
    interview: [
      iq("Effect of a tiny quantum?", "Response time looks good until context-switch overhead dominates utilization.", "beginner"),
      iq("RR vs FCFS?", "RR is preemptive FCFS with a cap. Long jobs cannot convoy the CPU for their whole burst.", "beginner"),
    ],
  }),
  T({
    slug: "mutex",
    section: "os",
    title: "Mutex",
    summary: "Mutual exclusion: at most one holder. The lock you actually want most of the time.",
    level: "intermediate",
    prereqs: ["critical-sections"],
    related: ["semaphore", "deadlocks"],
    next: "semaphore",
    what: "A mutex is a lock with ownership: acquire, enter the critical section, release. Only the owner should unlock. Implementations: TAS/CAS spinlocks (short), futexes (spin then sleep), adaptive mutexes.",
    why: "Race conditions are 'you needed a mutex' (or a lock-free protocol you can prove). Deadlocks are 'you needed an order on mutexes'.",
    mental: "A bathroom key. One holder. Don't copy the key (unlock from the other thread). Don't wait in the bathroom for a second key (lock order).",
    points: [
      "Protect data, not code. The invariant lives on the data.",
      "Hold time is the scalability limit. Do not I/O under a lock.",
      "Lock ordering prevents deadlock. Document the order.",
      "Try-lock and timed lock exist; they are not a substitute for a design.",
    ],
    code: {
      lang: "c",
      title: "The shape, not the API",
      code: `lock(&m);
account->balance -= 10;  /* invariant: balance consistent */
unlock(&m);`,
    },
    mistakes: ["Locking too coarse (one big mutex) or too fine (deadlock soup)", "Forgetting the data is still racy if you read it without the lock 'because I only read'"],
    usage: ["pthreads", "synchronized", "std::mutex"],
    interview: [
      iq("Mutex vs semaphore?", "A mutex has ownership and is binary. A semaphore is a counter: it can permit N and is often used for signaling, not just exclusion.", "intermediate"),
      iq("Why not spin forever?", "A busy-wait burns a core. Spin briefly if the critical section is tiny and the holder is on another core; then sleep (futex).", "advanced"),
    ],
  }),
  T({
    slug: "solid",
    section: "oop",
    title: "SOLID",
    summary: "Five design heuristics: SRP, OCP, LSP, ISP, DIP. Tools, not commandments.",
    level: "intermediate",
    prereqs: ["interfaces", "coupling"],
    related: ["factory", "strategy"],
    next: "factory",
    what: "Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion. They are ways to keep change local: one reason to change, extend without editing, subtypes that do not lie, small interfaces, depend on abstractions you own.",
    why: "Interviewers use SOLID as a vocabulary test. Production uses it as a smell check, not a scoring rubric.",
    mental: "Change should arrive like a new plugin, not a rewrite of a God class. If a new requirement edits ten files, a SOLID alarm is reasonable — and sometimes still the right call.",
    points: [
      "SRP: a module has one audience / one reason to change. Not 'one method'.",
      "OCP: new behavior via new types (strategy, decorator), not a growing switch — until a switch is clearer.",
      "LSP: a subtype must honor the parent’s contract. Square/rectangle is the cautionary tale.",
      "ISP: do not force clients to depend on methods they never call.",
      "DIP: high-level policy should not import low-level details; both depend on an interface.",
    ],
    mistakes: ["Interface-per-class cargo cult", "Pretending OCP means never editing files (you will)"],
    usage: ["Service boundaries", "Test seams", "Plugin architectures"],
    interview: [
      iq("State SOLID without buzzword soup.", "One reason to change; add types instead of editing; subtypes keep promises; small interfaces; depend on abstractions.", "intermediate"),
      iq("Give an LSP violation.", "A Square that inherits Rectangle and breaks area when setWidth is called independently of setHeight.", "intermediate"),
    ],
  }),
  T({
    slug: "attention",
    section: "deep-learning",
    title: "Attention",
    summary: "A weighted sum of values, with weights from a query-key match. The primitive of transformers.",
    level: "intermediate",
    prereqs: ["neural-networks"],
    related: ["transformers"],
    next: "transformers",
    viz: "neural-net",
    lab: "neural-net",
    what: "Attention computes, for a query vector q, a distribution over keys k_i (usually softmax of scaled dots), then returns the corresponding mixture of values v_i. Self-attention uses Q, K, V from the same sequence. Multi-head does this in parallel subspaces.",
    why: "It replaced recurrence as the default sequence mixer. Understanding the n² cost and the residual+norm wrapper is the job.",
    mental: "A query asks a room of keys how relevant they are, then takes a weighted average of their values. Heads are several rooms with different notions of relevance.",
    points: [
      "scores = QKᵀ / √d ; weights = softmax(scores); out = weights V.",
      "Causal mask: set future scores to −∞ so a token cannot see the future (decoders).",
      "n² in sequence length for dense attention. KV cache makes inference pay n, not n², per new token — still linear in n for memory.",
    ],
    extra: [
      { type: "flow", steps: ["Q, K, V projections", "Dots QKᵀ", "Softmax (+ mask)", "Mix V", "Output projection"] },
      { type: "viz", id: "neural-net" },
    ],
    mistakes: ["Calling attention 'the model understands'", "Forgetting the scale √d (softmax saturates)"],
    usage: ["Transformers", "Cross-attention in encoder-decoder", "Memory-retrieval hybrids"],
    interview: [
      iq("Write attention in four symbols.", "softmax(QKᵀ / √d) V", "intermediate"),
      iq("Why √d?", "Dot products of d-dimensional unit-ish vectors grow like √d; without scaling, softmax becomes peaky and gradients die.", "advanced"),
    ],
  }),
];
