import type { Lab } from "./types";

export const LABS: Lab[] = [
  {
    id: "osi-explorer",
    title: "OSI Model Explorer",
    blurb: "Click a layer, inspect PDUs, and watch encapsulation travel down the stack.",
    section: "networks",
    topics: ["osi-model", "tcp-ip-model"],
    controls: ["Select layer", "Play encapsulation", "Step", "Reset"],
  },
  {
    id: "tcp-simulator",
    title: "TCP Handshake Simulator",
    blurb: "SYN, SYN-ACK, ACK — then teardown. Inspect sequence and acknowledgment numbers.",
    section: "networks",
    topics: ["tcp", "tcp-handshake", "tcp-teardown"],
    controls: ["Play", "Pause", "Step", "Reset", "Speed"],
  },
  {
    id: "dns-simulator",
    title: "DNS Resolution Simulator",
    blurb: "Follow a name from stub resolver to root, TLD, and authoritative nameserver.",
    section: "networks",
    topics: ["dns"],
    controls: ["Play", "Step", "Reset", "Inspect"],
  },
  {
    id: "http-simulator",
    title: "HTTP Request Simulator",
    blurb: "A page load from URL bar through DNS, TCP, TLS, request, and response.",
    section: "web",
    topics: ["http", "https", "dns"],
    controls: ["Play", "Step", "Reset"],
  },
  {
    id: "routing-simulator",
    title: "Packet Routing Simulator",
    blurb: "Forward a packet across a small internet using longest-prefix matching.",
    section: "networks",
    topics: ["routing", "ip", "router"],
    controls: ["Play", "Step", "Reset", "Pick destination"],
  },
  {
    id: "algorithm-visualizer",
    title: "Algorithm Visualizer",
    blurb: "Sorting, searching, and array patterns with play / step / speed controls.",
    section: "dsa",
    topics: ["sorting", "binary-search", "two-pointers"],
    controls: ["Play", "Pause", "Step", "Reset", "Speed", "Algorithm"],
  },
  {
    id: "bst-explorer",
    title: "BST Explorer",
    blurb: "Insert, delete, and traverse a binary search tree. Watch rotations on AVL.",
    section: "dsa",
    topics: ["bst", "avl-trees", "binary-trees"],
    controls: ["Insert", "Delete", "Traverse", "Reset"],
  },
  {
    id: "graph-search",
    title: "BFS / DFS Simulator",
    blurb: "Walk a graph layer-by-layer or down a path. Queue and stack are visible.",
    section: "dsa",
    topics: ["bfs", "dfs", "graphs"],
    controls: ["Play", "Step", "Reset", "Mode"],
  },
  {
    id: "dijkstra",
    title: "Dijkstra Simulator",
    blurb: "Relax edges, watch the frontier, and reconstruct the shortest path.",
    section: "dsa",
    topics: ["dijkstra", "graphs"],
    controls: ["Play", "Step", "Reset", "Source"],
  },
  {
    id: "hash-collisions",
    title: "Hash Collision Lab",
    blurb: "Drop keys into buckets with chaining or open addressing and watch clustering.",
    section: "dsa",
    topics: ["hash-tables"],
    controls: ["Insert", "Mode", "Reset"],
  },
  {
    id: "cpu-scheduler",
    title: "CPU Scheduler",
    blurb: "FCFS, SJF, Round Robin, and priority — Gantt chart, waiting time, turnaround.",
    section: "os",
    topics: ["cpu-scheduling", "fcfs", "sjf", "round-robin"],
    controls: ["Play", "Step", "Reset", "Quantum", "Algorithm"],
  },
  {
    id: "process-states",
    title: "Process State Machine",
    blurb: "New, ready, running, waiting, terminated — and what causes each transition.",
    section: "os",
    topics: ["process-states", "processes"],
    controls: ["Step", "Reset", "Event"],
  },
  {
    id: "paging-simulator",
    title: "Paging Simulator",
    blurb: "Virtual pages, frames, a page table, and TLB hits versus faults.",
    section: "os",
    topics: ["paging", "virtual-memory", "tlb"],
    controls: ["Access address", "Step", "Reset"],
  },
  {
    id: "page-replacement",
    title: "Page Replacement",
    blurb: "FIFO, LRU, and optimal replacement on a reference string.",
    section: "os",
    topics: ["page-replacement", "lru", "fifo-replacement"],
    controls: ["Play", "Step", "Reset", "Algorithm", "Frames"],
  },
  {
    id: "deadlock-simulator",
    title: "Deadlock & Banker's Algorithm",
    blurb: "Allocate, wait, and test whether a state is safe.",
    section: "os",
    topics: ["deadlocks", "bankers-algorithm"],
    controls: ["Request", "Step", "Reset"],
  },
  {
    id: "cpu-pipeline",
    title: "CPU Pipeline",
    blurb: "Fetch, decode, execute, memory, write-back — with a stall you can inspect.",
    section: "architecture",
    topics: ["cpu-pipeline", "cpu"],
    controls: ["Play", "Step", "Reset", "Speed"],
  },
  {
    id: "sql-playground",
    title: "SQL Playground",
    blurb: "Run SELECT / WHERE / JOIN / GROUP BY against a tiny in-memory database.",
    section: "dbms",
    topics: ["sql", "joins", "aggregation"],
    controls: ["Run", "Reset", "Sample queries"],
  },
  {
    id: "bplus-tree",
    title: "B+ Tree Explorer",
    blurb: "Insert keys and watch splits propagate in a database-style index.",
    section: "dbms",
    topics: ["bplus-trees", "indexes"],
    controls: ["Insert", "Reset", "Order"],
  },
  {
    id: "transaction-simulator",
    title: "Transaction Isolation",
    blurb: "Two transactions, dirty reads, and how isolation levels change the outcome.",
    section: "dbms",
    topics: ["transactions", "isolation-levels", "acid"],
    controls: ["Step", "Reset", "Isolation"],
  },
  {
    id: "cache-simulator",
    title: "Cache Simulator",
    blurb: "Direct-mapped and set-associative caches with hit/miss coloring.",
    section: "architecture",
    topics: ["cache", "memory-hierarchy"],
    controls: ["Access", "Reset", "Associativity"],
  },
  {
    id: "load-balancer",
    title: "Load Balancer",
    blurb: "Round-robin, least-connections, and a backend going unhealthy.",
    section: "system-design",
    topics: ["load-balancers"],
    controls: ["Send request", "Kill backend", "Reset"],
  },
  {
    id: "consistent-hashing",
    title: "Consistent Hashing",
    blurb: "Place nodes on a ring, add a server, and see how few keys move.",
    section: "system-design",
    topics: ["consistent-hashing", "sharding"],
    controls: ["Add node", "Remove node", "Place key"],
  },
  {
    id: "distributed-simulator",
    title: "Leader Election",
    blurb: "Three servers, a crash, and a new leader. Traffic follows the lease.",
    section: "distributed",
    topics: ["leader-election", "raft", "fault-tolerance"],
    controls: ["Play", "Crash", "Reset"],
  },
  {
    id: "compiler-explorer",
    title: "Compiler Explorer",
    blurb: "Type a tiny program and inspect tokens, AST, and a simple IR.",
    section: "compilers",
    topics: ["lexer", "parser", "ast"],
    controls: ["Compile", "Reset"],
  },
  {
    id: "dfa-simulator",
    title: "DFA / NFA Simulator",
    blurb: "Feed a string to an automaton and watch the active state set.",
    section: "theory",
    topics: ["dfa", "nfa", "regular-languages"],
    controls: ["Step", "Reset", "Machine"],
  },
  {
    id: "neural-net",
    title: "Neural Network Lab",
    blurb: "Forward pass, loss, and a backprop step on a tiny network you can inspect.",
    section: "deep-learning",
    topics: ["neural-networks", "backpropagation"],
    controls: ["Forward", "Backward", "Reset"],
  },
  {
    id: "linux-terminal",
    title: "Linux Terminal",
    blurb: "A safe filesystem and a handful of real commands. No network, no escape.",
    section: "linux",
    topics: ["shell", "linux-filesystem", "pipes"],
    controls: ["Type commands"],
  },
  {
    id: "stack-queue",
    title: "Stack & Queue",
    blurb: "Push, pop, enqueue, dequeue — LIFO versus FIFO as live memory.",
    section: "dsa",
    topics: ["stack-ds", "queue"],
    controls: ["Push", "Pop", "Enqueue", "Dequeue", "Reset"],
  },
  {
    id: "memory-map",
    title: "Memory Map",
    blurb: "Stack frames, heap objects, code and data — call, return, malloc, free.",
    section: "fundamentals",
    topics: ["memory", "stack", "heap"],
    controls: ["Call", "Return", "malloc", "free", "Reset"],
  },
];

export const LAB_BY_ID = Object.fromEntries(LABS.map((l) => [l.id, l]));
