import type { Level, SectionId } from "./types";

export type NavTopic = {
  slug: string;
  section: SectionId;
  title: string;
  summary: string;
  level: Level;
  prereqs: string[];
  related: string[];
  next?: string;
  viz?: string;
  lab?: string;
};

type Row = [
  slug: string,
  section: SectionId,
  title: string,
  summary: string,
  level: Level,
  prereqs: string[],
  related: string[],
  next?: string,
  viz?: string,
];

const ROWS: Row[] = [
  // —— Fundamentals
  ["what-is-programming", "fundamentals", "What is Programming?", "Giving a machine an unambiguous sequence of instructions it can execute.", "beginner", [], ["source-code", "compiler"], "source-code"],
  ["source-code", "fundamentals", "Source Code", "Human-written text that a compiler or interpreter turns into behavior.", "beginner", ["what-is-programming"], ["compiler", "interpreter"], "compiler"],
  ["compiler", "fundamentals", "Compiler", "A program that translates source into a lower-level form, usually ahead of time.", "beginner", ["source-code"], ["interpreter", "linker", "compiler-design"], "interpreter", "compiler-explorer"],
  ["interpreter", "fundamentals", "Interpreter", "A program that executes source (or bytecode) directly, without a separate machine-code binary.", "beginner", ["source-code"], ["compiler", "runtime"], "linker"],
  ["linker", "fundamentals", "Linker", "The tool that combines object files and libraries into a single executable image.", "intermediate", ["compiler"], ["loader", "libraries"], "loader"],
  ["loader", "fundamentals", "Loader", "The OS component that maps an executable into memory and starts it.", "intermediate", ["linker"], ["runtime", "memory"], "runtime"],
  ["runtime", "fundamentals", "Runtime", "The support system a program needs while it runs: memory, threads, I/O, and language services.", "intermediate", ["loader"], ["stack", "heap", "garbage-collection"], "variables"],
  ["variables", "fundamentals", "Variables", "Named storage for values. A variable binds a name to a location and a type.", "beginner", ["what-is-programming"], ["data-types", "scope"], "data-types"],
  ["data-types", "fundamentals", "Data Types", "The set of values a variable can hold and the operations that are legal on them.", "beginner", ["variables"], ["operators", "memory"], "operators"],
  ["operators", "fundamentals", "Operators", "Built-in operations: arithmetic, comparison, logic, bitwise, and assignment.", "beginner", ["data-types"], ["conditions"], "conditions"],
  ["conditions", "fundamentals", "Conditions", "Control flow that chooses a path from a boolean expression.", "beginner", ["operators"], ["loops"], "loops"],
  ["loops", "fundamentals", "Loops", "Control flow that repeats a block while a condition holds, or over a collection.", "beginner", ["conditions"], ["functions", "recursion"], "functions"],
  ["functions", "fundamentals", "Functions", "Named, reusable units of computation with parameters, a body, and a return.", "beginner", ["variables"], ["scope", "recursion", "stack"], "recursion"],
  ["recursion", "fundamentals", "Recursion", "A function that solves a problem by calling itself on a smaller instance, with a base case.", "intermediate", ["functions", "stack"], ["recursion-algo", "stack"], "scope"],
  ["scope", "fundamentals", "Scope", "The region of a program where a name is visible. Nested scopes shadow outer ones.", "beginner", ["functions", "variables"], ["stack"], "stack"],
  ["stack", "fundamentals", "Call Stack", "The region that stores frames for active function calls: locals, return address, saved registers.", "intermediate", ["functions", "scope"], ["heap", "memory"], "heap", "stack-queue"],
  ["heap", "fundamentals", "Heap", "The region for dynamically allocated objects whose lifetime is not tied to a single frame.", "intermediate", ["memory"], ["stack", "dynamic-memory", "garbage-collection"], "memory", "memory-map"],
  ["memory", "fundamentals", "Memory", "The addressable store a program reads and writes: code, data, stack, and heap.", "beginner", ["loader"], ["stack", "heap", "pointers"], "pointers", "memory-map"],
  ["pointers", "fundamentals", "Pointers", "Values that hold addresses. They make aliasing, data structures, and manual memory possible.", "intermediate", ["memory"], ["references", "dynamic-memory"], "references"],
  ["references", "fundamentals", "References", "Names that alias an existing object without exposing arithmetic on its address.", "beginner", ["pointers"], ["pointers"], "dynamic-memory"],
  ["dynamic-memory", "fundamentals", "Dynamic Memory", "Allocation whose size or lifetime is decided at run time, not at compile time.", "intermediate", ["heap", "pointers"], ["garbage-collection"], "garbage-collection"],
  ["garbage-collection", "fundamentals", "Garbage Collection", "Automatic reclamation of heap objects the program can no longer reach.", "intermediate", ["heap", "dynamic-memory"], ["runtime"], "error-handling"],
  ["error-handling", "fundamentals", "Error Handling", "How a program detects, reports, and recovers from failures without corrupting state.", "beginner", ["functions"], ["exceptions"], "exceptions"],
  ["exceptions", "fundamentals", "Exceptions", "A non-local control-flow mechanism that unwinds the stack until a handler matches.", "intermediate", ["error-handling", "stack"], ["error-handling"], "debugging"],
  ["debugging", "fundamentals", "Debugging", "The discipline of forming a hypothesis about a defect and testing it against the running program.", "beginner", ["error-handling"], ["exceptions"], "file-io"],
  ["file-io", "fundamentals", "File I/O", "Reading and writing byte streams that outlive the process: files, pipes, sockets.", "beginner", ["runtime"], ["modules"], "modules"],
  ["modules", "fundamentals", "Modules", "Compilation or namespace units that hide internals and export a small interface.", "beginner", ["functions"], ["packages", "libraries"], "packages"],
  ["packages", "fundamentals", "Packages", "Versioned bundles of modules, with metadata for installation and dependency resolution.", "beginner", ["modules"], ["libraries"], "libraries"],
  ["libraries", "fundamentals", "Libraries", "Reusable code meant to be linked or imported, not run as a program on its own.", "beginner", ["packages", "linker"], ["apis"], "apis"],
  ["apis", "fundamentals", "APIs", "The contract a component publishes: types, functions, errors, and the rules for using them.", "beginner", ["libraries", "modules"], ["rest", "apis-web"], "c"],

  // —— Languages
  ["c", "languages", "C", "A small systems language with manual memory, undefined behavior, and a stable ABI.", "intermediate", ["pointers", "compiler"], ["cpp", "memory"], "cpp"],
  ["cpp", "languages", "C++", "C’s model plus abstractions: RAII, templates, and zero-cost as a design goal.", "intermediate", ["c"], ["rust", "oop"], "java"],
  ["java", "languages", "Java", "A managed, class-based language with a VM, a huge standard library, and structured concurrency evolving in.", "beginner", ["oop", "garbage-collection"], ["kotlin", "jvm"], "python"],
  ["python", "languages", "Python", "A dynamic language whose object model, iterators, and C-API shape almost every data stack.", "beginner", ["what-is-programming"], ["javascript", "modules"], "javascript"],
  ["javascript", "languages", "JavaScript", "The language of the web: prototypes, the event loop, and a single-threaded concurrency story.", "beginner", ["what-is-programming"], ["typescript", "event-loop"], "typescript"],
  ["typescript", "languages", "TypeScript", "A gradual type system erased at compile time, sitting on top of JavaScript.", "beginner", ["javascript"], ["javascript"], "go"],
  ["go", "languages", "Go", "A small language with goroutines, channels, and a runtime aimed at networked services.", "intermediate", ["functions"], ["rust", "concurrency"], "rust"],
  ["rust", "languages", "Rust", "Ownership, borrowing, and a type system that makes aliasing and mutation exclusive.", "advanced", ["pointers", "memory"], ["cpp", "go"], "kotlin"],
  ["kotlin", "languages", "Kotlin", "A JVM (and beyond) language with null-safety, coroutines, and Java interop as a first-class goal.", "intermediate", ["java"], ["java", "android"], "swift"],
  ["swift", "languages", "Swift", "Apple’s language: value types, optionals, ARC, and protocol-oriented design.", "intermediate", ["oop"], ["kotlin", "ios"], "sql-language"],
  ["sql-language", "languages", "SQL (Language)", "A declarative language for describing the result you want from a relational store.", "beginner", ["relational-databases"], ["sql", "joins"], "bash"],
  ["bash", "languages", "Bash", "The default Unix shell language: pipelines, redirection, and the glue of every server.", "beginner", ["linux-fundamentals"], ["shell", "pipes"], "arrays"],

  // —— DSA structures
  ["arrays", "dsa", "Arrays", "A contiguous sequence of elements addressable in O(1) by index.", "beginner", ["memory"], ["strings-ds", "linked-lists"], "strings-ds", "algorithm-visualizer"],
  ["strings-ds", "dsa", "Strings", "Sequences of characters. Encoding, immutability, and matching dominate their cost.", "beginner", ["arrays"], ["string-algorithms"], "linked-lists"],
  ["linked-lists", "dsa", "Linked Lists", "Nodes linked by pointers. O(1) insert at a known node, O(n) access by index.", "beginner", ["pointers"], ["doubly-linked-lists", "stack-ds"], "doubly-linked-lists", "stack-queue"],
  ["doubly-linked-lists", "dsa", "Doubly Linked Lists", "Each node points both ways, so deletion and reverse traversal do not need a predecessor walk.", "beginner", ["linked-lists"], ["circular-linked-lists"], "circular-linked-lists"],
  ["circular-linked-lists", "dsa", "Circular Linked Lists", "The last node points at the first. Useful for round-robin structures and buffers.", "intermediate", ["linked-lists"], ["queue"], "stack-ds"],
  ["stack-ds", "dsa", "Stack", "Last-in, first-out. Recursion, undo, and parsing are stacks in disguise.", "beginner", ["arrays"], ["queue", "stack"], "queue", "stack-queue"],
  ["queue", "dsa", "Queue", "First-in, first-out. BFS, printers, and thread pools are queues.", "beginner", ["arrays"], ["deque", "bfs"], "deque", "stack-queue"],
  ["deque", "dsa", "Deque", "A double-ended queue: push and pop at both ends in O(1).", "beginner", ["queue"], ["queue", "stack-ds"], "hash-tables"],
  ["hash-tables", "dsa", "Hash Tables", "Average O(1) insert/lookup via a hash function and a collision strategy.", "intermediate", ["arrays"], ["hash-maps", "sets"], "hash-maps", "hash-collisions"],
  ["hash-maps", "dsa", "Hash Maps", "A hash table used as an associative array from keys to values.", "beginner", ["hash-tables"], ["sets"], "sets"],
  ["sets", "dsa", "Sets", "Collections that answer membership. Hash sets and tree sets make different promises.", "beginner", ["hash-tables"], ["hash-maps"], "trees"],
  ["trees", "dsa", "Trees", "Connected acyclic graphs with a root. Hierarchical data lives here.", "beginner", ["linked-lists"], ["binary-trees", "graphs"], "binary-trees"],
  ["binary-trees", "dsa", "Binary Trees", "Each node has at most two children. Traversals and shape govern everything else.", "beginner", ["trees"], ["bst", "heaps"], "bst", "bst-explorer"],
  ["bst", "dsa", "Binary Search Trees", "Left < node < right. Ordered operations in O(h), which is O(log n) if balanced.", "intermediate", ["binary-trees"], ["avl-trees", "red-black-trees"], "avl-trees", "bst-explorer"],
  ["avl-trees", "dsa", "AVL Trees", "BSTs that rebalance on insert/delete so height stays within 1 of a sibling.", "advanced", ["bst"], ["red-black-trees"], "red-black-trees", "bst-explorer"],
  ["red-black-trees", "dsa", "Red-Black Trees", "A weaker balance invariant than AVL, with cheaper updates — the usual map/set backbone.", "advanced", ["bst"], ["avl-trees"], "heaps"],
  ["heaps", "dsa", "Heaps", "Almost-complete binary trees that keep the min or max at the root in O(1).", "intermediate", ["binary-trees", "arrays"], ["priority-queues"], "priority-queues"],
  ["priority-queues", "dsa", "Priority Queues", "Extract-min (or max) in O(log n). Dijkstra, schedulers, and A* depend on them.", "intermediate", ["heaps"], ["dijkstra", "cpu-scheduling"], "tries"],
  ["tries", "dsa", "Tries", "Trees indexed by characters (or bits). Prefix queries and dictionaries live here.", "intermediate", ["trees", "strings-ds"], ["string-algorithms"], "segment-trees"],
  ["segment-trees", "dsa", "Segment Trees", "A tree over ranges that answers range queries and updates in O(log n).", "advanced", ["trees", "arrays"], ["fenwick-trees"], "fenwick-trees"],
  ["fenwick-trees", "dsa", "Fenwick Trees", "A compact prefix-sum tree: range sums and point updates in O(log n).", "advanced", ["arrays", "prefix-sum"], ["segment-trees"], "graphs"],
  ["graphs", "dsa", "Graphs", "Vertices and edges. The universal model for networks, dependencies, and state spaces.", "intermediate", ["trees"], ["bfs", "dfs", "dijkstra"], "dsu", "graph-search"],
  ["dsu", "dsa", "Disjoint Set Union", "Near-O(1) union and find — the backbone of Kruskal and connected components.", "intermediate", ["graphs"], ["kruskal"], "asymptotic-notation"],

  // —— DSA algorithms
  ["asymptotic-notation", "dsa", "Big-O, Theta, Omega", "How runtime and memory grow: upper, tight, and lower bounds as n → ∞.", "beginner", ["functions"], ["sorting", "searching"], "searching"],
  ["searching", "dsa", "Searching", "Finding a value in a collection: linear, binary, and hash-based membership.", "beginner", ["arrays", "asymptotic-notation"], ["binary-search"], "sorting"],
  ["sorting", "dsa", "Sorting", "Putting elements in order. Stability, adaptivity, and n log n lower bounds matter.", "beginner", ["arrays", "asymptotic-notation"], ["binary-search", "divide-conquer"], "binary-search", "algorithm-visualizer"],
  ["binary-search", "dsa", "Binary Search", "Halve a monotonic search space until the answer remains. The idea is bigger than arrays.", "beginner", ["arrays", "searching"], ["two-pointers"], "two-pointers", "algorithm-visualizer"],
  ["two-pointers", "dsa", "Two Pointers", "Two indices walking a sequence to find pairs, partitions, or a window in linear time.", "intermediate", ["arrays"], ["sliding-window"], "sliding-window"],
  ["sliding-window", "dsa", "Sliding Window", "A subarray that grows and shrinks to maintain a constraint while scanning once.", "intermediate", ["two-pointers"], ["prefix-sum"], "prefix-sum"],
  ["prefix-sum", "dsa", "Prefix Sum", "Precomputed partial sums so any range sum is two lookups.", "beginner", ["arrays"], ["fenwick-trees"], "recursion-algo"],
  ["recursion-algo", "dsa", "Recursion (Algorithms)", "The algorithmic use of recursion: divide, conquer, and the call-tree cost.", "intermediate", ["recursion"], ["backtracking", "divide-conquer"], "backtracking"],
  ["backtracking", "dsa", "Backtracking", "Build a solution incrementally and undo when a partial assignment cannot work.", "intermediate", ["recursion-algo"], ["dynamic-programming"], "divide-conquer"],
  ["divide-conquer", "dsa", "Divide & Conquer", "Split, solve subproblems independently, combine. Recurrences describe the cost.", "intermediate", ["recursion-algo"], ["sorting", "dynamic-programming"], "greedy"],
  ["greedy", "dsa", "Greedy", "Commit to a locally optimal choice. Correct only when an exchange argument says so.", "intermediate", ["asymptotic-notation"], ["dynamic-programming", "kruskal"], "dynamic-programming"],
  ["dynamic-programming", "dsa", "Dynamic Programming", "Optimal substructure plus overlapping subproblems: remember the answer instead of recomputing it.", "intermediate", ["recursion-algo"], ["greedy", "dijkstra"], "bfs"],
  ["bfs", "dsa", "Breadth-First Search", "Explore by distance from the source. Shortest paths in unweighted graphs.", "intermediate", ["graphs", "queue"], ["dfs", "dijkstra"], "dfs", "graph-search"],
  ["dfs", "dsa", "Depth-First Search", "Explore a path to the end, then backtrack. Cycle detection, topology, components.", "intermediate", ["graphs", "stack-ds"], ["bfs", "topological-sort"], "topological-sort", "graph-search"],
  ["topological-sort", "dsa", "Topological Sort", "A linear order of a DAG so every edge goes forward. Build systems and course schedules.", "intermediate", ["dfs", "graphs"], ["dfs"], "dijkstra"],
  ["dijkstra", "dsa", "Dijkstra's Algorithm", "Non-negative shortest paths via a greedy frontier and a priority queue.", "intermediate", ["graphs", "priority-queues"], ["bellman-ford", "bfs"], "bellman-ford", "dijkstra"],
  ["bellman-ford", "dsa", "Bellman-Ford", "Relax all edges |V|−1 times. Handles negative weights and reports negative cycles.", "advanced", ["graphs"], ["dijkstra", "floyd-warshall"], "floyd-warshall"],
  ["floyd-warshall", "dsa", "Floyd-Warshall", "All-pairs shortest paths by trying each vertex as an intermediate.", "advanced", ["dynamic-programming", "graphs"], ["bellman-ford"], "kruskal"],
  ["kruskal", "dsa", "Kruskal's Algorithm", "MST by sorting edges and adding those that do not form a cycle (DSU).", "intermediate", ["graphs", "dsu", "greedy"], ["prim"], "prim"],
  ["prim", "dsa", "Prim's Algorithm", "MST by growing a tree from a seed, always adding the cheapest leaving edge.", "intermediate", ["graphs", "priority-queues"], ["kruskal"], "bit-manipulation"],
  ["bit-manipulation", "dsa", "Bit Manipulation", "Using the binary representation: masks, shifts, and counting bits as constant-time tricks.", "intermediate", ["data-types"], ["randomized-algorithms"], "string-algorithms"],
  ["string-algorithms", "dsa", "String Algorithms", "Matching, hashing, KMP, Z-function, and suffix structures for pattern search.", "advanced", ["strings-ds", "tries"], ["tries"], "randomized-algorithms"],
  ["randomized-algorithms", "dsa", "Randomized Algorithms", "Algorithms that flip coins: expected time, Monte Carlo vs Las Vegas, hashing.", "advanced", ["hash-tables", "asymptotic-notation"], ["hash-tables"], "logic"],

  // —— Discrete math
  ["logic", "discrete-math", "Logic", "The rules of valid inference. Every spec, type system, and proof sits on it.", "beginner", [], ["propositional-logic"], "propositional-logic"],
  ["propositional-logic", "discrete-math", "Propositional Logic", "Boolean variables and connectives. Truth tables, SAT, and circuit equivalence.", "beginner", ["logic"], ["predicate-logic", "boolean-algebra"], "predicate-logic"],
  ["predicate-logic", "discrete-math", "Predicate Logic", "Quantifiers over domains. This is the language of specifications and most proofs.", "intermediate", ["propositional-logic"], ["proofs"], "sets"],
  ["sets", "discrete-math", "Sets", "Collections defined by membership. Union, intersection, power set, cardinality.", "beginner", ["logic"], ["relations", "functions-math"], "relations"],
  ["relations", "discrete-math", "Relations", "Subsets of a product. Reflexive, symmetric, transitive — and the closures you take.", "intermediate", ["sets"], ["functions-math", "graph-theory"], "functions-math"],
  ["functions-math", "discrete-math", "Functions", "Mappings from a domain to a codomain: injective, surjective, bijective, invertible.", "beginner", ["sets"], ["relations"], "proofs"],
  ["proofs", "discrete-math", "Proofs", "Direct, contrapositive, contradiction, construction, and the habits that make arguments checkable.", "intermediate", ["logic"], ["induction"], "induction"],
  ["induction", "discrete-math", "Mathematical Induction", "Prove P(n0), assume P(k), prove P(k+1). Strong induction and structural induction included.", "intermediate", ["proofs"], ["recurrence-relations"], "combinatorics"],
  ["combinatorics", "discrete-math", "Combinatorics", "Counting: products, permutations, combinations, inclusion-exclusion, pigeonhole.", "intermediate", ["sets"], ["probability"], "probability"],
  ["probability", "discrete-math", "Probability", "Sample spaces, independence, expectation, and the inequalities used in algorithms.", "intermediate", ["combinatorics"], ["randomized-algorithms"], "graph-theory"],
  ["graph-theory", "discrete-math", "Graph Theory", "The mathematics of graphs: connectivity, coloring, matching, planarity, cuts.", "intermediate", ["graphs", "sets"], ["trees-math"], "trees-math"],
  ["trees-math", "discrete-math", "Trees (Math)", "Acyclic connected graphs. Spanning trees, rooted trees, and counting labeled trees.", "intermediate", ["graph-theory"], ["trees", "kruskal"], "recurrence-relations"],
  ["recurrence-relations", "discrete-math", "Recurrence Relations", "Equations that define a sequence from earlier terms. Master theorem lives here.", "intermediate", ["induction"], ["divide-conquer"], "boolean-algebra"],
  ["boolean-algebra", "discrete-math", "Boolean Algebra", "Algebra of 0/1 with AND, OR, NOT. Normal forms, minimization, and hardware.", "intermediate", ["propositional-logic"], ["alu"], "cpu"],

  // —— Architecture
  ["cpu", "architecture", "CPU", "The processor: fetch an instruction, decode it, execute it, repeat.", "beginner", ["memory"], ["alu", "registers", "isa"], "alu", "cpu-pipeline"],
  ["alu", "architecture", "ALU", "The arithmetic-logic unit: adders, shifters, comparators, and flags.", "beginner", ["cpu", "boolean-algebra"], ["registers"], "registers"],
  ["registers", "architecture", "Registers", "The fastest named storage in the CPU. Architectural vs microarchitectural.", "beginner", ["cpu"], ["isa"], "control-unit"],
  ["control-unit", "architecture", "Control Unit", "The logic that sequences fetch/decode/execute and drives datapath muxes.", "intermediate", ["cpu"], ["isa", "cpu-pipeline"], "isa"],
  ["isa", "architecture", "Instruction Set Architecture", "The contract between software and hardware: opcodes, registers, addressing, memory model.", "intermediate", ["cpu"], ["assembly", "machine-instructions"], "machine-instructions"],
  ["machine-instructions", "architecture", "Machine Instructions", "The binary encoding of operations the CPU actually executes.", "intermediate", ["isa"], ["assembly"], "assembly"],
  ["assembly", "architecture", "Assembly", "A human-readable form of machine code, with labels, directives, and addressing modes.", "intermediate", ["machine-instructions"], ["isa", "compiler"], "memory-hierarchy"],
  ["memory-hierarchy", "architecture", "Memory Hierarchy", "Registers, caches, DRAM, disk — a pyramid that trades capacity for latency.", "intermediate", ["memory", "cpu"], ["cache", "ram"], "cache", "cache-simulator"],
  ["cache", "architecture", "Cache", "Small fast memory that stores recently used blocks. Hits, misses, and associativity.", "intermediate", ["memory-hierarchy"], ["tlb", "cache-coherence"], "ram", "cache-simulator"],
  ["ram", "architecture", "RAM", "Volatile main memory. DRAM cells, DIMMs, and why random access is not actually equal-cost.", "beginner", ["memory-hierarchy"], ["rom", "virtual-memory"], "rom"],
  ["rom", "architecture", "ROM", "Read-mostly memory for firmware and bootstrap. Modern 'ROM' is often flash.", "beginner", ["memory-hierarchy"], ["storage"], "storage"],
  ["storage", "architecture", "Storage", "Persistent devices: HDD, SSD, and the block interface the OS sees.", "beginner", ["memory-hierarchy"], ["file-systems"], "cpu-pipeline"],
  ["cpu-pipeline", "architecture", "CPU Pipeline", "Overlapping fetch, decode, execute, memory, write-back so several instructions are in flight.", "advanced", ["cpu", "control-unit"], ["branch-prediction"], "branch-prediction", "cpu-pipeline"],
  ["branch-prediction", "architecture", "Branch Prediction", "Guessing the next PC so the pipeline does not stall on every if.", "advanced", ["cpu-pipeline"], ["cpu-pipeline"], "multicore"],
  ["multicore", "architecture", "Multicore Processors", "Several cores on one die, sharing some caches and all of memory — and the problems that follow.", "intermediate", ["cpu"], ["cache-coherence", "numa"], "gpu"],
  ["gpu", "architecture", "GPU", "A throughput processor: thousands of lanes, SIMT, and a memory system built for bandwidth.", "intermediate", ["cpu", "simd"], ["simd", "computer-graphics-fundamentals"], "simd"],
  ["simd", "architecture", "SIMD", "One instruction, many data. Vector units, warps, and data-parallel loops.", "intermediate", ["cpu"], ["gpu"], "dma"],
  ["dma", "architecture", "DMA", "Devices that copy memory without occupying the CPU for every byte.", "intermediate", ["cpu", "memory"], ["interrupts-arch"], "interrupts-arch"],
  ["interrupts-arch", "architecture", "Interrupts (Hardware)", "An asynchronous signal that vectors the CPU into a handler, then returns.", "intermediate", ["cpu"], ["interrupts-os", "dma"], "cache-coherence"],
  ["cache-coherence", "architecture", "Cache Coherence", "The protocol that keeps per-core caches from disagreeing about a line (MESI and friends).", "advanced", ["cache", "multicore"], ["numa"], "numa"],
  ["numa", "architecture", "NUMA", "Non-uniform memory access: local DRAM is faster than remote DRAM on another socket.", "advanced", ["multicore", "memory-hierarchy"], ["cache-coherence"], "what-is-os"],

  // —— OS
  ["what-is-os", "os", "What is an OS?", "The program that multiplexes hardware and offers processes a usable machine.", "beginner", ["cpu", "memory"], ["kernel"], "kernel"],
  ["kernel", "os", "Kernel", "The privileged core of the OS: syscalls, scheduling, virtual memory, drivers.", "intermediate", ["what-is-os"], ["system-calls", "user-mode"], "system-calls"],
  ["system-calls", "os", "System Calls", "The trap into the kernel: the only legal way a user program asks for privileged work.", "intermediate", ["kernel"], ["user-mode", "kernel-mode"], "user-mode"],
  ["user-mode", "os", "User Mode", "Unprivileged execution. Page faults and syscalls are how you leave it.", "beginner", ["kernel"], ["kernel-mode"], "kernel-mode"],
  ["kernel-mode", "os", "Kernel Mode", "Privileged execution: the CPU will honor instructions that touch control registers and I/O.", "intermediate", ["user-mode"], ["system-calls"], "processes"],
  ["processes", "os", "Processes", "An OS abstraction: address space, at least one thread, and a pile of kernel metadata.", "beginner", ["what-is-os", "memory"], ["threads", "process-states"], "threads", "process-states"],
  ["threads", "os", "Threads", "A schedulable execution context. Threads in one process share an address space.", "intermediate", ["processes"], ["synchronization", "context-switching"], "process-states"],
  ["process-states", "os", "Process States", "New, ready, running, waiting, terminated — and the events that move a process between them.", "beginner", ["processes"], ["cpu-scheduling", "context-switching"], "context-switching", "process-states"],
  ["context-switching", "os", "Context Switching", "Saving one thread's registers and loading another's so the CPU can change jobs.", "intermediate", ["threads", "registers"], ["cpu-scheduling"], "cpu-scheduling"],
  ["cpu-scheduling", "os", "CPU Scheduling", "The policy that picks the next ready thread. Fairness, latency, and throughput trade off.", "intermediate", ["process-states"], ["fcfs", "sjf", "round-robin"], "fcfs", "cpu-scheduler"],
  ["fcfs", "os", "FCFS", "First-come, first-served. Simple, convoy-prone, no preemption required.", "beginner", ["cpu-scheduling"], ["sjf", "round-robin"], "sjf", "cpu-scheduler"],
  ["sjf", "os", "SJF", "Shortest job first. Optimal average waiting time if you magically know run times.", "intermediate", ["cpu-scheduling"], ["fcfs", "priority-scheduling"], "round-robin", "cpu-scheduler"],
  ["round-robin", "os", "Round Robin", "Time slices in a cycle. The quantum is the whole design.", "beginner", ["cpu-scheduling", "queue"], ["fcfs", "priority-scheduling"], "priority-scheduling", "cpu-scheduler"],
  ["priority-scheduling", "os", "Priority Scheduling", "Run the highest-priority ready thread. Starvation and aging come with it.", "intermediate", ["cpu-scheduling"], ["round-robin"], "synchronization"],
  ["synchronization", "os", "Synchronization", "Coordinating threads that share state so the result could have been sequential.", "intermediate", ["threads"], ["race-conditions", "mutex"], "race-conditions"],
  ["race-conditions", "os", "Race Conditions", "When the result depends on an unlucky interleaving of concurrent accesses.", "intermediate", ["synchronization"], ["critical-sections", "mutex"], "critical-sections"],
  ["critical-sections", "os", "Critical Sections", "Code that must run as if atomic with respect to other threads touching the same data.", "intermediate", ["race-conditions"], ["mutex", "semaphore"], "mutex"],
  ["mutex", "os", "Mutex", "Mutual exclusion: at most one holder. The lock you actually want most of the time.", "intermediate", ["critical-sections"], ["semaphore", "deadlocks"], "semaphore"],
  ["semaphore", "os", "Semaphore", "A counter with wait/signal. Mutexes are semaphores of 1; producer-consumer uses more.", "intermediate", ["mutex"], ["monitors", "deadlocks"], "monitors"],
  ["monitors", "os", "Monitors", "A language-level construct: a mutex plus condition variables bundled with the data.", "intermediate", ["mutex"], ["semaphore"], "deadlocks"],
  ["deadlocks", "os", "Deadlocks", "A cycle of waits. Coffman conditions, detection, and the ways out.", "intermediate", ["mutex", "semaphore"], ["deadlock-prevention", "bankers-algorithm"], "deadlock-prevention", "deadlock-simulator"],
  ["deadlock-prevention", "os", "Deadlock Prevention", "Break a Coffman condition so a cycle cannot form: no hold-and-wait, preemption, ordering.", "intermediate", ["deadlocks"], ["deadlock-avoidance"], "deadlock-avoidance"],
  ["deadlock-avoidance", "os", "Deadlock Avoidance", "Admit a request only if the resulting state is safe. Banker's algorithm is the classic.", "advanced", ["deadlocks"], ["bankers-algorithm"], "bankers-algorithm"],
  ["bankers-algorithm", "os", "Banker's Algorithm", "Dijkstra's safety algorithm: pretend to allocate, see if a finish order exists.", "advanced", ["deadlock-avoidance"], ["deadlocks"], "memory-management", "deadlock-simulator"],
  ["memory-management", "os", "Memory Management", "How the OS carves physical memory for processes: allocation, protection, sharing.", "intermediate", ["memory", "processes"], ["paging", "segmentation"], "paging"],
  ["paging", "os", "Paging", "Fixed-size pages and frames. The idea that makes virtual memory practical.", "intermediate", ["memory-management"], ["page-tables", "virtual-memory"], "segmentation", "paging-simulator"],
  ["segmentation", "os", "Segmentation", "Variable-sized logical regions (code, heap, stack) with base and limit.", "intermediate", ["memory-management"], ["paging"], "virtual-memory"],
  ["virtual-memory", "os", "Virtual Memory", "Each process sees its own address space, backed by RAM and disk as needed.", "intermediate", ["paging"], ["page-tables", "page-replacement"], "page-tables"],
  ["page-tables", "os", "Page Tables", "The map from virtual page to frame (or disk). Multi-level to keep them sparse.", "intermediate", ["paging", "virtual-memory"], ["tlb"], "tlb"],
  ["tlb", "os", "TLB", "A cache of page-table entries so every load does not walk the page table.", "intermediate", ["page-tables", "cache"], ["paging"], "page-replacement", "paging-simulator"],
  ["page-replacement", "os", "Page Replacement", "Which resident page to evict on a fault. The policy is the whole game.", "intermediate", ["virtual-memory"], ["lru", "fifo-replacement"], "lru", "page-replacement"],
  ["lru", "os", "LRU", "Replace the page unused for the longest time. Stack algorithms and clock approximations.", "intermediate", ["page-replacement"], ["fifo-replacement"], "fifo-replacement", "page-replacement"],
  ["fifo-replacement", "os", "FIFO Replacement", "Evict the oldest page. Belady's anomaly is the interview sting.", "beginner", ["page-replacement"], ["lru"], "thrashing", "page-replacement"],
  ["thrashing", "os", "Thrashing", "When the working set does not fit, the system spends its time paging, not computing.", "intermediate", ["page-replacement", "virtual-memory"], ["working-set"], "file-systems"],
  ["file-systems", "os", "File Systems", "The on-disk (and in-memory) structures that turn bytes into files, directories, and mounts.", "intermediate", ["storage"], ["disk-scheduling"], "disk-scheduling"],
  ["disk-scheduling", "os", "Disk Scheduling", "FCFS, SSTF, SCAN — algorithms from the HDD era that still show up in interviews.", "intermediate", ["file-systems"], ["io"], "io"],
  ["io", "os", "I/O", "How the kernel talks to devices: programmed I/O, interrupts, DMA, block vs character.", "intermediate", ["dma", "interrupts-os"], ["interrupts-os"], "interrupts-os"],
  ["interrupts-os", "os", "Interrupts (OS)", "The kernel's view: interrupt context, bottom halves, and why you cannot sleep in a handler.", "intermediate", ["interrupts-arch", "kernel"], ["signals", "io"], "signals"],
  ["signals", "os", "Signals", "Software interrupts to a process: SIGINT, SIGCHLD, handlers, and async-signal-safety.", "intermediate", ["processes"], ["ipc"], "ipc"],
  ["ipc", "os", "IPC", "Pipes, sockets, shared memory, message queues — how processes exchange data.", "intermediate", ["processes"], ["signals", "message-passing"], "linux-process-model"],
  ["linux-process-model", "os", "Linux Process Model", "Tasks, fork, clone, copy-on-write, namespaces, and cgroups as the real Unix.", "advanced", ["processes", "linux-fundamentals"], ["fork", "threads"], "what-is-networking"],

  // —— Networks
  ["what-is-networking", "networks", "What is Networking?", "Independent machines exchanging messages over a shared, unreliable medium.", "beginner", [], ["lan", "osi-model"], "lan"],
  ["lan", "networks", "LAN", "A local area network: one broadcast domain or a few, under one administration.", "beginner", ["what-is-networking"], ["wan", "ethernet"], "wan"],
  ["wan", "networks", "WAN", "A wide-area network spanning sites and usually several providers.", "beginner", ["what-is-networking"], ["lan", "routing"], "man"],
  ["man", "networks", "MAN", "A metropolitan network: a city-scale fabric, often provider-owned fiber.", "beginner", ["lan"], ["wan"], "pan"],
  ["pan", "networks", "PAN", "A personal area network: Bluetooth, USB, the devices around one person.", "beginner", ["what-is-networking"], ["lan"], "network-topology"],
  ["network-topology", "networks", "Network Topology", "Bus, star, ring, mesh, hybrid — how nodes are wired, logically and physically.", "beginner", ["what-is-networking"], ["switch", "router"], "client-server"],
  ["client-server", "networks", "Client/Server", "A role split: clients initiate, servers wait and respond. Most of the internet.", "beginner", ["what-is-networking"], ["peer-to-peer", "http"], "peer-to-peer"],
  ["peer-to-peer", "networks", "Peer-to-Peer", "Nodes that are both client and server. BitTorrent, some overlay networks, some blockchains.", "intermediate", ["client-server"], ["distributed-fundamentals"], "network-devices"],
  ["network-devices", "networks", "Network Devices", "The box-level view: hubs, switches, routers, firewalls, and where each sits in the stack.", "beginner", ["osi-model"], ["hub", "switch", "router"], "hub"],
  ["hub", "networks", "Hub", "A physical-layer repeater: every bit out every port. Collision domain = the whole hub.", "beginner", ["l1-physical"], ["switch", "repeater"], "switch"],
  ["switch", "networks", "Switch", "A data-link device that forwards frames by MAC and splits collision domains.", "beginner", ["l2-data-link", "mac-addresses"], ["bridge", "vlan"], "router"],
  ["router", "networks", "Router", "A network-layer device that forwards packets between subnets using a routing table.", "beginner", ["l3-network", "ip"], ["routing", "gateway"], "bridge"],
  ["bridge", "networks", "Bridge", "Connects two L2 segments and learns MACs. A switch is a multi-port bridge.", "beginner", ["switch"], ["switch"], "gateway"],
  ["gateway", "networks", "Gateway", "A node that translates between networks or protocols — often just 'the router'.", "beginner", ["router"], ["nat", "firewall"], "repeater"],
  ["repeater", "networks", "Repeater", "Amplifies or retimes a signal to extend a physical segment.", "beginner", ["l1-physical"], ["hub"], "modem"],
  ["modem", "networks", "Modem", "Modulator-demodulator: analog carrier on, bits off, and the reverse.", "beginner", ["l1-physical"], ["signals"], "access-point"],
  ["access-point", "networks", "Access Point", "A bridge between wireless stations and a wired LAN, with association and encryption.", "beginner", ["l2-data-link"], ["wifi"], "firewall"],
  ["firewall", "networks", "Firewall", "A policy box: filter, NAT, or proxy traffic by rule. Host or network, stateful or not.", "intermediate", ["network-security"], ["nat", "router"], "osi-model"],

  ["osi-model", "networks", "OSI Model", "Seven layers of function, from photons to application messages. The shared language of networking.", "beginner", ["what-is-networking"], ["tcp-ip-model", "l7-application", "l1-physical"], "l7-application", "osi-explorer"],
  ["l7-application", "networks", "Layer 7 — Application", "The OSI layer where applications meet the network: HTTP, DNS, SMTP, and their data.", "beginner", ["osi-model"], ["dns", "http", "smtp"], "l6-presentation", "osi-explorer"],
  ["l6-presentation", "networks", "Layer 6 — Presentation", "Syntax and encryption: encoding, compression, TLS as it is often taught at this layer.", "beginner", ["osi-model"], ["tls", "encryption"], "l5-session", "osi-explorer"],
  ["l5-session", "networks", "Layer 5 — Session", "Dialogs: setup, teardown, and checkpoints. Thin in TCP/IP, explicit in some RPC systems.", "beginner", ["osi-model"], ["rpc", "tcp"], "l4-transport", "osi-explorer"],
  ["l4-transport", "networks", "Layer 4 — Transport", "Process-to-process: ports, reliability, and congestion control. TCP and UDP live here.", "beginner", ["osi-model"], ["tcp", "udp", "ports"], "l3-network", "osi-explorer"],
  ["l3-network", "networks", "Layer 3 — Network", "Host-to-host across hops: IP, routing, ICMP. Packets and logical addresses.", "beginner", ["osi-model"], ["ip", "routing", "icmp"], "l2-data-link", "osi-explorer"],
  ["l2-data-link", "networks", "Layer 2 — Data Link", "Hop-to-hop frames: MAC addresses, Ethernet, switches, and error detection.", "beginner", ["osi-model"], ["ethernet", "mac-addresses", "frames"], "l1-physical", "osi-explorer"],
  ["l1-physical", "networks", "Layer 1 — Physical", "Bits on a medium: voltage, light, radio, connectors, and the limits of Shannon.", "beginner", ["osi-model"], ["signals", "transmission-media"], "tcp-ip-model", "osi-explorer"],
  ["tcp-ip-model", "networks", "TCP/IP Model", "Four layers the internet actually runs: application, transport, internet, network access.", "beginner", ["osi-model"], ["osi-vs-tcpip", "ip", "tcp"], "osi-vs-tcpip", "osi-explorer"],
  ["osi-vs-tcpip", "networks", "OSI vs TCP/IP", "A seven-layer teaching model versus a four-layer running model. Same ideas, different cuts.", "beginner", ["osi-model", "tcp-ip-model"], ["osi-model"], "signals"],

  ["signals", "networks", "Signals", "The physical representation of bits: analog vs digital, encoding, and noise.", "intermediate", ["l1-physical"], ["bandwidth", "modulation"], "bandwidth"],
  ["bandwidth", "networks", "Bandwidth", "How much spectrum or bit-rate a channel offers. Not the same thing as throughput.", "beginner", ["signals"], ["latency", "throughput"], "latency"],
  ["latency", "networks", "Latency", "One-way or round-trip delay. Propagation, transmission, queueing, processing.", "beginner", ["bandwidth"], ["throughput"], "transmission-media"],
  ["transmission-media", "networks", "Transmission Media", "Copper, fiber, and wireless — each with a noise, cost, and distance story.", "beginner", ["l1-physical"], ["fiber", "copper", "wireless-phy"], "fiber"],
  ["fiber", "networks", "Fiber", "Light in glass. Huge bandwidth, long reach, immunity to electrical noise.", "beginner", ["transmission-media"], ["copper"], "copper"],
  ["copper", "networks", "Copper", "Twisted pair and coax. Cheap, familiar, and still how most desks are wired.", "beginner", ["transmission-media"], ["fiber"], "wireless-phy"],
  ["wireless-phy", "networks", "Wireless", "Shared spectrum, fading, and a MAC that is nothing like a wire.", "intermediate", ["transmission-media"], ["access-point"], "modulation"],
  ["modulation", "networks", "Modulation", "Imprinting bits on a carrier: AM, FM, PSK, QAM — the physical alphabet.", "intermediate", ["signals"], ["modem"], "frames"],

  ["frames", "networks", "Frames", "The data-link PDU: header, payload, trailer. Ethernet's 14-byte header is the one you will draw.", "beginner", ["l2-data-link"], ["mac-addresses", "ethernet"], "mac-addresses"],
  ["mac-addresses", "networks", "MAC Addresses", "48-bit link-layer identifiers. Unique-ish, local or universal, unicast or group.", "beginner", ["l2-data-link"], ["ethernet", "arp"], "ethernet"],
  ["ethernet", "networks", "Ethernet", "The LAN technology: CSMA/CD history, switching present, 802.3 framing.", "beginner", ["frames", "mac-addresses"], ["switching", "vlan"], "switching"],
  ["switching", "networks", "Switching", "Learn MACs, flood unknowns, forward knowns, filter the rest. CAM tables and STP.", "intermediate", ["switch", "ethernet"], ["vlan", "stp"], "arp"],
  ["arp", "networks", "ARP", "Resolve IPv4 to MAC on a LAN. The cache, the timeout, and the spoof.", "intermediate", ["ip", "mac-addresses"], ["ipv4", "ethernet"], "error-detection"],
  ["error-detection", "networks", "Error Detection", "Parity, checksums, CRC. Detecting corruption is cheaper than preventing it.", "intermediate", ["frames"], ["ethernet"], "vlan"],
  ["vlan", "networks", "VLANs", "One physical switch, many broadcast domains. 802.1Q tags and trunk ports.", "intermediate", ["switching"], ["ethernet"], "ip"],

  ["ip", "networks", "IP", "The internet's network protocol: best-effort datagrams and hierarchical addresses.", "beginner", ["l3-network"], ["ipv4", "ipv6", "routing"], "ipv4"],
  ["ipv4", "networks", "IPv4", "32-bit addresses, dotted quad, fragmentation, and a header you should be able to sketch.", "beginner", ["ip"], ["ipv6", "subnetting", "nat"], "ipv6"],
  ["ipv6", "networks", "IPv6", "128-bit addresses, no NAT-as-crutch, SLAAC, and a simpler header.", "intermediate", ["ip"], ["ipv4"], "subnetting"],
  ["subnetting", "networks", "Subnetting", "Carving a prefix into smaller networks. Masks, hosts, and the all-zero/all-one rules.", "intermediate", ["ipv4"], ["cidr"], "cidr"],
  ["cidr", "networks", "CIDR", "Classless addressing: a prefix and a length. Aggregation is the point.", "intermediate", ["subnetting", "ipv4"], ["routing"], "routing"],
  ["routing", "networks", "Routing", "Choosing a next hop. Tables, longest prefix match, and intra- vs inter-domain.", "intermediate", ["ip", "router"], ["routing-protocols", "bgp"], "icmp", "routing-simulator"],
  ["icmp", "networks", "ICMP", "IP's control plane for errors and diagnostics. Ping and traceroute ride it.", "beginner", ["ip"], ["ipv4"], "nat"],
  ["nat", "networks", "NAT", "Rewriting addresses (and usually ports) so many hosts share a public IP.", "intermediate", ["ipv4", "router"], ["firewall"], "routing-protocols"],
  ["routing-protocols", "networks", "Routing Protocols", "RIP, OSPF, BGP: how routers learn paths they did not configure by hand.", "advanced", ["routing"], ["bgp", "ospf"], "tcp"],

  ["tcp", "networks", "TCP", "Reliable, ordered, congestion-controlled byte streams between two ports.", "beginner", ["l4-transport"], ["udp", "tcp-handshake"], "udp", "tcp-simulator"],
  ["udp", "networks", "UDP", "Datagrams with ports and a checksum. No connection, no retransmission, no congestion control.", "beginner", ["l4-transport"], ["tcp", "ports"], "ports"],
  ["ports", "networks", "Ports", "16-bit transport addresses that multiplex a host. Well-known, registered, ephemeral.", "beginner", ["tcp", "udp"], ["tcp", "nat"], "tcp-handshake"],
  ["tcp-handshake", "networks", "TCP Handshake", "SYN, SYN-ACK, ACK. Sequence numbers exchanged so a connection can start.", "beginner", ["tcp"], ["tcp-teardown", "tcp"], "tcp-teardown", "tcp-simulator"],
  ["tcp-teardown", "networks", "TCP Teardown", "Four-way (or three-way with FIN-ACK) close, TIME-WAIT, and why half-open exists.", "intermediate", ["tcp-handshake"], ["tcp"], "flow-control", "tcp-simulator"],
  ["flow-control", "networks", "Flow Control", "Stopping a fast sender from drowning a slow receiver. TCP's window.", "intermediate", ["tcp"], ["congestion-control"], "congestion-control"],
  ["congestion-control", "networks", "Congestion Control", "Protecting the network from collapse: slow start, AIMD, ECN, and BBR.", "advanced", ["tcp", "flow-control"], ["tcp"], "dns"],

  ["dns", "networks", "DNS", "The hierarchical lookup that turns names into records — usually addresses.", "beginner", ["l7-application"], ["dhcp", "http"], "dhcp", "dns-simulator"],
  ["dhcp", "networks", "DHCP", "Automatic host configuration: address, mask, gateway, DNS, lease.", "beginner", ["ipv4"], ["dns"], "http"],
  ["http", "networks", "HTTP", "The application protocol of the web: methods, status codes, headers, and now HTTP/2 and /3.", "beginner", ["l7-application", "tcp"], ["https", "rest"], "https", "http-simulator"],
  ["https", "networks", "HTTPS", "HTTP over TLS. Confidentiality, integrity, and (usually) server authentication.", "beginner", ["http", "tls"], ["tls", "certificates"], "ftp", "http-simulator"],
  ["ftp", "networks", "FTP", "A historic file protocol with separate control and data channels. Prefer SFTP/HTTPS.", "beginner", ["tcp"], ["ssh"], "smtp"],
  ["smtp", "networks", "SMTP", "How mail moves between MTAs. Store-and-forward, MX records, and spam as an adversarial load.", "beginner", ["dns", "l7-application"], ["dns"], "ssh"],
  ["ssh", "networks", "SSH", "Authenticated, encrypted remote shells and tunnels. Keys, not passwords, if you can.", "beginner", ["tcp", "encryption"], ["linux-fundamentals"], "websockets"],
  ["websockets", "networks", "WebSockets", "A TCP-backed, full-duplex channel started with an HTTP upgrade.", "intermediate", ["http", "tcp"], ["http"], "database-fundamentals"],
];

export const NAV: NavTopic[] = ROWS.map(([slug, section, title, summary, level, prereqs, related, next, viz]) => ({
  slug,
  section,
  title,
  summary,
  level,
  prereqs,
  related,
  next,
  viz,
  lab: viz,
}));

export const NAV_BY_SLUG: Record<string, NavTopic> = Object.fromEntries(NAV.map((t) => [t.slug, t]));
