import type { LearningPath } from "./types";

export const PATHS: LearningPath[] = [
  {
    id: "beginner",
    title: "Beginner",
    blurb: "From writing a program to the systems that run it. The CS core, in order.",
    audience: "New to computer science",
    slugs: [
      "what-is-programming",
      "variables",
      "functions",
      "arrays",
      "linked-lists",
      "asymptotic-notation",
      "sorting",
      "cpu",
      "memory-hierarchy",
      "processes",
      "cpu-scheduling",
      "osi-model",
      "tcp",
      "sql",
      "acid",
      "scalability",
    ],
  },
  {
    id: "interview",
    title: "Interview",
    blurb: "The stack most product-engineering interviews actually sample.",
    audience: "Software engineering interviews",
    slugs: [
      "arrays",
      "hash-tables",
      "trees",
      "bst",
      "graphs",
      "bfs",
      "dfs",
      "dynamic-programming",
      "binary-search",
      "solid",
      "processes",
      "threads",
      "deadlocks",
      "virtual-memory",
      "indexes",
      "transactions",
      "tcp",
      "http",
      "cap-theorem",
      "load-balancers",
      "url-shortener",
    ],
  },
  {
    id: "backend",
    title: "Backend Engineer",
    blurb: "From process model to distributed design, with Linux and databases in the middle.",
    audience: "Backend / platform engineers",
    slugs: [
      "what-is-programming",
      "python",
      "go",
      "hash-tables",
      "graphs",
      "linux-fundamentals",
      "processes",
      "virtual-memory",
      "tcp",
      "http",
      "sql",
      "indexes",
      "transactions",
      "rest",
      "authentication",
      "replication-dist",
      "consensus",
      "cap-theorem",
      "caches-sd",
      "kubernetes",
    ],
  },
  {
    id: "ai-engineer",
    title: "AI Engineer",
    blurb: "Math and models first, then transformers, then the systems that serve them.",
    audience: "ML / LLM engineers",
    slugs: [
      "python",
      "probability",
      "supervised",
      "overfitting",
      "neural-networks",
      "backpropagation",
      "cnn",
      "attention",
      "transformers",
      "tokenization",
      "embeddings",
      "pretraining",
      "rag",
      "vector-databases",
      "ai-system-design",
    ],
  },
];

export const PATH_BY_ID = Object.fromEntries(PATHS.map((p) => [p.id, p]));
