import { RedirectFunction, Routes } from "@angular/router";
import { topicHref } from "@/lib/content";
import { MainLayout } from "@/app/layout/main";
import { AboutPage } from "@/app/pages/about/about";
import { ContactPage } from "@/app/pages/contact/contact";
import { Home } from "@/app/pages/home/home";
import { Library } from "@/app/pages/library/library";
import { NotFound } from "@/app/pages/not-found/not-found";
import { Path } from "@/app/pages/paths/path/path";
import { Paths } from "@/app/pages/paths/paths";
import { DbmsPage } from "@/app/pages/dbms/dbms";
import { NetworksPage } from "@/app/pages/networks/networks";
import { OsPage } from "@/app/pages/os/os";
import { PrivacyPage } from "@/app/pages/privacy/privacy";
import { TermsPage } from "@/app/pages/terms/terms";

const toTopicPage: RedirectFunction = ({ params }) => topicHref(params["slug"] ?? "");

export const routes: Routes = [
  {
    path: "",
    component: MainLayout,
    children: [
      { path: "", component: Home, title: "CS — Learn computer science in depth" },
      {
        path: "library",
        children: [
          { path: "", component: Library, title: "Library · CS" },
          { path: ":slug", redirectTo: toTopicPage },
        ],
      },
      {
        path: "networks",
        children: [
          { path: "", component: NetworksPage, title: "Computer Networks · CS" },
          { path: "access-point", loadComponent: () => import("@/app/pages/networks/access-point/access-point").then((m) => m.NetworksAccessPointPage), title: "Access Point · CS" },
          { path: "arp", loadComponent: () => import("@/app/pages/networks/arp/arp").then((m) => m.NetworksArpPage), title: "ARP · CS" },
          { path: "bandwidth", loadComponent: () => import("@/app/pages/networks/bandwidth/bandwidth").then((m) => m.NetworksBandwidthPage), title: "Bandwidth · CS" },
          { path: "bgp", loadComponent: () => import("@/app/pages/networks/bgp/bgp").then((m) => m.NetworksBgpPage), title: "BGP · CS" },
          { path: "bridge", loadComponent: () => import("@/app/pages/networks/bridge/bridge").then((m) => m.NetworksBridgePage), title: "Bridge · CS" },
          { path: "cidr", loadComponent: () => import("@/app/pages/networks/cidr/cidr").then((m) => m.NetworksCidrPage), title: "CIDR · CS" },
          { path: "client-server", loadComponent: () => import("@/app/pages/networks/client-server/client-server").then((m) => m.NetworksClientServerPage), title: "Client/Server · CS" },
          { path: "congestion-control", loadComponent: () => import("@/app/pages/networks/congestion-control/congestion-control").then((m) => m.NetworksCongestionControlPage), title: "Congestion Control · CS" },
          { path: "copper", loadComponent: () => import("@/app/pages/networks/copper/copper").then((m) => m.NetworksCopperPage), title: "Copper · CS" },
          { path: "dhcp", loadComponent: () => import("@/app/pages/networks/dhcp/dhcp").then((m) => m.NetworksDhcpPage), title: "DHCP · CS" },
          { path: "dns", loadComponent: () => import("@/app/pages/networks/dns/dns").then((m) => m.NetworksDnsPage), title: "DNS · CS" },
          { path: "error-detection", loadComponent: () => import("@/app/pages/networks/error-detection/error-detection").then((m) => m.NetworksErrorDetectionPage), title: "Error Detection · CS" },
          { path: "ethernet", loadComponent: () => import("@/app/pages/networks/ethernet/ethernet").then((m) => m.NetworksEthernetPage), title: "Ethernet · CS" },
          { path: "fiber", loadComponent: () => import("@/app/pages/networks/fiber/fiber").then((m) => m.NetworksFiberPage), title: "Fiber · CS" },
          { path: "firewall", loadComponent: () => import("@/app/pages/networks/firewall/firewall").then((m) => m.NetworksFirewallPage), title: "Firewall · CS" },
          { path: "flow-control", loadComponent: () => import("@/app/pages/networks/flow-control/flow-control").then((m) => m.NetworksFlowControlPage), title: "Flow Control · CS" },
          { path: "frames", loadComponent: () => import("@/app/pages/networks/frames/frames").then((m) => m.NetworksFramesPage), title: "Frames · CS" },
          { path: "ftp", loadComponent: () => import("@/app/pages/networks/ftp/ftp").then((m) => m.NetworksFtpPage), title: "FTP · CS" },
          { path: "gateway", loadComponent: () => import("@/app/pages/networks/gateway/gateway").then((m) => m.NetworksGatewayPage), title: "Gateway · CS" },
          { path: "http", loadComponent: () => import("@/app/pages/networks/http/http").then((m) => m.NetworksHttpPage), title: "HTTP · CS" },
          { path: "https", loadComponent: () => import("@/app/pages/networks/https/https").then((m) => m.NetworksHttpsPage), title: "HTTPS · CS" },
          { path: "hub", loadComponent: () => import("@/app/pages/networks/hub/hub").then((m) => m.NetworksHubPage), title: "Hub · CS" },
          { path: "icmp", loadComponent: () => import("@/app/pages/networks/icmp/icmp").then((m) => m.NetworksIcmpPage), title: "ICMP · CS" },
          { path: "ip", loadComponent: () => import("@/app/pages/networks/ip/ip").then((m) => m.NetworksIpPage), title: "IP · CS" },
          { path: "ipv4", loadComponent: () => import("@/app/pages/networks/ipv4/ipv4").then((m) => m.NetworksIpv4Page), title: "IPv4 · CS" },
          { path: "ipv6", loadComponent: () => import("@/app/pages/networks/ipv6/ipv6").then((m) => m.NetworksIpv6Page), title: "IPv6 · CS" },
          { path: "l1-physical", loadComponent: () => import("@/app/pages/networks/l1-physical/l1-physical").then((m) => m.NetworksL1PhysicalPage), title: "Layer 1 — Physical · CS" },
          { path: "l2-data-link", loadComponent: () => import("@/app/pages/networks/l2-data-link/l2-data-link").then((m) => m.NetworksL2DataLinkPage), title: "Layer 2 — Data Link · CS" },
          { path: "l3-network", loadComponent: () => import("@/app/pages/networks/l3-network/l3-network").then((m) => m.NetworksL3NetworkPage), title: "Layer 3 — Network · CS" },
          { path: "l4-transport", loadComponent: () => import("@/app/pages/networks/l4-transport/l4-transport").then((m) => m.NetworksL4TransportPage), title: "Layer 4 — Transport · CS" },
          { path: "l5-session", loadComponent: () => import("@/app/pages/networks/l5-session/l5-session").then((m) => m.NetworksL5SessionPage), title: "Layer 5 — Session · CS" },
          { path: "l6-presentation", loadComponent: () => import("@/app/pages/networks/l6-presentation/l6-presentation").then((m) => m.NetworksL6PresentationPage), title: "Layer 6 — Presentation · CS" },
          { path: "l7-application", loadComponent: () => import("@/app/pages/networks/l7-application/l7-application").then((m) => m.NetworksL7ApplicationPage), title: "Layer 7 — Application · CS" },
          { path: "lan", loadComponent: () => import("@/app/pages/networks/lan/lan").then((m) => m.NetworksLanPage), title: "LAN · CS" },
          { path: "latency", loadComponent: () => import("@/app/pages/networks/latency/latency").then((m) => m.NetworksLatencyPage), title: "Latency · CS" },
          { path: "mac-addresses", loadComponent: () => import("@/app/pages/networks/mac-addresses/mac-addresses").then((m) => m.NetworksMacAddressesPage), title: "MAC Addresses · CS" },
          { path: "man", loadComponent: () => import("@/app/pages/networks/man/man").then((m) => m.NetworksManPage), title: "MAN · CS" },
          { path: "modem", loadComponent: () => import("@/app/pages/networks/modem/modem").then((m) => m.NetworksModemPage), title: "Modem · CS" },
          { path: "modulation", loadComponent: () => import("@/app/pages/networks/modulation/modulation").then((m) => m.NetworksModulationPage), title: "Modulation · CS" },
          { path: "nat", loadComponent: () => import("@/app/pages/networks/nat/nat").then((m) => m.NetworksNatPage), title: "NAT · CS" },
          { path: "network-devices", loadComponent: () => import("@/app/pages/networks/network-devices/network-devices").then((m) => m.NetworksNetworkDevicesPage), title: "Network Devices · CS" },
          { path: "network-topology", loadComponent: () => import("@/app/pages/networks/network-topology/network-topology").then((m) => m.NetworksNetworkTopologyPage), title: "Network Topology · CS" },
          { path: "osi-model", loadComponent: () => import("@/app/pages/networks/osi-model/osi-model").then((m) => m.NetworksOsiModelPage), title: "OSI Model · CS" },
          { path: "osi-vs-tcpip", loadComponent: () => import("@/app/pages/networks/osi-vs-tcpip/osi-vs-tcpip").then((m) => m.NetworksOsiVsTcpipPage), title: "OSI vs TCP/IP · CS" },
          { path: "ospf", loadComponent: () => import("@/app/pages/networks/ospf/ospf").then((m) => m.NetworksOspfPage), title: "OSPF · CS" },
          { path: "pan", loadComponent: () => import("@/app/pages/networks/pan/pan").then((m) => m.NetworksPanPage), title: "PAN · CS" },
          { path: "peer-to-peer", loadComponent: () => import("@/app/pages/networks/peer-to-peer/peer-to-peer").then((m) => m.NetworksPeerToPeerPage), title: "Peer-to-Peer · CS" },
          { path: "ports", loadComponent: () => import("@/app/pages/networks/ports/ports").then((m) => m.NetworksPortsPage), title: "Ports · CS" },
          { path: "repeater", loadComponent: () => import("@/app/pages/networks/repeater/repeater").then((m) => m.NetworksRepeaterPage), title: "Repeater · CS" },
          { path: "router", loadComponent: () => import("@/app/pages/networks/router/router").then((m) => m.NetworksRouterPage), title: "Router · CS" },
          { path: "routing", loadComponent: () => import("@/app/pages/networks/routing/routing").then((m) => m.NetworksRoutingPage), title: "Routing · CS" },
          { path: "routing-protocols", loadComponent: () => import("@/app/pages/networks/routing-protocols/routing-protocols").then((m) => m.NetworksRoutingProtocolsPage), title: "Routing Protocols · CS" },
          { path: "signals", loadComponent: () => import("@/app/pages/networks/signals/signals").then((m) => m.NetworksSignalsPage), title: "Signals · CS" },
          { path: "smtp", loadComponent: () => import("@/app/pages/networks/smtp/smtp").then((m) => m.NetworksSmtpPage), title: "SMTP · CS" },
          { path: "ssh", loadComponent: () => import("@/app/pages/networks/ssh/ssh").then((m) => m.NetworksSshPage), title: "SSH · CS" },
          { path: "stp", loadComponent: () => import("@/app/pages/networks/stp/stp").then((m) => m.NetworksStpPage), title: "Spanning Tree · CS" },
          { path: "subnetting", loadComponent: () => import("@/app/pages/networks/subnetting/subnetting").then((m) => m.NetworksSubnettingPage), title: "Subnetting · CS" },
          { path: "switch", loadComponent: () => import("@/app/pages/networks/switch/switch").then((m) => m.NetworksSwitchPage), title: "Switch · CS" },
          { path: "switching", loadComponent: () => import("@/app/pages/networks/switching/switching").then((m) => m.NetworksSwitchingPage), title: "Switching · CS" },
          { path: "tcp", loadComponent: () => import("@/app/pages/networks/tcp/tcp").then((m) => m.NetworksTcpPage), title: "TCP · CS" },
          { path: "tcp-handshake", loadComponent: () => import("@/app/pages/networks/tcp-handshake/tcp-handshake").then((m) => m.NetworksTcpHandshakePage), title: "TCP Handshake · CS" },
          { path: "tcp-ip-model", loadComponent: () => import("@/app/pages/networks/tcp-ip-model/tcp-ip-model").then((m) => m.NetworksTcpIpModelPage), title: "TCP/IP Model · CS" },
          { path: "tcp-teardown", loadComponent: () => import("@/app/pages/networks/tcp-teardown/tcp-teardown").then((m) => m.NetworksTcpTeardownPage), title: "TCP Teardown · CS" },
          { path: "transmission-media", loadComponent: () => import("@/app/pages/networks/transmission-media/transmission-media").then((m) => m.NetworksTransmissionMediaPage), title: "Transmission Media · CS" },
          { path: "udp", loadComponent: () => import("@/app/pages/networks/udp/udp").then((m) => m.NetworksUdpPage), title: "UDP · CS" },
          { path: "vlan", loadComponent: () => import("@/app/pages/networks/vlan/vlan").then((m) => m.NetworksVlanPage), title: "VLANs · CS" },
          { path: "wan", loadComponent: () => import("@/app/pages/networks/wan/wan").then((m) => m.NetworksWanPage), title: "WAN · CS" },
          { path: "websockets", loadComponent: () => import("@/app/pages/networks/websockets/websockets").then((m) => m.NetworksWebsocketsPage), title: "WebSockets · CS" },
          { path: "what-is-networking", loadComponent: () => import("@/app/pages/networks/what-is-networking/what-is-networking").then((m) => m.NetworksWhatIsNetworkingPage), title: "What is Networking? · CS" },
          { path: "wifi", loadComponent: () => import("@/app/pages/networks/wifi/wifi").then((m) => m.NetworksWifiPage), title: "Wi-Fi · CS" },
          { path: "wireless-phy", loadComponent: () => import("@/app/pages/networks/wireless-phy/wireless-phy").then((m) => m.NetworksWirelessPhyPage), title: "Wireless · CS" },
        ],
      },
      {
        path: "os",
        children: [
          { path: "", component: OsPage, title: "Operating Systems · CS" },
          { path: "bankers-algorithm", loadComponent: () => import("@/app/pages/os/bankers-algorithm/bankers-algorithm").then((m) => m.OsBankersAlgorithmPage), title: "Banker's Algorithm · CS" },
          { path: "context-switching", loadComponent: () => import("@/app/pages/os/context-switching/context-switching").then((m) => m.OsContextSwitchingPage), title: "Context Switching · CS" },
          { path: "cpu-scheduling", loadComponent: () => import("@/app/pages/os/cpu-scheduling/cpu-scheduling").then((m) => m.OsCpuSchedulingPage), title: "CPU Scheduling · CS" },
          { path: "critical-sections", loadComponent: () => import("@/app/pages/os/critical-sections/critical-sections").then((m) => m.OsCriticalSectionsPage), title: "Critical Sections · CS" },
          { path: "deadlock-avoidance", loadComponent: () => import("@/app/pages/os/deadlock-avoidance/deadlock-avoidance").then((m) => m.OsDeadlockAvoidancePage), title: "Deadlock Avoidance · CS" },
          { path: "deadlock-prevention", loadComponent: () => import("@/app/pages/os/deadlock-prevention/deadlock-prevention").then((m) => m.OsDeadlockPreventionPage), title: "Deadlock Prevention · CS" },
          { path: "deadlocks", loadComponent: () => import("@/app/pages/os/deadlocks/deadlocks").then((m) => m.OsDeadlocksPage), title: "Deadlocks · CS" },
          { path: "disk-scheduling", loadComponent: () => import("@/app/pages/os/disk-scheduling/disk-scheduling").then((m) => m.OsDiskSchedulingPage), title: "Disk Scheduling · CS" },
          { path: "fcfs", loadComponent: () => import("@/app/pages/os/fcfs/fcfs").then((m) => m.OsFcfsPage), title: "FCFS · CS" },
          { path: "fifo-replacement", loadComponent: () => import("@/app/pages/os/fifo-replacement/fifo-replacement").then((m) => m.OsFifoReplacementPage), title: "FIFO Replacement · CS" },
          { path: "file-systems", loadComponent: () => import("@/app/pages/os/file-systems/file-systems").then((m) => m.OsFileSystemsPage), title: "File Systems · CS" },
          { path: "fork", loadComponent: () => import("@/app/pages/os/fork/fork").then((m) => m.OsForkPage), title: "fork() · CS" },
          { path: "interrupts-os", loadComponent: () => import("@/app/pages/os/interrupts-os/interrupts-os").then((m) => m.OsInterruptsOsPage), title: "Interrupts (OS) · CS" },
          { path: "io", loadComponent: () => import("@/app/pages/os/io/io").then((m) => m.OsIoPage), title: "I/O · CS" },
          { path: "ipc", loadComponent: () => import("@/app/pages/os/ipc/ipc").then((m) => m.OsIpcPage), title: "IPC · CS" },
          { path: "kernel", loadComponent: () => import("@/app/pages/os/kernel/kernel").then((m) => m.OsKernelPage), title: "Kernel · CS" },
          { path: "kernel-mode", loadComponent: () => import("@/app/pages/os/kernel-mode/kernel-mode").then((m) => m.OsKernelModePage), title: "Kernel Mode · CS" },
          { path: "linux-process-model", loadComponent: () => import("@/app/pages/os/linux-process-model/linux-process-model").then((m) => m.OsLinuxProcessModelPage), title: "Linux Process Model · CS" },
          { path: "lru", loadComponent: () => import("@/app/pages/os/lru/lru").then((m) => m.OsLruPage), title: "LRU · CS" },
          { path: "memory-management", loadComponent: () => import("@/app/pages/os/memory-management/memory-management").then((m) => m.OsMemoryManagementPage), title: "Memory Management · CS" },
          { path: "monitors", loadComponent: () => import("@/app/pages/os/monitors/monitors").then((m) => m.OsMonitorsPage), title: "Monitors · CS" },
          { path: "mutex", loadComponent: () => import("@/app/pages/os/mutex/mutex").then((m) => m.OsMutexPage), title: "Mutex · CS" },
          { path: "page-replacement", loadComponent: () => import("@/app/pages/os/page-replacement/page-replacement").then((m) => m.OsPageReplacementPage), title: "Page Replacement · CS" },
          { path: "page-tables", loadComponent: () => import("@/app/pages/os/page-tables/page-tables").then((m) => m.OsPageTablesPage), title: "Page Tables · CS" },
          { path: "paging", loadComponent: () => import("@/app/pages/os/paging/paging").then((m) => m.OsPagingPage), title: "Paging · CS" },
          { path: "priority-scheduling", loadComponent: () => import("@/app/pages/os/priority-scheduling/priority-scheduling").then((m) => m.OsPrioritySchedulingPage), title: "Priority Scheduling · CS" },
          { path: "process-states", loadComponent: () => import("@/app/pages/os/process-states/process-states").then((m) => m.OsProcessStatesPage), title: "Process States · CS" },
          { path: "processes", loadComponent: () => import("@/app/pages/os/processes/processes").then((m) => m.OsProcessesPage), title: "Processes · CS" },
          { path: "race-conditions", loadComponent: () => import("@/app/pages/os/race-conditions/race-conditions").then((m) => m.OsRaceConditionsPage), title: "Race Conditions · CS" },
          { path: "segmentation", loadComponent: () => import("@/app/pages/os/segmentation/segmentation").then((m) => m.OsSegmentationPage), title: "Segmentation · CS" },
          { path: "signals", loadComponent: () => import("@/app/pages/os/signals/signals").then((m) => m.OsSignalsPage), title: "Signals · CS" },
          { path: "round-robin", loadComponent: () => import("@/app/pages/os/round-robin/round-robin").then((m) => m.OsRoundRobinPage), title: "Round Robin · CS" },
          { path: "semaphore", loadComponent: () => import("@/app/pages/os/semaphore/semaphore").then((m) => m.OsSemaphorePage), title: "Semaphore · CS" },
          { path: "sjf", loadComponent: () => import("@/app/pages/os/sjf/sjf").then((m) => m.OsSjfPage), title: "SJF · CS" },
          { path: "synchronization", loadComponent: () => import("@/app/pages/os/synchronization/synchronization").then((m) => m.OsSynchronizationPage), title: "Synchronization · CS" },
          { path: "system-calls", loadComponent: () => import("@/app/pages/os/system-calls/system-calls").then((m) => m.OsSystemCallsPage), title: "System Calls · CS" },
          { path: "thrashing", loadComponent: () => import("@/app/pages/os/thrashing/thrashing").then((m) => m.OsThrashingPage), title: "Thrashing · CS" },
          { path: "threads", loadComponent: () => import("@/app/pages/os/threads/threads").then((m) => m.OsThreadsPage), title: "Threads · CS" },
          { path: "tlb", loadComponent: () => import("@/app/pages/os/tlb/tlb").then((m) => m.OsTlbPage), title: "TLB · CS" },
          { path: "user-mode", loadComponent: () => import("@/app/pages/os/user-mode/user-mode").then((m) => m.OsUserModePage), title: "User Mode · CS" },
          { path: "virtual-memory", loadComponent: () => import("@/app/pages/os/virtual-memory/virtual-memory").then((m) => m.OsVirtualMemoryPage), title: "Virtual Memory · CS" },
          { path: "what-is-os", loadComponent: () => import("@/app/pages/os/what-is-os/what-is-os").then((m) => m.OsWhatIsOsPage), title: "What is an OS? · CS" },
          { path: "working-set", loadComponent: () => import("@/app/pages/os/working-set/working-set").then((m) => m.OsWorkingSetPage), title: "Working Set · CS" },
        ],
      },
      {
        path: "dbms",
        children: [
          { path: "", component: DbmsPage, title: "Databases / DBMS · CS" },
          { path: "1nf", loadComponent: () => import("@/app/pages/dbms/1nf/1nf").then((m) => m.Dbms1nfPage), title: "1NF · CS" },
          { path: "2nf", loadComponent: () => import("@/app/pages/dbms/2nf/2nf").then((m) => m.Dbms2nfPage), title: "2NF · CS" },
          { path: "3nf", loadComponent: () => import("@/app/pages/dbms/3nf/3nf").then((m) => m.Dbms3nfPage), title: "3NF · CS" },
          { path: "acid", loadComponent: () => import("@/app/pages/dbms/acid/acid").then((m) => m.DbmsAcidPage), title: "ACID · CS" },
          { path: "aggregation", loadComponent: () => import("@/app/pages/dbms/aggregation/aggregation").then((m) => m.DbmsAggregationPage), title: "Aggregation · CS" },
          { path: "b-trees", loadComponent: () => import("@/app/pages/dbms/b-trees/b-trees").then((m) => m.DbmsBTreesPage), title: "B-Trees · CS" },
          { path: "bcnf", loadComponent: () => import("@/app/pages/dbms/bcnf/bcnf").then((m) => m.DbmsBcnfPage), title: "BCNF · CS" },
          { path: "bplus-trees", loadComponent: () => import("@/app/pages/dbms/bplus-trees/bplus-trees").then((m) => m.DbmsBplusTreesPage), title: "B+ Trees · CS" },
          { path: "buffer-pool", loadComponent: () => import("@/app/pages/dbms/buffer-pool/buffer-pool").then((m) => m.DbmsBufferPoolPage), title: "Buffer Pool · CS" },
          { path: "column-stores", loadComponent: () => import("@/app/pages/dbms/column-stores/column-stores").then((m) => m.DbmsColumnStoresPage), title: "Column Stores · CS" },
          { path: "concurrency-db", loadComponent: () => import("@/app/pages/dbms/concurrency-db/concurrency-db").then((m) => m.DbmsConcurrencyDbPage), title: "Database Concurrency · CS" },
          { path: "constraints", loadComponent: () => import("@/app/pages/dbms/constraints/constraints").then((m) => m.DbmsConstraintsPage), title: "Constraints · CS" },
          { path: "database-fundamentals", loadComponent: () => import("@/app/pages/dbms/database-fundamentals/database-fundamentals").then((m) => m.DbmsDatabaseFundamentalsPage), title: "Database Fundamentals · CS" },
          { path: "document-stores", loadComponent: () => import("@/app/pages/dbms/document-stores/document-stores").then((m) => m.DbmsDocumentStoresPage), title: "Document Stores · CS" },
          { path: "foreign-keys", loadComponent: () => import("@/app/pages/dbms/foreign-keys/foreign-keys").then((m) => m.DbmsForeignKeysPage), title: "Foreign Keys · CS" },
          { path: "graph-databases", loadComponent: () => import("@/app/pages/dbms/graph-databases/graph-databases").then((m) => m.DbmsGraphDatabasesPage), title: "Graph Databases · CS" },
          { path: "indexes", loadComponent: () => import("@/app/pages/dbms/indexes/indexes").then((m) => m.DbmsIndexesPage), title: "Indexes · CS" },
          { path: "isolation-levels", loadComponent: () => import("@/app/pages/dbms/isolation-levels/isolation-levels").then((m) => m.DbmsIsolationLevelsPage), title: "Isolation Levels · CS" },
          { path: "joins", loadComponent: () => import("@/app/pages/dbms/joins/joins").then((m) => m.DbmsJoinsPage), title: "Joins · CS" },
          { path: "key-value", loadComponent: () => import("@/app/pages/dbms/key-value/key-value").then((m) => m.DbmsKeyValuePage), title: "Key-Value Stores · CS" },
          { path: "locks-db", loadComponent: () => import("@/app/pages/dbms/locks-db/locks-db").then((m) => m.DbmsLocksDbPage), title: "Locks (DB) · CS" },
          { path: "mvcc", loadComponent: () => import("@/app/pages/dbms/mvcc/mvcc").then((m) => m.DbmsMvccPage), title: "MVCC · CS" },
          { path: "normalization", loadComponent: () => import("@/app/pages/dbms/normalization/normalization").then((m) => m.DbmsNormalizationPage), title: "Normalization · CS" },
          { path: "partitioning", loadComponent: () => import("@/app/pages/dbms/partitioning/partitioning").then((m) => m.DbmsPartitioningPage), title: "Partitioning · CS" },
          { path: "primary-keys", loadComponent: () => import("@/app/pages/dbms/primary-keys/primary-keys").then((m) => m.DbmsPrimaryKeysPage), title: "Primary Keys · CS" },
          { path: "query-optimization", loadComponent: () => import("@/app/pages/dbms/query-optimization/query-optimization").then((m) => m.DbmsQueryOptimizationPage), title: "Query Optimization · CS" },
          { path: "query-planners", loadComponent: () => import("@/app/pages/dbms/query-planners/query-planners").then((m) => m.DbmsQueryPlannersPage), title: "Query Planners · CS" },
          { path: "relational-databases", loadComponent: () => import("@/app/pages/dbms/relational-databases/relational-databases").then((m) => m.DbmsRelationalDatabasesPage), title: "Relational Databases · CS" },
          { path: "replication-db", loadComponent: () => import("@/app/pages/dbms/replication-db/replication-db").then((m) => m.DbmsReplicationDbPage), title: "Replication (DB) · CS" },
          { path: "sharding", loadComponent: () => import("@/app/pages/dbms/sharding/sharding").then((m) => m.DbmsShardingPage), title: "Sharding · CS" },
          { path: "sql", loadComponent: () => import("@/app/pages/dbms/sql/sql").then((m) => m.DbmsSqlPage), title: "SQL · CS" },
          { path: "storage-engines", loadComponent: () => import("@/app/pages/dbms/storage-engines/storage-engines").then((m) => m.DbmsStorageEnginesPage), title: "Storage Engines · CS" },
          { path: "subqueries", loadComponent: () => import("@/app/pages/dbms/subqueries/subqueries").then((m) => m.DbmsSubqueriesPage), title: "Subqueries · CS" },
          { path: "tables", loadComponent: () => import("@/app/pages/dbms/tables/tables").then((m) => m.DbmsTablesPage), title: "Tables · CS" },
          { path: "transactions", loadComponent: () => import("@/app/pages/dbms/transactions/transactions").then((m) => m.DbmsTransactionsPage), title: "Transactions · CS" },
          { path: "views", loadComponent: () => import("@/app/pages/dbms/views/views").then((m) => m.DbmsViewsPage), title: "Views · CS" },
          { path: "wal", loadComponent: () => import("@/app/pages/dbms/wal/wal").then((m) => m.DbmsWalPage), title: "Write-Ahead Log · CS" },
        ],
      },
      { path: "topics", redirectTo: "library", pathMatch: "prefix" },
      { path: "labs", redirectTo: "library", pathMatch: "prefix" },
      { path: "graph", redirectTo: "library" },
      {
        path: "paths",
        children: [
          { path: "", component: Paths, title: "Learning paths · CS" },
          { path: ":id", component: Path, title: "Path · CS" },
        ],
      },
      { path: "about", component: AboutPage, title: "About · CS" },
      { path: "privacy", component: PrivacyPage, title: "Privacy · CS" },
      { path: "terms", component: TermsPage, title: "Terms of Service · CS" },
      { path: "contact", component: ContactPage, title: "Contact · CS" },
      { path: "**", component: NotFound, title: "Not found · CS" },
    ],
  },
];
