import { iq, T } from "../helpers";
import type { ContentBlock, Topic } from "../types";

function caseExtra(rows: string[][], trap: string): ContentBlock[] {
  return [
    {
      type: "flow",
      steps: [
        "Requirements",
        "Capacity",
        "API",
        "Data model",
        "High-level architecture",
        "Scale",
        "Failure handling",
      ],
    },
    { type: "table", headers: ["Piece", "Choice"], rows },
    { type: "callout", kind: "interview", title: "Common trap", text: trap },
  ];
}

export const FLAGSHIP: Topic[] = [
  T({
    slug: "youtube",
    section: "system-design",
    title: "YouTube",
    summary: "Upload, transcode, store, CDN, and a recommendation path that often dwarfs the video path.",
    level: "advanced",
    prereqs: ["object-storage", "cdns"],
    related: ["netflix", "video-streaming"],
    next: "netflix",
    what: "A video platform is two products: a write path (upload → transcode → object store → metadata) and a read path (watch page → signed CDN URL → adaptive bitrate). Thumbnails, comments, and recommendations are separate systems with their own SLOs.",
    why: "It forces you to split metadata from blobs, to think in chunks not files, and to put a CDN in front of anything humans stream.",
    mental: "A blob store with a transcoding farm and a phone book (metadata DB). The CDN is the product users actually touch.",
    points: [
      "Requirements: upload, process many renditions, watch with ABR, like/comment, search, recommendations. Availability over perfect consistency on counts.",
      "Capacity: minutes of video/day × bitrate × copies. Storage dominates. Transcode is bursty CPU/GPU.",
      "API: POST /upload (resumable), GET /watch, GET /manifest.mpd, signed GET on CDN.",
      "Data: videos table (id, owner, duration, status), object keys per rendition, a graph for comments, a search index.",
      "HLD: upload service → queue → transcoders → object storage; metadata DB; CDN; recommendation offline jobs.",
      "Scale: chunked resumable upload, many transcode workers, CDN for 99% of bytes, shard metadata by video_id.",
      "Failures: partial upload, transcode poison message, hot video (CDN + origin shield), region outage (multi-CDN).",
    ],
    steps: [
      "Client requests an upload session; server returns a resumable URL to object storage.",
      "On complete, enqueue transcode. Workers emit 144p–4K plus a manifest.",
      "Watch: app fetches metadata + manifest, player picks a bitrate, CDN serves chunks.",
    ],
    extra: caseExtra(
      [
        ["Blobs", "Object storage, never the primary SQL"],
        ["Hot path", "CDN + short-lived signed URLs"],
        ["Transcode", "Queue + workers, not the upload request"],
        ["Counts", "Eventually consistent counters / cache"],
      ],
      "Putting video bytes in MySQL, or transcoding inside the upload HTTP request.",
    ),
    mistakes: ["One bitrate", "No resumable upload", "Recommendations on the watch critical path without a fallback"],
    usage: ["Any user-generated video product"],
    interview: [
      iq("Why not store video in the database?", "Blobs are huge, sequential, and cacheable. DBs want small rows and transactions. Split metadata from objects.", "intermediate"),
      iq("How does ABR work?", "Encode many renditions. A manifest lists chunk URLs. The player switches quality as bandwidth changes.", "intermediate"),
    ],
  }),
  T({
    slug: "netflix",
    section: "system-design",
    title: "Netflix",
    summary: "Open Connect, adaptive bitrate, and a control plane that is a microservice zoo.",
    level: "advanced",
    prereqs: ["youtube", "cdns"],
    related: ["video-streaming"],
    next: "video-streaming",
    what: "A licensed-video streamer pushes bits to ISP-colocated caches (Open Connect) so the backbone is not the product. The control plane (catalog, auth, personalization, playback licenses) is many services; the data plane is files on appliances near users.",
    why: "It is the textbook of 'move the bytes next to the eyeballs' and of isolating a noisy control plane from a boring data plane.",
    mental: "A CDN you own, plus a website that tells the player which file to ask for.",
    points: [
      "Requirements: catalog, playback, resume, profiles, recommendations, DRM. Prime-time spike.",
      "Capacity: simultaneous streams × bitrate. Peak is the design point.",
      "API: auth, title metadata, playback license, manifest. The video URL is not your origin.",
      "HLD: clients → playback service → Open Connect / CDN; control plane in the cloud.",
      "Failures: appliance down (other OCAs, internet CDN fallback), license service down (no new plays, existing may continue), regional cloud (active-active control).",
    ],
    extra: caseExtra(
      [
        ["Bytes", "ISP-colocated appliances"],
        ["Catalog", "Cloud microservices + cache"],
        ["DRM", "License service on the control plane"],
        ["Fallback", "Public CDN if OCA misses"],
      ],
      "Drawing one giant 'Netflix server' that both personalizes and streams 4K.",
    ),
    mistakes: ["Streaming from a single region origin at peak", "Coupling recommendation outage to playback"],
    usage: ["OTT video", "Any 'pre-position the bytes' design"],
    interview: [
      iq("Why put caches in ISPs?", "Last-mile and peering cost dominate. Pre-position popular titles; the backbone sees control traffic, not every stream.", "advanced"),
    ],
  }),
  T({
    slug: "twitter",
    section: "system-design",
    title: "Twitter / X",
    summary: "Fan-out on write vs read, a home timeline, and the celebrity problem.",
    level: "advanced",
    prereqs: ["url-shortener", "caches-sd"],
    related: ["chat-system"],
    next: "chat-system",
    what: "A tweet is a small row. The hard part is the home timeline: for each follower, a tweet should appear near-real-time. Fan-out on write (push into each follower's cache) is fast to read and painful for celebrities. Fan-out on read (pull at view time) is the reverse. Production mixes both.",
    why: "It is the canonical 'hot key / celebrity' design. If you only know one fan-out story, this is the one.",
    mental: "A post is cheap. Telling a hundred million people about it is not.",
    points: [
      "Requirements: post, follow, home timeline, search, notifications. Low latency on home.",
      "Capacity: write QPS is small vs timeline reads. Storage of tweets is fine; fan-out is the storm.",
      "API: POST /tweets, GET /timeline, POST /follow.",
      "Data: tweets (id, author, text, ts), follows graph, timeline cache (Redis list per user) for ordinary users.",
      "HLD: mix — push to ordinary fans, pull celebrity tweets at read time and merge.",
      "Failures: cache miss storm, celebrity tweet, search indexer lag (eventual is OK).",
    ],
    extra: caseExtra(
      [
        ["Ordinary tweet", "Fan-out on write into Redis lists"],
        ["Celebrity", "Fan-out on read, merge at view"],
        ["Graph", "Follow table, cached counts"],
        ["Search", "Async indexer, not the write path"],
      ],
      "Fan-out on write for every account, including accounts with 100M followers.",
    ),
    mistakes: ["A SQL JOIN of all followees on every home fetch", "One Redis key for the whole site"],
    usage: ["Feeds", "Activity streams"],
    interview: [
      iq("Fan-out on write vs read?", "Write: push the tweet to each follower's timeline (fast read, write amplification). Read: assemble at view time (cheap write, slow/complex read). Hybrid for celebrities.", "intermediate"),
    ],
  }),
  T({
    slug: "chat-system",
    section: "system-design",
    title: "Chat System",
    summary: "One-to-one and group messages, presence, and delivery at the edge of consistency.",
    level: "advanced",
    prereqs: ["websockets", "message-queues"],
    related: ["notification-system"],
    next: "notification-system",
    what: "A chat system delivers small ordered messages with presence and optional groups. Online users want push (WebSocket / HTTP2). Offline users need a store-and-forward inbox. Group chat is fan-out with a membership list.",
    why: "It combines connections, fan-out, ordering, and 'what does delivered mean'. WhatsApp-scale adds E2E encryption on top.",
    mental: "A mailbox plus a live wire. If the wire is down, the mailbox still fills.",
    points: [
      "Requirements: 1:1, groups, delivery receipts, presence, media (via object storage), order per conversation.",
      "API: WS messages; REST for history. Idempotency keys on send.",
      "Data: conversations, members, messages (id, conv, sender, ts, body), device inbox.",
      "HLD: gateway (sticky connections) → chat service → Kafka/queue → fan-out workers → recipient gateways or push.",
      "Order: per-conversation sequence numbers. Causal across conversations is usually not required.",
      "Failures: gateway crash (reconnect + catch-up), duplicate send (idempotency), split brain on presence (timeouts, not truth).",
    ],
    extra: caseExtra(
      [
        ["Online", "WebSocket to a regional gateway"],
        ["Offline", "APNs/FCM + inbox in DB"],
        ["Groups", "Fan-out to members, not a naive query"],
        ["Media", "Object storage, message holds a URL"],
      ],
      "A single chat server with a global TCP connection table, or using DB polling every 300ms.",
    ),
    mistakes: ["Polling as the only transport", "No idempotency on send", "Presence as a strong consistency problem"],
    usage: ["Support chat", "Social DMs", "Workplace messengers"],
    interview: [
      iq("How do you not lose a message if the recipient is offline?", "Persist first (or on a durable log), then attempt push. Receipts are a later write. Never only-in-memory.", "intermediate"),
    ],
  }),
  T({
    slug: "uber",
    section: "system-design",
    title: "Uber",
    summary: "Matching riders to drivers on a map, with dispatch that cannot be a naive query.",
    level: "advanced",
    prereqs: ["geo", "kafka"],
    related: ["ride-sharing"],
    next: "ride-sharing",
    what: "Ride sharing is a three-sided matching problem under a latency budget: a rider request, a set of nearby available drivers, a dispatch that must be fair and fast. Location updates at 1 Hz from millions of phones cannot all hit one database.",
    why: "It is the geo + matching case study. If you only know CRUD, this design is how you learn spatial indexes and supply/demand.",
    mental: "A map of moving supply. Hash the city into cells; only search nearby cells; lock a driver for a few seconds while the offer is out.",
    points: [
      "Requirements: request ride, match, track, complete, pay, ratings. Matching in a few seconds.",
      "Capacity: location updates dominate writes. Use in-memory geo (Redis GEO, H3 cells) not a row per ping in OLTP.",
      "API: POST /trips, WS for location and status.",
      "Data: users, drivers (status), trips, payments. Location is ephemeral.",
      "HLD: location service (cells), matching/dispatch, trip service, payments, notifications.",
      "Dispatch: ring of hexes, filter by ETA, offer one driver, timeout, next. Avoid thundering herd.",
      "Failures: no drivers (queue or expand radius), matcher crash (offers are leases), GPS lies (map matching).",
    ],
    extra: caseExtra(
      [
        ["Location", "H3 / geohash cells in memory"],
        ["Match", "Expanding radius + short driver lease"],
        ["Track", "Stream locations for the active trip only"],
        ["Pay", "Separate ledger, idempotent capture"],
      ],
      "SELECT * FROM drivers WHERE distance < 5km ORDER BY distance on every request against Postgres.",
    ),
    mistakes: ["Storing every ping forever in the primary", "Dispatching the same driver to two riders without a lease"],
    usage: ["Ride share", "Courier dispatch"],
    interview: [
      iq("How do you find nearby drivers?", "Partition space (geohash/H3). Update drivers into cells. On request, query k rings of cells, rank by ETA, lease one.", "advanced"),
    ],
  }),
  T({
    slug: "instagram",
    section: "system-design",
    title: "Instagram",
    summary: "Media upload, a follow graph, and a feed that is part cache, part ranking.",
    level: "advanced",
    prereqs: ["twitter", "object-storage"],
    related: ["whatsapp"],
    next: "whatsapp",
    what: "Photo/video social: upload media to object storage, write a post row, fan-out a feed (or rank at read time), serve images via CDN. The graph of follows is the same celebrity problem as Twitter, with heavier blobs.",
    why: "Combines the feed problem with the blob problem. A good interview if they want both.",
    mental: "Twitter’s fan-out plus YouTube’s transcoding, with a smaller video and a stronger CDN for images.",
    points: [
      "Upload: client → object storage (pre-signed), then POST metadata. Never proxy multi-MB through the app if you can avoid it.",
      "Feed: hybrid fan-out. Ranked 'for you' is a separate candidate generator + ranker.",
      "Images: many sizes at upload time; CDN. Cache-control is the API.",
    ],
    extra: caseExtra(
      [
        ["Bytes", "Pre-signed object storage + CDN"],
        ["Feed", "Hybrid fan-out + ranking service"],
        ["Graph", "Follow table, cached"],
      ],
      "Uploading the photo as base64 in the JSON of POST /posts.",
    ),
    mistakes: ["Original-size images on the timeline", "Ranking in SQL ORDER BY"],
    usage: ["Media social products"],
    interview: [
      iq("Why pre-signed uploads?", "The app server is a bad place for gigabits of photo bytes. The client writes to storage; the app writes metadata after.", "intermediate"),
    ],
  }),
  T({
    slug: "whatsapp",
    section: "system-design",
    title: "WhatsApp",
    summary: "End-to-end encryption, a small server footprint, and queues as the product.",
    level: "advanced",
    prereqs: ["chat-system", "encryption"],
    related: ["chat-system"],
    next: "uber",
    what: "E2E chat: servers cannot read bodies. They store encrypted blobs addressed to a device, fan them out, and drop them after delivery. Presence and group membership are metadata; the Double Ratchet lives on clients.",
    why: "It shows how little the server must do if clients are smart, and why 'the server is a queue' is a design, not a cop-out.",
    mental: "A post office that cannot open the mail. Device keys, not user passwords, are the trust story.",
    points: [
      "Signal protocol: identity keys, prekeys, ratchets. Server holds prekey bundles.",
      "Multi-device: each device has keys; sender encrypts per device or uses a sender key in groups.",
      "Scale: Erlang-style cheap connections; store-and-forward only.",
    ],
    extra: caseExtra(
      [
        ["Body", "Opaque ciphertext"],
        ["Fan-out", "Per-device mailbox"],
        ["Groups", "Sender keys + membership list"],
      ],
      "Storing plaintext 'for spam detection' while claiming E2E.",
    ),
    mistakes: ["Server-side search over plaintext", "One key for all of a user's devices without a plan"],
    usage: ["E2E messengers"],
    interview: [
      iq("What can the server still know?", "Metadata: who talked to whom, when, size, group membership — unless you go further (sealed sender). Not the body.", "advanced"),
    ],
  }),
  T({
    slug: "amazon",
    section: "system-design",
    title: "Amazon",
    summary: "A catalog, a cart, inventory, and a warehouse network. The original service-oriented giant.",
    level: "advanced",
    prereqs: ["microservices-sd"],
    related: ["payment-system"],
    next: "google-search",
    what: "E-commerce at scale is catalog search, cart, inventory reservation, checkout (idempotent payment + order), and fulfillment. Inventory is the consistency hot spot: two customers must not buy the last item.",
    why: "It is the case for transactions where they matter (checkout) and caches where they don't (catalog).",
    mental: "A warehouse plus a website. The website lies (cache); the warehouse cannot.",
    points: [
      "Catalog: denormalized search index, CDN for images, eventual on descriptions.",
      "Cart: per-user, often cache + DB. Not inventory yet.",
      "Checkout: reserve inventory (short TTL), capture payment, create order, release reserve on fail.",
      "Idempotency keys on pay. Exactly-once is a ledger, not a hope.",
    ],
    extra: caseExtra(
      [
        ["Catalog", "Search index, cacheable"],
        ["Inventory", "Reserved then committed"],
        ["Pay", "Idempotent capture, ledger"],
        ["Fulfill", "Warehouse events"],
      ],
      "Decrementing inventory on 'add to cart'.",
    ),
    mistakes: ["Holding inventory for abandoned carts forever", "Payment retry that double-charges"],
    usage: ["Retail", "Any scarce-goods checkout"],
    interview: [
      iq("How do you not oversell?", "Atomic reserve with a TTL at checkout, not at cart. Commit on pay success; expire otherwise. DB constraint or conditional write.", "intermediate"),
    ],
  }),
  T({
    slug: "google-search",
    section: "system-design",
    title: "Google Search",
    summary: "Crawl, index, rank, and serve in ~100ms. The original warehouse-scale computer.",
    level: "advanced",
    prereqs: ["search-engines-sd", "ir-fundamentals"],
    related: ["search-engine"],
    next: "search-engine",
    what: "Web search is a pipeline: crawl the graph, extract, shard an inverted index, retrieve candidates, rank (signals + ML), snippet. Serving is a fan-out to index shards with a tight tail-latency budget.",
    why: "It is the IR + systems interview. Indexing is batch/stream; serving is a scatter-gather.",
    mental: "A library catalog (inverted index) plus a very fast committee that votes on the ten best cards.",
    points: [
      "Crawler: politeness, canonical URLs, frontier priority, render for JS sites.",
      "Index: term → postings (doc, tf, positions). Sharded by term or by doc; both exist.",
      "Serve: query rewrite → retrieve from shards → merge → rank → cache the head.",
      "Freshness vs cost: news needs a fast lane; the long tail can lag.",
    ],
    extra: caseExtra(
      [
        ["Crawl", "Frontier + fetchers + politeness"],
        ["Index", "Inverted, sharded, compressed"],
        ["Serve", "Scatter-gather + ranker + result cache"],
      ],
      "SELECT * FROM pages WHERE body LIKE '%query%' at 10k QPS.",
    ),
    mistakes: ["One machine's grep", "Ranking only on TF-IDF in 2026 without saying it's a baseline"],
    usage: ["Site search", "Web search", "Log search cousins"],
    interview: [
      iq("Why an inverted index?", "Queries are terms; documents are many. Term → list of docs is the structure that makes intersection fast.", "beginner"),
    ],
  }),
  T({
    slug: "search-engine",
    section: "system-design",
    title: "Search Engine",
    summary: "A complete IR pipeline you could sketch: crawler, indexer, query service, ranker.",
    level: "advanced",
    prereqs: ["google-search"],
    related: ["ir-fundamentals"],
    next: "payment-system",
    viz: "http-simulator",
    what: "Same bones as web search, scoped to a product: crawl or ingest, analyze, index (sparse + maybe dense), retrieve, rank, evaluate. Hybrid search fuses BM25 and vectors.",
    why: "Most engineers will build this (site search, logs) long before they build Google.",
    mental: "A write path that builds postings and embeddings; a read path that unions two candidate lists and ranks.",
    points: [
      "Ingest: events or a crawler. Idempotent doc ids.",
      "Analyze: tokenize, stem/lemmatize, language.",
      "Index: inverted + vector (HNSW). Refresh interval is a product knob.",
      "Query: retrieve k1 sparse + k2 dense, RRF or a learned ranker, then snippets.",
    ],
    extra: caseExtra(
      [
        ["Sparse", "BM25 inverted index"],
        ["Dense", "Embeddings + ANN"],
        ["Blend", "RRF or cross-encoder on a shortlist"],
      ],
      "Only vectors, then wondering why SKU codes and error IDs never match.",
    ),
    mistakes: ["Rebuilding the whole index on every document", "No evaluation set"],
    usage: ["Product search", "Docs search (this site)", "Support tickets"],
    interview: [
      iq("Why hybrid?", "Keyword search nails exact tokens (IDs, names). Vectors nail paraphrase. Each misses what the other hits.", "intermediate"),
    ],
  }),
  T({
    slug: "notification-system",
    section: "system-design",
    title: "Notification System",
    summary: "Fan-out to push, email, SMS, with preferences, retries, and quiet hours.",
    level: "intermediate",
    prereqs: ["message-queues"],
    related: ["chat-system"],
    next: "youtube",
    what: "A notification platform takes an event, decides who should hear it and on which channel, respects preferences and rate limits, and delivers with retries. The event bus is the source; workers per channel are the sinks.",
    why: "Almost every product grows one. It is a clean fan-out + preference + idempotency design.",
    mental: "An event comes in. A rules engine says 'email Ada, push Alan, nobody at 3am'. Queues per channel do the rest.",
    points: [
      "API: POST /events or internal bus. Templates, not raw HTML from every service.",
      "Preferences: per user, per type, per channel. Quiet hours. Unsubscribe is a legal path.",
      "Idempotency: event_id so a retry does not triple-text.",
      "Failures: provider 429 (backoff), bounce (suppress), poison template (dead letter).",
    ],
    extra: caseExtra(
      [
        ["In", "Event bus"],
        ["Decide", "Preference + fan-out service"],
        ["Out", "APNs / FCM / SES / SMS workers"],
      ],
      "Each microservice calling Twilio directly with no shared preference store.",
    ),
    mistakes: ["No idempotency key", "Notification in the request path of the user action"],
    usage: ["Every consumer product"],
    interview: [
      iq("Where do you put retries?", "In the channel worker, with jittered backoff and a max. The original product request should have already returned.", "intermediate"),
    ],
  }),
  T({
    slug: "payment-system",
    section: "system-design",
    title: "Payment System",
    summary: "Idempotent captures, ledgers, and exactly-once as a business requirement.",
    level: "advanced",
    prereqs: ["transactions", "retry-backoff"],
    related: ["amazon"],
    next: "file-storage",
    what: "Payments are a ledger: authorize, capture, refund, payout. The processor (Stripe, a bank) is an unreliable network. Your system of record must be idempotent and reconcilable. Double-charge is a P0.",
    why: "This is where 'at-least-once delivery' meets money. Interviews use it to test idempotency keys and state machines.",
    mental: "A state machine per payment plus a double-entry ledger. Retries replay the same key, not a new charge.",
    points: [
      "API: POST /payments with Idempotency-Key. States: created → authorized → captured / failed / refunded.",
      "Ledger: append-only entries, never update a row’s amount.",
      "Webhooks from the processor are signed and also idempotent.",
      "Reconciliation job vs processor reports. Humans for the rest.",
    ],
    extra: caseExtra(
      [
        ["Key", "Idempotency-Key from client"],
        ["SoR", "Your ledger, not the provider dashboard"],
        ["Retry", "Same key, same intent"],
      ],
      "Generating a new charge id on every retry because the first request timed out.",
    ),
    mistakes: ["UPDATE balance SET x = x + 1 without a unique constraint on the intent", "Trusting webhooks without signature checks"],
    usage: ["Checkout", "Payouts", "Wallets"],
    interview: [
      iq("A capture times out. What now?", "Do not retry as a new capture. Look up the idempotency key / processor intent; if unknown, a safe retrieve; if exists, adopt that state.", "advanced"),
    ],
  }),
  T({
    slug: "file-storage",
    section: "system-design",
    title: "File Storage",
    summary: "Metadata vs bytes, chunking, dedup, and a namespace that looks like a disk.",
    level: "advanced",
    prereqs: ["object-storage"],
    related: ["dropbox"],
    next: "food-delivery",
    what: "A Dropbox-like service presents a filesystem: names, folders, versions, sharing. Bytes live in chunked objects. Metadata (the tree) is a database. Sync clients upload only changed chunks.",
    why: "It is the classic split of namespace from blob, plus conflict (two clients edit offline).",
    mental: "A git for files the user did not ask to be git: content-addressed chunks, a tree of names, and a sync protocol.",
    points: [
      "Chunk files (CDC or fixed). Hash chunks; dedup across users if the product allows.",
      "Metadata DB: nodes, versions, permissions. Not the bytes.",
      "Sync: client sends hashes; server asks for missing chunks; notify peers.",
      "Conflicts: last-writer-wins with a copy, or CRDTs for special docs.",
    ],
    extra: caseExtra(
      [
        ["Bytes", "Chunked object storage"],
        ["Names", "Metadata DB"],
        ["Sync", "Hash list + notify"],
      ],
      "One blob per file with no chunking, so a 1-byte edit re-uploads 2 GB.",
    ),
    mistakes: ["No versioning", "Permissions only on the client"],
    usage: ["Drive products", "Backup"],
    interview: [
      iq("Why chunk?", "Edits and dedup. A small change uploads a small chunk. Identical files across users share bytes if you content-address.", "intermediate"),
    ],
  }),
  T({
    slug: "food-delivery",
    section: "system-design",
    title: "Food Delivery",
    summary: "Three-sided marketplace: diner, restaurant, courier — with ETAs that lie.",
    level: "advanced",
    prereqs: ["uber", "notification-system"],
    related: ["ride-sharing"],
    next: "linux-fundamentals",
    what: "Food delivery adds a restaurant prep-time constraint to ride-sharing’s courier matching. You cannot pick a courier before the food has a ready time; you cannot wait so long the food is cold. ETAs are estimates with wide errors.",
    why: "A matching problem with a perishable good. Good for talking about SLA vs marketplace dynamics.",
    mental: "Three clocks: diner patience, kitchen, courier travel. Dispatch is a bet on all three.",
    points: [
      "Order: diner → restaurant accept → courier assign (maybe delayed until T-ready) → pick up → drop off.",
      "Couriers: same geo cells as Uber, with batches (one courier, two nearby orders) as an optimization.",
      "Failures: restaurant reject, courier cancel, no-show. Comp and re-dispatch.",
    ],
    extra: caseExtra(
      [
        ["Kitchen", "Prep-time model"],
        ["Courier", "Geo match with a delay window"],
        ["Diner", "Notifications + honest ETA ranges"],
      ],
      "Assigning a courier at order time when the kitchen needs 40 minutes.",
    ),
    mistakes: ["Point ETAs without a range", "Ignoring batching"],
    usage: ["Delivery marketplaces"],
    interview: [
      iq("When do you assign the courier?", "Late enough that they are not idle at the restaurant, early enough that food does not wait. Often a few minutes before predicted ready.", "advanced"),
    ],
  }),
  T({
    slug: "ride-sharing",
    section: "system-design",
    title: "Ride Sharing",
    summary: "Supply, demand, surge, and location at 1 Hz from millions of phones.",
    level: "advanced",
    prereqs: ["uber"],
    related: ["food-delivery"],
    next: "amazon",
    what: "The product layer on top of dispatch: pricing (surge as a signal, not a punishment slide), pooling, and marketplace health (too few drivers, too many, in the wrong cells).",
    why: "If Uber is matching, ride-sharing as a topic is the economics and the map.",
    mental: "A control loop: measure idle drivers vs waiting riders per cell, change price and reposition incentives.",
    points: [
      "Surge: raise price in a cell to attract supply and damp demand. Communicate clearly.",
      "Pooling: match two riders with compatible routes; extra constraint on the matcher.",
      "Honesty: show ETAs as ranges; GPS lag is real.",
    ],
    extra: caseExtra(
      [
        ["Signal", "Idle / waiting per H3 cell"],
        ["Act", "Price + bonuses + reposition"],
        ["Match", "Same as Uber dispatch"],
      ],
      "A global surge multiplier for a whole city when only the airport is busy.",
    ),
    mistakes: ["Surge without cell granularity", "Hiding the price until after the match"],
    usage: ["Ride share", "Any two-sided location market"],
    interview: [
      iq("Why cell-local pricing?", "Supply cannot teleport. A city-wide multiplier sends drivers to the wrong neighborhood.", "advanced"),
    ],
  }),
  T({
    slug: "video-streaming",
    section: "system-design",
    title: "Video Streaming",
    summary: "Chunked files, manifests, ABR, and the CDN as the real product.",
    level: "advanced",
    prereqs: ["cdns", "object-storage"],
    related: ["youtube"],
    next: "instagram",
    what: "Streaming is not a single TCP file download. Encode renditions, cut into time chunks, publish a manifest (HLS/DASH), let the player pick. Put the chunks on a CDN. Live adds a few seconds of latency and a packaging pipeline.",
    why: "The generic form of YouTube/Netflix without the social layer. Useful as a building block.",
    mental: "A folder of 2-second files and a playlist. The player is a loop: pick, fetch, buffer, repeat.",
    points: [
      "VOD: transcode offline. Live: transcode in a pipeline, sliding manifest.",
      "Keyframes at chunk boundaries so switches are clean.",
      "Auth: signed URLs or cookies at the CDN edge.",
    ],
    extra: caseExtra(
      [
        ["Encode", "Many bitrates + codec ladder"],
        ["Package", "HLS/DASH chunks + manifest"],
        ["Serve", "CDN, origin as rare miss"],
      ],
      "One MP4 progressive download for a 2-hour 4K film to a phone on LTE.",
    ),
    mistakes: ["No CDN", "Chunks that are whole GOPs of 10 seconds on live (latency)"],
    usage: ["VOD", "Live events", "Internal video"],
    interview: [
      iq("HLS in one sentence?", "A playlist of URIs to media segments. The player downloads the playlist, then the segments, and can switch playlists as bandwidth changes.", "beginner"),
    ],
  }),
];
