import type { NavTopic } from "./nav";
import type { Level, SectionId } from "./types";

type Row = [
  slug: string,
  section: SectionId,
  title: string,
  summary: string,
  level: Level,
  prereqs: string[],
  related: string[],
  next?: string,
  viz?: string,
];

const ROWS: Row[] = [
  // —— DBMS
  ["database-fundamentals", "dbms", "Database Fundamentals", "A database is a managed collection of data with a query language, integrity rules, and a storage engine.", "beginner", [], ["relational-databases"], "relational-databases"],
  ["relational-databases", "dbms", "Relational Databases", "Data as relations (tables), queried with algebra/calculus, constrained by keys.", "beginner", ["database-fundamentals"], ["sql", "tables"], "sql"],
  ["sql", "dbms", "SQL", "The declarative language of relational databases: SELECT describes the result, not the plan.", "beginner", ["relational-databases"], ["joins", "indexes"], "tables", "sql-playground"],
  ["tables", "dbms", "Tables", "Named relations: a heading of columns and a body of rows. Duplicates depend on whether you mean bag or set.", "beginner", ["sql"], ["primary-keys"], "primary-keys"],
  ["primary-keys", "dbms", "Primary Keys", "A column (or set) that uniquely identifies a row. The handle the rest of the schema points at.", "beginner", ["tables"], ["foreign-keys", "constraints"], "foreign-keys"],
  ["foreign-keys", "dbms", "Foreign Keys", "A column that must match a key in another table. Referential integrity as a constraint, not a hope.", "beginner", ["primary-keys"], ["constraints", "joins"], "constraints"],
  ["constraints", "dbms", "Constraints", "Declarations the engine enforces: NOT NULL, UNIQUE, CHECK, FK — integrity that survives a bad insert.", "beginner", ["tables"], ["primary-keys"], "joins"],
  ["joins", "dbms", "Joins", "Combining rows from two relations by a predicate: inner, left, right, full, cross, and the nested-loop vs hash implementations.", "intermediate", ["sql", "foreign-keys"], ["subqueries"], "aggregation", "sql-playground"],
  ["aggregation", "dbms", "Aggregation", "GROUP BY, HAVING, and the reduction of many rows to a statistic.", "beginner", ["sql"], ["joins"], "subqueries", "sql-playground"],
  ["subqueries", "dbms", "Subqueries", "A query used as a value, a table, or a predicate. Correlated vs uncorrelated is the performance fork.", "intermediate", ["sql", "joins"], ["query-optimization"], "indexes"],
  ["indexes", "dbms", "Indexes", "Auxiliary structures (usually B+ trees) that make predicates cheap at the cost of writes and space.", "intermediate", ["sql", "bplus-trees"], ["query-optimization", "b-trees"], "views", "bplus-tree"],
  ["views", "dbms", "Views", "Named queries. Virtual by default; materialized when you cache the result.", "beginner", ["sql"], ["indexes"], "transactions"],
  ["transactions", "dbms", "Transactions", "A grouping of reads and writes that should succeed or fail as a unit.", "intermediate", ["sql"], ["acid", "isolation-levels"], "acid", "transaction-simulator"],
  ["acid", "dbms", "ACID", "Atomicity, Consistency, Isolation, Durability — the classical transaction contract.", "intermediate", ["transactions"], ["isolation-levels", "wal"], "isolation-levels"],
  ["isolation-levels", "dbms", "Isolation Levels", "Read uncommitted through serializable: which anomalies you tolerate for concurrency.", "advanced", ["acid", "transactions"], ["mvcc", "locks-db"], "locks-db", "transaction-simulator"],
  ["locks-db", "dbms", "Locks (DB)", "Shared/exclusive, row/table, intention locks. Two-phase locking as a correctness argument.", "advanced", ["transactions"], ["mvcc", "deadlocks"], "mvcc"],
  ["mvcc", "dbms", "MVCC", "Readers see a snapshot; writers create versions. Postgres and InnoDB's answer to blocking reads.", "advanced", ["isolation-levels"], ["locks-db", "wal"], "concurrency-db"],
  ["concurrency-db", "dbms", "Database Concurrency", "Interleaving transactions without losing integrity. Conflict serializability is the theory.", "advanced", ["transactions"], ["mvcc", "locks-db"], "normalization"],
  ["normalization", "dbms", "Normalization", "Decomposing schemas to remove redundancy. Normal forms are tests, not decorations.", "intermediate", ["relational-databases"], ["1nf", "bcnf"], "1nf"],
  ["1nf", "dbms", "1NF", "Atomic values in cells; no repeating groups. The floor of the relational model.", "beginner", ["normalization"], ["2nf"], "2nf"],
  ["2nf", "dbms", "2NF", "1NF plus no partial dependence of a non-key attribute on part of a composite key.", "intermediate", ["1nf"], ["3nf"], "3nf"],
  ["3nf", "dbms", "3NF", "2NF plus no transitive dependence of a non-key attribute on the key.", "intermediate", ["2nf"], ["bcnf"], "bcnf"],
  ["bcnf", "dbms", "BCNF", "Every determinant is a candidate key. Stricter than 3NF; sometimes you lose a dependency.", "intermediate", ["3nf"], ["normalization"], "query-optimization"],
  ["query-optimization", "dbms", "Query Optimization", "Turning SQL into a cheap plan: statistics, join order, and access paths.", "advanced", ["sql", "indexes"], ["query-planners"], "query-planners"],
  ["query-planners", "dbms", "Query Planners", "Cost-based vs rule-based planners, EXPLAIN, and why the optimizer is the real engine.", "advanced", ["query-optimization"], ["storage-engines"], "storage-engines"],
  ["storage-engines", "dbms", "Storage Engines", "The physical implementation: heap files, clustered indexes, InnoDB vs MyISAM vs LSM.", "advanced", ["database-fundamentals"], ["buffer-pool", "wal"], "buffer-pool"],
  ["buffer-pool", "dbms", "Buffer Pool", "The database's cache of disk pages. Replacement policy, dirty pages, and checkpoints.", "advanced", ["storage-engines", "cache"], ["wal"], "wal"],
  ["wal", "dbms", "Write-Ahead Log", "Log the change before the page. Redo/undo, crash recovery, and replication's raw feed.", "advanced", ["acid", "storage-engines"], ["replication-db"], "b-trees"],
  ["b-trees", "dbms", "B-Trees", "Balanced multiway trees. Internal nodes hold keys and children; used widely in filesystems and DBs.", "intermediate", ["trees"], ["bplus-trees", "indexes"], "bplus-trees"],
  ["bplus-trees", "dbms", "B+ Trees", "All values in leaves, leaves linked. The index structure behind almost every relational PK.", "intermediate", ["b-trees", "indexes"], ["indexes"], "replication-db", "bplus-tree"],
  ["replication-db", "dbms", "Replication (DB)", "Copying data to other nodes: statement vs row, sync vs async, failover.", "advanced", ["wal"], ["sharding", "replication-dist"], "sharding"],
  ["sharding", "dbms", "Sharding", "Partitioning rows across machines by a key. Hotspots and resharding are the cost.", "advanced", ["replication-db"], ["partitioning", "consistent-hashing"], "partitioning"],
  ["partitioning", "dbms", "Partitioning", "Splitting a table by range, list, or hash — within one instance or across them.", "intermediate", ["tables"], ["sharding"], "key-value"],
  ["key-value", "dbms", "Key-Value Stores", "The simplest NoSQL: get/put by key. Redis, Dynamo-style systems.", "intermediate", ["database-fundamentals"], ["document-stores"], "document-stores"],
  ["document-stores", "dbms", "Document Stores", "JSON/BSON documents with secondary indexes. Schema-on-read, query-on-fields.", "intermediate", ["key-value"], ["column-stores"], "column-stores"],
  ["column-stores", "dbms", "Column Stores", "Values stored by column, not row. Analytics, compression, and vectorized execution.", "intermediate", ["database-fundamentals"], ["graph-databases"], "graph-databases"],
  ["graph-databases", "dbms", "Graph Databases", "First-class nodes and edges. Index-free adjacency and graph query languages.", "intermediate", ["graphs"], ["document-stores"], "classes"],

  // —— OOP
  ["classes", "oop", "Classes", "A template for objects: fields, methods, and the invariants that should hold.", "beginner", ["functions"], ["objects"], "objects"],
  ["objects", "oop", "Objects", "A bundle of state and behavior at run time. Identity, state, behavior.", "beginner", ["classes"], ["encapsulation"], "encapsulation"],
  ["encapsulation", "oop", "Encapsulation", "Hiding representation behind an interface so clients do not depend on internals.", "beginner", ["objects"], ["abstraction"], "abstraction"],
  ["abstraction", "oop", "Abstraction", "Showing the essential operations and hiding the rest. Types are the usual vehicle.", "beginner", ["encapsulation"], ["interfaces"], "inheritance"],
  ["inheritance", "oop", "Inheritance", "A subclass reuses and specializes a superclass. Easy to overuse; composition is often healthier.", "beginner", ["classes"], ["polymorphism", "composition"], "polymorphism"],
  ["polymorphism", "oop", "Polymorphism", "The same operation, many implementations. Subtype, parametric, and ad-hoc.", "intermediate", ["inheritance", "interfaces"], ["interfaces"], "interfaces"],
  ["interfaces", "oop", "Interfaces", "A named set of operations without a single implementation. The seam for substitution.", "beginner", ["abstraction"], ["polymorphism"], "composition"],
  ["composition", "oop", "Composition", "Has-a: an object owns or uses another to get work done. Prefer this over deep inheritance.", "beginner", ["objects"], ["aggregation", "inheritance"], "aggregation"],
  ["aggregation", "oop", "Aggregation", "A weaker has-a: parts can outlive the whole. UML's hollow diamond.", "beginner", ["composition"], ["association"], "association"],
  ["association", "oop", "Association", "A structural relationship between objects, with multiplicity and direction.", "beginner", ["objects"], ["aggregation"], "coupling"],
  ["coupling", "oop", "Coupling", "How much one module knows about another. High coupling is change contagion.", "intermediate", ["modules"], ["cohesion"], "cohesion"],
  ["cohesion", "oop", "Cohesion", "How strongly a module's pieces belong together. High cohesion, low coupling is the cliché because it is true.", "intermediate", ["coupling"], ["solid"], "solid"],
  ["solid", "oop", "SOLID", "Five design heuristics: SRP, OCP, LSP, ISP, DIP. Tools, not commandments.", "intermediate", ["interfaces", "coupling"], ["factory", "strategy"], "factory"],
  ["factory", "oop", "Factory", "A method or object whose job is to create other objects without the caller naming the class.", "intermediate", ["interfaces"], ["builder", "solid"], "builder"],
  ["builder", "oop", "Builder", "Stepwise construction of a complex object, often with a fluent interface.", "intermediate", ["factory"], ["singleton"], "singleton"],
  ["singleton", "oop", "Singleton", "One instance, globally reachable. Easy to write, hard to test, often a hidden service locator.", "intermediate", ["classes"], ["factory"], "adapter"],
  ["adapter", "oop", "Adapter", "A wrapper that makes an existing interface look like the one a client already knows.", "intermediate", ["interfaces"], ["decorator"], "decorator"],
  ["decorator", "oop", "Decorator", "Add behavior by wrapping, without changing the wrapped object's class.", "intermediate", ["composition"], ["proxy"], "observer"],
  ["observer", "oop", "Observer", "Subscribers register for events; the subject notifies without knowing who they are.", "intermediate", ["interfaces"], ["pubsub"], "strategy"],
  ["strategy", "oop", "Strategy", "A family of interchangeable algorithms behind one interface, chosen at run time.", "intermediate", ["interfaces"], ["solid"], "command"],
  ["command", "oop", "Command", "An object that represents a request: execute, undo, queue, log.", "intermediate", ["objects"], ["strategy"], "state-pattern"],
  ["state-pattern", "oop", "State Pattern", "An object whose behavior changes with an explicit state object, instead of a thick switch.", "intermediate", ["strategy"], ["command"], "proxy"],
  ["proxy", "oop", "Proxy", "A stand-in that controls access: lazy load, remote, access control, virtual.", "intermediate", ["interfaces"], ["decorator"], "repository"],
  ["repository", "oop", "Repository", "A collection-like interface over persistent storage, so the domain does not speak SQL.", "intermediate", ["interfaces"], ["factory"], "sdlc"],

  // —— SE
  ["sdlc", "software-engineering", "SDLC", "The life of software: idea, requirements, design, build, test, deploy, operate, retire.", "beginner", [], ["requirements", "agile"], "requirements"],
  ["requirements", "software-engineering", "Requirements", "What the system must do, and how you will know. Ambiguity here becomes defects later.", "beginner", ["sdlc"], ["architecture-se"], "architecture-se"],
  ["architecture-se", "software-engineering", "Software Architecture", "The load-bearing decisions: module boundaries, quality attributes, and the trade-offs you will live with.", "intermediate", ["requirements"], ["system-design"], "agile"],
  ["agile", "software-engineering", "Agile", "Short feedback loops, working software, and a willingness to change the plan.", "beginner", ["sdlc"], ["scrum"], "scrum"],
  ["scrum", "software-engineering", "Scrum", "A particular agile process: sprints, a backlog, a daily, and three roles.", "beginner", ["agile"], ["agile"], "git"],
  ["git", "software-engineering", "Git", "A content-addressed snapshot database that happens to be a version control system.", "beginner", [], ["github", "version-control"], "github"],
  ["github", "software-engineering", "GitHub", "Hosted Git plus the social layer: PRs, issues, actions, and code review.", "beginner", ["git"], ["code-review", "cicd"], "version-control"],
  ["version-control", "software-engineering", "Version Control", "The practice of recording history so you can collaborate, blame, and revert.", "beginner", ["git"], ["git"], "code-review"],
  ["code-review", "software-engineering", "Code Review", "A second brain on the diff: correctness, design, and the shared standard of the codebase.", "beginner", ["git"], ["testing"], "testing"],
  ["testing", "software-engineering", "Testing", "Executing a program to find discrepancies with an intended spec. Strategy, not just tools.", "beginner", ["functions"], ["unit-testing"], "unit-testing"],
  ["unit-testing", "software-engineering", "Unit Testing", "Fast, isolated tests of a small unit. Mocks are a tool, not the point.", "beginner", ["testing"], ["integration-testing"], "integration-testing"],
  ["integration-testing", "software-engineering", "Integration Testing", "Tests that several components together still honor the contract.", "intermediate", ["unit-testing"], ["e2e-testing"], "e2e-testing"],
  ["e2e-testing", "software-engineering", "End-to-End Testing", "Drive the system as a user would. Slow, valuable, and easy to make flaky.", "intermediate", ["integration-testing"], ["testing"], "cicd"],
  ["cicd", "software-engineering", "CI/CD", "Every change is built, tested, and (if you mean it) delivered by a machine.", "intermediate", ["testing", "git"], ["deployment-strategies"], "refactoring"],
  ["refactoring", "software-engineering", "Refactoring", "Changing structure without changing behavior, in small safe steps, with tests as the net.", "intermediate", ["testing"], ["clean-code"], "clean-code"],
  ["clean-code", "software-engineering", "Clean Code", "Names, size, and structure that make the next change cheaper. Subjective, but not meaningless.", "beginner", ["refactoring"], ["technical-debt"], "technical-debt"],
  ["technical-debt", "software-engineering", "Technical Debt", "A shortcut that saves now and taxes later. Interest is real; so is overpaying it.", "intermediate", ["clean-code"], ["refactoring"], "documentation-se"],
  ["documentation-se", "software-engineering", "Documentation", "The artifact that lets a stranger (including future you) use or change the system.", "beginner", ["apis"], ["code-review"], "observability"],
  ["observability", "software-engineering", "Observability", "Logs, metrics, traces — enough telemetry to ask new questions of a running system.", "intermediate", ["cicd"], ["metrics", "tracing"], "browser-architecture"],

  // —— Web
  ["browser-architecture", "web", "Browser Architecture", "Processes, the rendering engine, the JS engine, and the network stack in one product.", "intermediate", ["http"], ["dom", "javascript-engine"], "dom"],
  ["dom", "web", "DOM", "The tree of objects representing a document. JavaScript mutates this; the renderer paints it.", "beginner", ["html"], ["cssom", "rendering"], "cssom"],
  ["cssom", "web", "CSSOM", "The CSS object model: parsed styles as a tree the renderer can query.", "intermediate", ["css", "dom"], ["rendering"], "rendering"],
  ["rendering", "web", "Rendering", "Style, layout, paint, composite. The critical path of a frame, and what makes it jank.", "intermediate", ["dom", "cssom"], ["performance-web"], "javascript-engine"],
  ["javascript-engine", "web", "JavaScript Engine", "Parse, compile (often JIT), optimize, garbage-collect. V8 as the usual example.", "intermediate", ["javascript"], ["event-loop"], "event-loop"],
  ["event-loop", "web", "Event Loop", "A queue of tasks and a stack. JavaScript is single-threaded; concurrency is scheduling.", "intermediate", ["javascript"], ["web-apis"], "web-apis"],
  ["web-apis", "web", "Web APIs", "The interfaces the browser offers JS: DOM, fetch, storage, workers, observers.", "beginner", ["javascript"], ["event-loop"], "browser-storage"],
  ["browser-storage", "web", "Browser Storage", "Cookies, localStorage, sessionStorage, IndexedDB — different lifetimes, different threat models.", "beginner", ["web-apis"], ["cookies"], "cookies"],
  ["cookies", "web", "Cookies", "Small data the browser stores and sends. HttpOnly, Secure, SameSite are the real topic.", "beginner", ["http"], ["browser-storage", "csrf"], "cache-web"],
  ["cache-web", "web", "HTTP Caching", "Freshness, validators, and Cache-Control. The cheapest request is the one you do not make.", "intermediate", ["http"], ["cdns"], "html"],
  ["html", "web", "HTML", "The markup language of documents: elements, accessibility tree, and forms.", "beginner", [], ["css", "dom"], "css"],
  ["css", "web", "CSS", "Selectors, cascade, specificity, layout modes. Visual design as a constraint solver.", "beginner", ["html"], ["rendering"], "javascript-web"],
  ["javascript-web", "web", "JavaScript on the Web", "Scripts, modules, bundlers, and the rules of the browser as a runtime.", "beginner", ["javascript", "html"], ["typescript-web"], "typescript-web"],
  ["typescript-web", "web", "TypeScript on the Web", "Types that vanish before the network. Tooling is the product.", "beginner", ["typescript", "javascript-web"], ["react"], "react"],
  ["react", "web", "React", "UI as a function of state. Reconciliation, hooks, and the cost of renders.", "intermediate", ["javascript-web"], ["performance-web"], "accessibility"],
  ["accessibility", "web", "Accessibility", "Designing so people can perceive and operate the UI. Semantics, keyboard, contrast.", "beginner", ["html"], ["html"], "performance-web"],
  ["performance-web", "web", "Web Performance", "Core Web Vitals, payload, main-thread work, and measuring instead of guessing.", "intermediate", ["rendering"], ["cache-web", "cdns"], "rest"],
  ["rest", "web", "REST", "Resources, representations, and uniform verbs. More than 'JSON over HTTP'.", "intermediate", ["http"], ["graphql", "apis-web"], "graphql"],
  ["graphql", "web", "GraphQL", "A query language for an application graph. Clients ask for fields; the server resolves them.", "intermediate", ["rest"], ["apis-web"], "apis-web"],
  ["apis-web", "web", "Web APIs (HTTP)", "Designing HTTP APIs: versioning, errors, idempotency, pagination, authn.", "intermediate", ["rest", "http"], ["authentication"], "authentication"],
  ["authentication", "web", "Authentication", "Proving who is calling. Sessions, tokens, and the difference from authorization.", "intermediate", ["http"], ["authorization", "jwt"], "authorization"],
  ["authorization", "web", "Authorization", "What an authenticated principal is allowed to do. RBAC, ABAC, and the default deny.", "intermediate", ["authentication"], ["jwt", "oauth"], "jwt"],
  ["jwt", "web", "JWT", "A signed (sometimes encrypted) JSON claim set. Self-contained, revocable only with extra work.", "intermediate", ["authentication"], ["oauth", "sessions"], "oauth"],
  ["oauth", "web", "OAuth", "Delegated authorization. Access tokens, refresh tokens, and PKCE for public clients.", "intermediate", ["authentication"], ["jwt"], "sessions"],
  ["sessions", "web", "Sessions", "Server-side (or coordinated) state bound to a client via a cookie or token.", "beginner", ["cookies", "authentication"], ["jwt"], "websockets-web"],
  ["websockets-web", "web", "WebSockets (Web)", "Push from the server without polling. Still TCP, still an origin, still auth.", "intermediate", ["websockets", "http"], ["microservices-web"], "microservices-web"],
  ["microservices-web", "web", "Microservices", "Multiple deployable services, aligned to domains, talking over the network. Ops cost included.", "advanced", ["apis-web"], ["distributed-fundamentals"], "cia-triad"],

  // —— Security
  ["cia-triad", "cybersecurity", "CIA Triad", "Confidentiality, integrity, availability. The three axes every control is arguing about.", "beginner", [], ["authentication-sec", "encryption"], "authentication-sec"],
  ["authentication-sec", "cybersecurity", "Authentication (Security)", "Verifying identity: something you know, have, are — and why MFA exists.", "beginner", ["cia-triad"], ["authorization-sec", "password-security"], "authorization-sec"],
  ["authorization-sec", "cybersecurity", "Authorization (Security)", "Policy after identity. Confused deputies and over-broad tokens are the usual bugs.", "beginner", ["authentication-sec"], ["identity-management"], "encryption"],
  ["encryption", "cybersecurity", "Encryption", "Making confidentiality a key-management problem. Reversible with the right secret.", "beginner", ["cia-triad"], ["symmetric", "asymmetric"], "hashing"],
  ["hashing", "cybersecurity", "Hashing", "One-way mixing. Integrity checks, password storage (with salt and a KDF), and content addressing.", "beginner", ["cia-triad"], ["password-security", "encryption"], "symmetric"],
  ["symmetric", "cybersecurity", "Symmetric Encryption", "One key for both directions. AES-GCM as the modern default mode of thought.", "intermediate", ["encryption"], ["asymmetric", "tls"], "asymmetric"],
  ["asymmetric", "cybersecurity", "Asymmetric Encryption", "A key pair: encrypt to a public key, or sign with a private key. Slow, so we hybridize.", "intermediate", ["encryption"], ["digital-signatures", "tls"], "digital-signatures"],
  ["digital-signatures", "cybersecurity", "Digital Signatures", "Integrity plus authenticity of a message, verifiable with a public key.", "intermediate", ["asymmetric", "hashing"], ["certificates"], "certificates"],
  ["certificates", "cybersecurity", "Certificates", "A signed binding of a public key to a name. PKI, CAs, and what browsers actually check.", "intermediate", ["digital-signatures"], ["tls"], "tls"],
  ["tls", "cybersecurity", "TLS", "The protocol under HTTPS: handshake, certificates, AEAD, and forward secrecy.", "intermediate", ["symmetric", "certificates"], ["https"], "password-security"],
  ["password-security", "cybersecurity", "Password Security", "Hashing with a slow KDF, unique salts, and never storing reversibly. Phishing is still the breach.", "beginner", ["hashing", "authentication-sec"], ["authentication-sec"], "sql-injection"],
  ["sql-injection", "cybersecurity", "SQL Injection", "Untrusted input becoming SQL. Parameterized queries are the fix, not filters.", "intermediate", ["sql"], ["xss", "owasp"], "xss"],
  ["xss", "cybersecurity", "XSS", "Injecting script into someone else's page. Encode on output; CSP as defense in depth.", "intermediate", ["html", "javascript-web"], ["csrf", "owasp"], "csrf"],
  ["csrf", "cybersecurity", "CSRF", "A browser, already authenticated, tricked into a state-changing request. SameSite and tokens.", "intermediate", ["cookies", "authentication"], ["xss", "cors"], "cors"],
  ["cors", "cybersecurity", "CORS", "A browser policy for cross-origin reads. Not an access-control system for your API.", "intermediate", ["http"], ["csrf"], "owasp"],
  ["owasp", "cybersecurity", "OWASP", "A map of common web failures. The Top 10 is a syllabus, not a complete threat model.", "beginner", ["sql-injection", "xss"], ["secure-coding"], "secure-coding"],
  ["secure-coding", "cybersecurity", "Secure Coding", "Defaults that fail closed: validation, least privilege, memory safety, dependency hygiene.", "intermediate", ["owasp"], ["network-security"], "network-security"],
  ["network-security", "cybersecurity", "Network Security", "Segmentation, firewalls, TLS everywhere, and the assumption that the LAN is hostile.", "intermediate", ["firewall", "tls"], ["identity-management"], "identity-management"],
  ["identity-management", "cybersecurity", "Identity Management", "Provisioning, SSO, lifecycle, and the directory as the real security boundary.", "intermediate", ["authentication-sec", "oauth"], ["oauth"], "compiler-design"],

  // —— Compilers
  ["compiler-design", "compilers", "Compiler Design", "The architecture of a translator: front end, middle end, back end.", "intermediate", ["compiler"], ["lexer", "parser"], "lexer", "compiler-explorer"],
  ["interpreter-cmp", "compilers", "Interpreters (Design)", "Tree-walk, bytecode VM, or JIT — executing without a native binary.", "intermediate", ["interpreter"], ["runtime-cmp"], "lexer"],
  ["lexer", "compilers", "Lexer", "The scanner: source characters to tokens, with longest-match and keyword rules.", "intermediate", ["compiler-design", "regular-expressions"], ["tokens", "parser"], "tokens", "compiler-explorer"],
  ["tokens", "compilers", "Tokens", "The atomic words of a language: identifiers, literals, operators, punctuation.", "beginner", ["lexer"], ["parser"], "parser"],
  ["parser", "compilers", "Parser", "Tokens to a tree. Recursive descent, Pratt, LR — all enforcing a grammar.", "intermediate", ["tokens", "cfg"], ["ast"], "ast", "compiler-explorer"],
  ["ast", "compilers", "AST", "An abstract syntax tree: the program as nested structure, comments and punctuation gone.", "intermediate", ["parser"], ["semantic-analysis"], "semantic-analysis", "compiler-explorer"],
  ["semantic-analysis", "compilers", "Semantic Analysis", "Name resolution, types, definite assignment — the meaning a grammar cannot state.", "intermediate", ["ast"], ["type-checking"], "type-checking"],
  ["type-checking", "compilers", "Type Checking", "Rejecting programs that would not make sense to execute. Inference vs annotation.", "intermediate", ["semantic-analysis", "data-types"], ["ir"], "ir"],
  ["ir", "compilers", "Intermediate Representation", "A compiler's private language: three-address code, SSA, and why optimization wants it.", "advanced", ["ast"], ["optimization-cmp"], "optimization-cmp"],
  ["optimization-cmp", "compilers", "Optimization", "Rewrites that preserve semantics and improve a cost model: inlining, DCE, constant folding.", "advanced", ["ir"], ["code-generation"], "code-generation"],
  ["code-generation", "compilers", "Code Generation", "IR to machine code or bytecode: instruction selection, register allocation, calling conventions.", "advanced", ["ir", "isa"], ["runtime-cmp"], "runtime-cmp"],
  ["runtime-cmp", "compilers", "Language Runtime", "The services compiled code expects: allocator, scheduler, unwinder, class loader.", "advanced", ["runtime", "code-generation"], ["gc-cmp"], "gc-cmp"],
  ["gc-cmp", "compilers", "GC (Implementation)", "Mark-sweep, copying, generational, concurrent. The mutator/collector contract.", "advanced", ["garbage-collection", "runtime-cmp"], ["runtime-cmp"], "formal-languages"],

  // —— Theory
  ["formal-languages", "theory", "Formal Languages", "Sets of strings over an alphabet, classified by the machines that recognize them.", "intermediate", ["sets"], ["regular-expressions", "cfg"], "regular-expressions"],
  ["regular-expressions", "theory", "Regular Expressions", "A notation for regular languages. In code they are often more powerful than the theory.", "beginner", ["formal-languages"], ["dfa", "nfa"], "dfa"],
  ["dfa", "theory", "DFA", "A deterministic finite automaton: one state, one next state, no extra memory.", "intermediate", ["regular-expressions"], ["nfa", "regular-languages"], "nfa", "dfa-simulator"],
  ["nfa", "theory", "NFA", "Nondeterministic finite automata, ε-transitions, and the subset construction to a DFA.", "intermediate", ["dfa"], ["regular-languages"], "regular-languages", "dfa-simulator"],
  ["regular-languages", "theory", "Regular Languages", "The languages DFAs recognize. Closed under the usual operations; pumping lemma as a weapon.", "intermediate", ["dfa", "nfa"], ["cfg"], "cfg"],
  ["cfg", "theory", "Context-Free Grammars", "Productions with a single nonterminal on the left. Programming-language syntax lives here.", "intermediate", ["formal-languages"], ["pda", "parser"], "pda"],
  ["pda", "theory", "Pushdown Automata", "A finite automaton plus a stack. CFGs and PDAs define the same class.", "advanced", ["cfg", "stack-ds"], ["turing-machines"], "turing-machines"],
  ["turing-machines", "theory", "Turing Machines", "An infinite tape and a finite control. The standard model of 'computable'.", "advanced", ["dfa"], ["decidability", "halting-problem"], "decidability"],
  ["decidability", "theory", "Decidability", "A language is decidable if a TM halts on every input with yes or no.", "advanced", ["turing-machines"], ["undecidability"], "undecidability"],
  ["undecidability", "theory", "Undecidability", "Problems no algorithm solves. Reduction is how you prove a new one is in the club.", "advanced", ["decidability"], ["halting-problem"], "halting-problem"],
  ["halting-problem", "theory", "Halting Problem", "There is no TM that, given ⟨M, w⟩, decides whether M halts on w.", "advanced", ["turing-machines"], ["undecidability"], "complexity-theory"],
  ["complexity-theory", "theory", "Complexity Theory", "Not 'can we compute it' but 'with what resources'. Time and space as functions of n.", "advanced", ["turing-machines", "asymptotic-notation"], ["p-complexity", "np-complexity"], "p-complexity"],
  ["p-complexity", "theory", "P", "Languages decidable in polynomial time on a deterministic TM. 'Efficient' as a first cut.", "advanced", ["complexity-theory"], ["np-complexity"], "np-complexity"],
  ["np-complexity", "theory", "NP", "Languages with polynomial-time verifiable certificates. Not 'non-polynomial'.", "advanced", ["p-complexity"], ["np-complete"], "np-hard"],
  ["np-hard", "theory", "NP-Hard", "At least as hard as every problem in NP, via polynomial-time reductions.", "advanced", ["np-complexity"], ["np-complete"], "np-complete"],
  ["np-complete", "theory", "NP-Complete", "In NP and NP-hard. SAT is the ancestor; Karp's 21 are the family.", "advanced", ["np-hard"], ["p-complexity"], "distributed-fundamentals"],

  // —— Distributed
  ["distributed-fundamentals", "distributed", "Distributed Systems", "Independent computers that appear, if you are lucky, as one. The network is the computer — and the failure.", "intermediate", ["tcp", "processes"], ["rpc", "fault-tolerance"], "rpc"],
  ["rpc", "distributed", "RPC", "Calling a function that happens to run on another machine. Timeouts, retries, and idempotency follow.", "intermediate", ["apis", "distributed-fundamentals"], ["message-passing"], "message-passing"],
  ["message-passing", "distributed", "Message Passing", "No shared memory: send and receive. The model of actors, Kafka, and most microservices.", "intermediate", ["rpc"], ["logical-clocks"], "logical-clocks"],
  ["logical-clocks", "distributed", "Logical Clocks", "Ordering events without synchronized wall clocks. Happens-before is the primitive.", "advanced", ["distributed-fundamentals"], ["lamport-clocks", "vector-clocks"], "lamport-clocks"],
  ["lamport-clocks", "distributed", "Lamport Clocks", "A counter per process, incremented on events and taking max+1 on receive.", "advanced", ["logical-clocks"], ["vector-clocks"], "vector-clocks"],
  ["vector-clocks", "distributed", "Vector Clocks", "A timestamp per process so you can tell causality from concurrency.", "advanced", ["lamport-clocks"], ["replication-dist"], "replication-dist"],
  ["replication-dist", "distributed", "Replication", "Several copies of the same state. Leader, quorum, and the conflict that follows a partition.", "advanced", ["distributed-fundamentals"], ["quorum", "consistency-models"], "quorum"],
  ["quorum", "distributed", "Quorum", "R + W > N so reads and writes overlap. The math behind many 'highly available' stores.", "advanced", ["replication-dist"], ["consistency-models"], "consistency-models"],
  ["consistency-models", "distributed", "Consistency Models", "Linearizability, sequential, causal, eventual — what a read is allowed to return.", "advanced", ["replication-dist"], ["eventual-consistency", "cap-theorem"], "eventual-consistency"],
  ["eventual-consistency", "distributed", "Eventual Consistency", "If writes stop, replicas converge. Until then, you may see the past.", "intermediate", ["consistency-models"], ["replication-dist"], "leader-election"],
  ["leader-election", "distributed", "Leader Election", "Picking one process to decide. Bully, Raft, and the lease that makes it real.", "advanced", ["distributed-fundamentals"], ["raft", "consensus"], "consensus", "distributed-simulator"],
  ["consensus", "distributed", "Consensus", "Agreeing on a value despite failures. FLP, and why we still run Raft.", "advanced", ["leader-election"], ["raft", "paxos"], "raft"],
  ["raft", "distributed", "Raft", "A consensus protocol designed to be explainable: leader, log, terms, and majority.", "advanced", ["consensus"], ["paxos", "leader-election"], "paxos", "distributed-simulator"],
  ["paxos", "distributed", "Paxos", "The classic consensus family. Prepare/accept, and Multi-Paxos as what people actually run.", "advanced", ["consensus"], ["raft"], "distributed-transactions"],
  ["distributed-transactions", "distributed", "Distributed Transactions", "ACID across machines. 2PC is the starting point and often the ending warning.", "advanced", ["transactions", "consensus"], ["two-phase-commit"], "two-phase-commit"],
  ["two-phase-commit", "distributed", "Two-Phase Commit", "Prepare then commit. Blocking when the coordinator dies is the textbook cost.", "advanced", ["distributed-transactions"], ["consensus"], "failure-detection"],
  ["failure-detection", "distributed", "Failure Detection", "Timeouts, heartbeats, and the fact that you cannot distinguish a slow node from a dead one.", "advanced", ["distributed-fundamentals"], ["fault-tolerance"], "fault-tolerance"],
  ["fault-tolerance", "distributed", "Fault Tolerance", "Continuing (perhaps degraded) after a failure. Replication, retries, and failover.", "intermediate", ["failure-detection"], ["network-partitions"], "network-partitions", "distributed-simulator"],
  ["network-partitions", "distributed", "Network Partitions", "The network splits. CAP is the slogan; your timeout is the reality.", "advanced", ["fault-tolerance", "cap-theorem"], ["cap-theorem"], "distributed-locks"],
  ["distributed-locks", "distributed", "Distributed Locks", "Mutual exclusion across processes. Fencing tokens, and why Redis SET NX is not enough.", "advanced", ["mutex", "consensus"], ["leader-election"], "scalability"],

  // —— System design
  ["scalability", "system-design", "Scalability", "Doing more: vertical until you cannot, then horizontal, with the coordination tax.", "intermediate", ["distributed-fundamentals"], ["availability", "load-balancers"], "availability"],
  ["availability", "system-design", "Availability", "The fraction of time a service does useful work. Nines, and the error budget they imply.", "intermediate", ["scalability"], ["reliability", "slos"], "reliability"],
  ["reliability", "system-design", "Reliability", "Continuing to be correct under stress. Durability, redundancy, and graceful degradation.", "intermediate", ["availability"], ["fault-tolerance-sd"], "latency-sd"],
  ["latency-sd", "system-design", "Latency", "How long an operation takes. Tail latency is the one users feel and p99 is the one you measure.", "intermediate", ["latency"], ["throughput"], "throughput"],
  ["throughput", "system-design", "Throughput", "Work per unit time. Little's law ties it to latency and concurrency.", "intermediate", ["latency-sd"], ["scalability"], "cap-theorem"],
  ["cap-theorem", "system-design", "CAP Theorem", "In a partition, you give up linearizability or availability. The rest is engineering.", "intermediate", ["consistency-models", "network-partitions"], ["acid-vs-base"], "acid-vs-base"],
  ["acid-vs-base", "system-design", "ACID vs BASE", "Strict transactions versus an apology-oriented, eventually consistent style.", "intermediate", ["acid", "eventual-consistency"], ["cap-theorem"], "consistency-sd"],
  ["consistency-sd", "system-design", "Consistency (Design)", "Choosing a consistency model as a product decision, not a database default.", "intermediate", ["consistency-models"], ["cap-theorem"], "fault-tolerance-sd"],
  ["fault-tolerance-sd", "system-design", "Fault Tolerance (Design)", "Designing so a dead box is an event, not an outage: redundancy, retries, isolation.", "intermediate", ["fault-tolerance"], ["circuit-breakers"], "load-balancers"],
  ["load-balancers", "system-design", "Load Balancers", "Spread traffic, hide backends, terminate TLS, and health-check the fleet.", "intermediate", ["scalability"], ["reverse-proxies"], "reverse-proxies", "load-balancer"],
  ["reverse-proxies", "system-design", "Reverse Proxies", "A server in front of servers: TLS, routing, caching, and a single origin for clients.", "intermediate", ["load-balancers", "http"], ["api-gateways", "cdns"], "api-gateways"],
  ["api-gateways", "system-design", "API Gateways", "Auth, rate limits, routing, and protocol translation at the edge of a service fleet.", "intermediate", ["reverse-proxies", "apis-web"], ["rate-limiters"], "caches-sd"],
  ["caches-sd", "system-design", "Caches", "Remembering expensive results. Aside, through, write-back, and the invalidation problem.", "intermediate", ["cache", "cache-web"], ["redis", "cdns"], "redis"],
  ["redis", "system-design", "Redis", "An in-memory data structure server used as cache, lock, queue, and sometimes a database.", "intermediate", ["key-value", "caches-sd"], ["caches-sd"], "cdns"],
  ["cdns", "system-design", "CDNs", "Put bytes closer to users. Edge caches, origin shield, and cache-control as the API.", "intermediate", ["cache-web"], ["reverse-proxies"], "message-queues"],
  ["message-queues", "system-design", "Message Queues", "Asynchronous buffers between producers and consumers. Delivery semantics are the design.", "intermediate", ["message-passing"], ["kafka"], "kafka"],
  ["kafka", "system-design", "Kafka", "A replicated, partitioned log. Consumers are offsets; retention is a disk, not a RAM, problem.", "advanced", ["message-queues"], ["event-driven"], "object-storage"],
  ["object-storage", "system-design", "Object Storage", "Immutable blobs addressed by key. S3 as the API the industry converged on.", "intermediate", ["storage"], ["cdns"], "search-engines-sd"],
  ["search-engines-sd", "system-design", "Search Engines (Systems)", "Crawling, inverted indexes, ranking, and the serving path of a query.", "advanced", ["ir-fundamentals"], ["inverted-index"], "rate-limiters"],
  ["rate-limiters", "system-design", "Rate Limiters", "Token bucket, sliding window, and the distributed counter problem.", "intermediate", ["api-gateways"], ["load-balancers"], "consistent-hashing"],
  ["consistent-hashing", "system-design", "Consistent Hashing", "A ring so that adding a node moves only a 1/n fraction of keys — plus virtual nodes.", "advanced", ["hash-tables", "sharding"], ["sharding"], "circuit-breakers", "consistent-hashing"],
  ["circuit-breakers", "system-design", "Circuit Breakers", "Stop calling a sick dependency so it can recover — and so you fail fast.", "intermediate", ["fault-tolerance-sd"], ["retry-backoff"], "retry-backoff"],
  ["retry-backoff", "system-design", "Retry and Backoff", "Retry is amplification. Jittered exponential backoff and idempotency keys are the adult version.", "intermediate", ["rpc"], ["circuit-breakers"], "event-driven"],
  ["event-driven", "system-design", "Event-Driven Architecture", "Facts emitted as events; consumers decide what to do. Coupling in time is gone; coupling in meaning remains.", "advanced", ["message-queues"], ["microservices-sd"], "microservices-sd"],
  ["microservices-sd", "system-design", "Microservices (Design)", "Independent deploys versus distributed transactions. Draw the seams where the domain already splits.", "advanced", ["microservices-web"], ["event-driven", "api-gateways"], "url-shortener"],

  // —— Case studies
  ["url-shortener", "system-design", "URL Shortener", "Tiny unique IDs, 301s, and a write-heavy mapping that must not collide.", "intermediate", ["hash-tables", "load-balancers"], ["twitter"], "twitter"],
  ["twitter", "system-design", "Twitter / X", "Fan-out on write vs read, a home timeline, and the celebrity problem.", "advanced", ["url-shortener", "caches-sd"], ["chat-system"], "chat-system"],
  ["chat-system", "system-design", "Chat System", "One-to-one and group messages, presence, and delivery at the edge of consistency.", "advanced", ["websockets", "message-queues"], ["notification-system"], "notification-system"],
  ["notification-system", "system-design", "Notification System", "Fan-out to push, email, SMS, with preferences, retries, and quiet hours.", "intermediate", ["message-queues"], ["chat-system"], "youtube"],
  ["youtube", "system-design", "YouTube", "Upload, transcode, store, CDN, and a recommendation path that dwarfs the video path.", "advanced", ["object-storage", "cdns"], ["netflix", "video-streaming"], "netflix"],
  ["netflix", "system-design", "Netflix", "Open Connect, adaptive bitrate, and a control plane that is a microservice zoo.", "advanced", ["youtube", "cdns"], ["video-streaming"], "video-streaming"],
  ["video-streaming", "system-design", "Video Streaming", "Chunked files, manifests, ABR, and the CDN as the real product.", "advanced", ["cdns", "object-storage"], ["youtube"], "instagram"],
  ["instagram", "system-design", "Instagram", "Media upload, a graph of follows, and a feed that is part cache, part ranking.", "advanced", ["twitter", "object-storage"], ["whatsapp"], "whatsapp"],
  ["whatsapp", "system-design", "WhatsApp", "End-to-end encryption, a small server footprint, and queues as the product.", "advanced", ["chat-system", "encryption"], ["chat-system"], "uber"],
  ["uber", "system-design", "Uber", "Matching riders to drivers on a map, with dispatch that cannot be a naive query.", "advanced", ["geo", "kafka"], ["ride-sharing"], "ride-sharing"],
  ["ride-sharing", "system-design", "Ride Sharing", "Supply, demand, surge, and location at 1 Hz from millions of phones.", "advanced", ["uber"], ["food-delivery"], "amazon"],
  ["amazon", "system-design", "Amazon", "A catalog, a cart, inventory, and a warehouse network. The original service-oriented giant.", "advanced", ["microservices-sd"], ["payment-system"], "google-search"],
  ["google-search", "system-design", "Google Search", "Crawl, index, rank, and serve in ~100ms. The original warehouse-scale computer.", "advanced", ["search-engines-sd", "ir-fundamentals"], ["search-engine"], "search-engine"],
  ["search-engine", "system-design", "Search Engine", "A complete IR pipeline you could sketch: crawler, indexer, query service, ranker.", "advanced", ["google-search"], ["ir-fundamentals"], "payment-system"],
  ["payment-system", "system-design", "Payment System", "Idempotent captures, ledgers, and exactly-once as a business requirement.", "advanced", ["transactions", "retry-backoff"], ["amazon"], "file-storage"],
  ["file-storage", "system-design", "File Storage", "Metadata vs bytes, chunking, dedup, and a namespace that looks like a disk.", "advanced", ["object-storage"], ["dropbox"], "food-delivery"],
  ["food-delivery", "system-design", "Food Delivery", "Three-sided marketplace: diner, restaurant, courier — with ETAs that lie.", "advanced", ["uber", "notification-system"], ["ride-sharing"], "linux-fundamentals"],

  // —— Linux
  ["linux-fundamentals", "linux", "Linux Fundamentals", "A Unix-like kernel, a userspace, and a culture of small tools composed with pipes.", "beginner", ["what-is-os"], ["linux-filesystem", "shell"], "linux-filesystem"],
  ["linux-filesystem", "linux", "Linux Filesystem", "A single tree. Everything is a file — until it is a socket, a namespace, or /proc.", "beginner", ["linux-fundamentals", "file-systems"], ["proc", "permissions"], "linux-processes", "linux-terminal"],
  ["linux-processes", "linux", "Processes (Linux)", "fork, exec, wait, and the process tree. pstree is a map of the machine.", "intermediate", ["processes", "linux-fundamentals"], ["linux-threads", "signals-linux"], "linux-threads"],
  ["linux-threads", "linux", "Threads (Linux)", "clone() and NPTL. A thread is a task that shares an address space.", "intermediate", ["threads", "linux-processes"], ["linux-processes"], "permissions"],
  ["permissions", "linux", "Permissions", "User, group, other; rwx; and the bits that actually matter: setuid, capabilities, ACLs.", "beginner", ["linux-filesystem"], ["users-groups"], "users-groups"],
  ["users-groups", "linux", "Users and Groups", "uid, gid, /etc/passwd, and the real vs effective IDs a process carries.", "beginner", ["permissions"], ["permissions"], "shell"],
  ["shell", "linux", "Shell", "A REPL that launches programs, expands globs, and wires file descriptors.", "beginner", ["linux-fundamentals"], ["bash-linux", "pipes"], "bash-linux", "linux-terminal"],
  ["bash-linux", "linux", "Bash (Unix)", "The language of automation on Unix: functions, arrays, set -euo pipefail.", "beginner", ["bash", "shell"], ["pipes"], "pipes"],
  ["pipes", "linux", "Pipes", "stdout of one process into stdin of the next. The Unix idea in one character.", "beginner", ["shell"], ["redirection"], "redirection", "linux-terminal"],
  ["redirection", "linux", "Redirection", "<, >, >>, 2>&1 — the file-descriptor algebra of the shell.", "beginner", ["pipes"], ["env-vars"], "env-vars"],
  ["env-vars", "linux", "Environment Variables", "A string map inherited by children. Configuration without a config file.", "beginner", ["shell"], ["linux-processes"], "ssh-linux"],
  ["ssh-linux", "linux", "SSH (Ops)", "Remote login, keys, agent forwarding, and tunnels you should understand before you use.", "beginner", ["ssh", "linux-fundamentals"], ["ssh"], "signals-linux"],
  ["signals-linux", "linux", "Signals (Linux)", "kill, trap, SIGPIPE, and why a daemon should handle SIGTERM.", "intermediate", ["signals", "linux-processes"], ["linux-processes"], "networking-commands"],
  ["networking-commands", "linux", "Networking Commands", "ss, ip, ping, traceroute, dig, curl — reading the live network from a box.", "beginner", ["linux-fundamentals", "tcp"], ["dns", "tcp"], "proc"],
  ["proc", "linux", "The /proc Filesystem", "A window into the kernel: processes, net, sysctl, and the files that are not on disk.", "intermediate", ["linux-filesystem"], ["syscalls-linux"], "syscalls-linux"],
  ["syscalls-linux", "linux", "System Calls (Linux)", "The actual ABI: unistd, strace, and the handful of calls that implement a Unix.", "intermediate", ["system-calls", "linux-fundamentals"], ["proc"], "package-management"],
  ["package-management", "linux", "Package Management", "apt, dnf, pacman: dependency graphs, signatures, and why you pin in production.", "beginner", ["linux-fundamentals"], ["linux-fundamentals"], "cloud-fundamentals"],

  // —— Cloud
  ["cloud-fundamentals", "cloud", "Cloud Fundamentals", "Someone else's computers, APIs in front of them, billed by the hour or the request.", "beginner", [], ["iaas", "virtual-machines"], "iaas"],
  ["iaas", "cloud", "IaaS", "VMs, disks, and networks as API objects. You still own the guest OS.", "beginner", ["cloud-fundamentals"], ["paas", "virtual-machines"], "paas"],
  ["paas", "cloud", "PaaS", "You bring code; the platform brings the runtime, scaling, and a lot of opinions.", "beginner", ["iaas"], ["saas", "serverless"], "saas"],
  ["saas", "cloud", "SaaS", "Software delivered as a service. You are now on the other side of the API.", "beginner", ["paas"], ["cloud-fundamentals"], "virtual-machines"],
  ["virtual-machines", "cloud", "Virtual Machines", "A hypervisor multiplexing hardware. Isolation that looks like a computer.", "intermediate", ["iaas"], ["containers"], "containers"],
  ["containers", "cloud", "Containers", "Namespaces + cgroups + a filesystem image. Not a VM, despite the UX.", "intermediate", ["linux-fundamentals", "virtual-machines"], ["docker", "kubernetes"], "object-storage-cloud"],
  ["object-storage-cloud", "cloud", "Object Storage (Cloud)", "Durable blobs, eleven nines of marketing, and a consistency model you must read.", "intermediate", ["object-storage"], ["cloud-fundamentals"], "cloud-networking"],
  ["cloud-networking", "cloud", "Cloud Networking", "VPCs, subnets, security groups, and the fact that 'the network' is now software.", "intermediate", ["vpc", "routing"], ["iam"], "iam"],
  ["iam", "cloud", "IAM", "Identities, roles, policies. The blast radius of a leaked key is the whole account.", "intermediate", ["identity-management"], ["cloud-fundamentals"], "autoscaling"],
  ["autoscaling", "cloud", "Autoscaling", "Add or remove capacity from a metric. Cold starts and flapping are the failure modes.", "intermediate", ["virtual-machines", "load-balancers"], ["serverless"], "serverless"],
  ["serverless", "cloud", "Serverless", "You deploy functions; the platform scales to zero. Timeouts, payloads, and vendor glue.", "intermediate", ["paas", "autoscaling"], ["containers"], "monitoring-cloud"],
  ["monitoring-cloud", "cloud", "Cloud Monitoring", "Host metrics, managed-service metrics, and the dashboard that is not a substitute for traces.", "intermediate", ["observability"], ["logging-cloud"], "logging-cloud"],
  ["logging-cloud", "cloud", "Cloud Logging", "Centralized logs as a billed firehose. Structure them or drown.", "beginner", ["observability"], ["monitoring-cloud"], "docker"],

  // —— DevOps
  ["docker", "devops", "Docker", "Images, containers, and a daemon. The packaging format the cloud standardized on.", "intermediate", ["containers"], ["kubernetes"], "kubernetes"],
  ["kubernetes", "devops", "Kubernetes", "A control plane for containers: desired state, reconciliation, and a lot of YAML.", "advanced", ["docker", "containers"], ["deployment-strategies"], "iac"],
  ["iac", "devops", "Infrastructure as Code", "The network and the boxes are in git. Plan, apply, and review like software.", "intermediate", ["git"], ["terraform"], "terraform"],
  ["terraform", "devops", "Terraform", "A graph of resources and a state file. Providers for every cloud, including the ones you regret.", "intermediate", ["iac"], ["iac"], "deployment-strategies"],
  ["deployment-strategies", "devops", "Deployment Strategies", "Rolling, recreate, blue/green, canary — how you swap the running bits.", "intermediate", ["cicd"], ["blue-green", "canary"], "blue-green"],
  ["blue-green", "devops", "Blue/Green Deployment", "Two environments; flip the pointer. Instant rollback, double the capacity during the cut.", "intermediate", ["deployment-strategies"], ["canary"], "canary"],
  ["canary", "devops", "Canary Deployment", "Send a fraction of traffic to the new version and watch the error budget.", "intermediate", ["deployment-strategies", "slos"], ["blue-green"], "monitoring-sre"],
  ["monitoring-sre", "devops", "Monitoring", "Known-unknowns: the dashboards you designed. Alerts that page a human should be rare and true.", "intermediate", ["observability"], ["logging-sre", "metrics"], "logging-sre"],
  ["logging-sre", "devops", "Logging (SRE)", "A debug interface for production. Cardinality, retention, and PII.", "intermediate", ["observability"], ["tracing"], "metrics"],
  ["metrics", "devops", "Metrics", "Numbers over time: RED, USE, and the histograms that make percentiles honest.", "intermediate", ["observability"], ["slos"], "tracing"],
  ["tracing", "devops", "Tracing", "A request as a tree of spans across services. Sampling is not optional at scale.", "intermediate", ["observability", "microservices-sd"], ["metrics"], "slis"],
  ["slis", "devops", "SLIs", "The measurements that stand in for user happiness: availability, latency, quality.", "intermediate", ["metrics"], ["slos"], "slos"],
  ["slos", "devops", "SLOs", "A target on an SLI, and an error budget that tells you when to slow down shipping.", "intermediate", ["slis"], ["slas"], "slas"],
  ["slas", "devops", "SLAs", "The SLO you wrote into a contract, with money attached.", "beginner", ["slos"], ["slos"], "incident-response"],
  ["incident-response", "devops", "Incident Response", "Detect, mitigate, communicate, learn. The runbook is the product.", "intermediate", ["slos"], ["reliability-sre"], "reliability-sre"],
  ["reliability-sre", "devops", "Reliability", "SRE as an engineering discipline: toil, error budgets, and making tomorrow quieter.", "intermediate", ["incident-response", "slos"], ["availability"], "ai-fundamentals"],

  // —— AI / ML / DL / LLM
  ["ai-fundamentals", "ai", "AI Fundamentals", "Building machines that act as if they were intelligent: search, knowledge, learning.", "beginner", [], ["search-ai", "supervised"], "search-ai"],
  ["search-ai", "ai", "Search (AI)", "State spaces, BFS/DFS/A*, and heuristics. Planning as graph search.", "intermediate", ["graphs", "ai-fundamentals"], ["planning"], "knowledge-representation"],
  ["knowledge-representation", "ai", "Knowledge Representation", "Logic, frames, graphs — making facts a machine can query and update.", "intermediate", ["predicate-logic"], ["reasoning"], "planning"],
  ["planning", "ai", "Planning", "Choosing a sequence of actions to reach a goal. STRIPS, and why the real world is not STRIPS.", "intermediate", ["search-ai"], ["reasoning"], "reasoning"],
  ["reasoning", "ai", "Reasoning", "Inference over a knowledge base: forward, backward, and the incompleteness you live with.", "intermediate", ["knowledge-representation"], ["probabilistic-ai"], "probabilistic-ai"],
  ["probabilistic-ai", "ai", "Probabilistic AI", "When the world is noisy: Bayes nets, HMMs, and decisions under uncertainty.", "advanced", ["probability", "reasoning"], ["supervised"], "supervised"],
  ["supervised", "ml", "Supervised Learning", "Learn a mapping from labeled examples. Classification and regression are the two headlines.", "beginner", ["probability"], ["regression", "classification"], "unsupervised"],
  ["unsupervised", "ml", "Unsupervised Learning", "Structure without labels: clusters, density, and compressed representations.", "intermediate", ["supervised"], ["clustering", "pca"], "regression"],
  ["regression", "ml", "Regression", "Predict a continuous target. Linear models, residuals, and regularization.", "beginner", ["supervised"], ["classification", "overfitting"], "classification"],
  ["classification", "ml", "Classification", "Predict a discrete label. Decision boundaries, class imbalance, and calibration.", "beginner", ["supervised"], ["decision-trees-ml"], "decision-trees-ml"],
  ["decision-trees-ml", "ml", "Decision Trees", "Axis-aligned splits that you can read. Easy to overfit, easy to ensemble.", "beginner", ["classification"], ["random-forests"], "random-forests"],
  ["random-forests", "ml", "Random Forests", "Bagged trees with feature randomness. Strong off-the-shelf tabular models.", "intermediate", ["decision-trees-ml"], ["svm"], "svm"],
  ["svm", "ml", "SVM", "Maximum-margin classifiers, kernels, and the dual that made them famous.", "advanced", ["classification"], ["knn"], "knn"],
  ["knn", "ml", "k-NN", "Classify by the labels of the nearest neighbors. The dataset is the model.", "beginner", ["classification"], ["clustering"], "clustering"],
  ["clustering", "ml", "Clustering", "k-means, hierarchical, density-based. There is no single right partition.", "intermediate", ["unsupervised"], ["pca"], "pca"],
  ["pca", "ml", "PCA", "Orthogonal directions of variance. A linear compression, not a mystery.", "intermediate", ["unsupervised"], ["feature-engineering"], "feature-engineering"],
  ["feature-engineering", "ml", "Feature Engineering", "Turning raw observations into the numbers a model can use. Still half the job.", "intermediate", ["supervised"], ["evaluation-ml"], "evaluation-ml"],
  ["evaluation-ml", "ml", "Evaluation", "Hold-out, cross-validation, precision/recall, ROC, and the metric that matches the cost.", "intermediate", ["supervised"], ["overfitting"], "overfitting"],
  ["overfitting", "ml", "Overfitting", "Fitting the sample's noise. The bias-variance story, and why more data is a regularizer.", "beginner", ["evaluation-ml"], ["regularization"], "regularization"],
  ["regularization", "ml", "Regularization", "Penalizing complexity: L2, L1, dropout, early stopping — different names, same idea.", "intermediate", ["overfitting"], ["neural-networks"], "neural-networks"],
  ["neural-networks", "deep-learning", "Neural Networks", "Composed linear maps and nonlinearities. Universal approximation, in theory; engineering, in practice.", "intermediate", ["supervised"], ["backpropagation"], "backpropagation", "neural-net"],
  ["backpropagation", "deep-learning", "Backpropagation", "Reverse-mode autodiff on a computational graph. The gradient is a chain rule.", "intermediate", ["neural-networks"], ["cnn"], "cnn", "neural-net"],
  ["cnn", "deep-learning", "CNN", "Weight sharing over local patches. The inductive bias that ate computer vision.", "intermediate", ["neural-networks"], ["computer-vision-fundamentals"], "rnn"],
  ["rnn", "deep-learning", "RNN", "A network with state over time. Vanishing gradients made them famous for failing.", "intermediate", ["neural-networks"], ["lstm", "gru"], "lstm"],
  ["lstm", "deep-learning", "LSTM", "Gates that learn what to remember. The RNN that actually trained.", "intermediate", ["rnn"], ["gru", "attention"], "gru"],
  ["gru", "deep-learning", "GRU", "A simpler gated recurrent unit. Often close enough to LSTM, cheaper.", "intermediate", ["lstm"], ["attention"], "attention"],
  ["attention", "deep-learning", "Attention", "A weighted sum of values, with weights from a query-key match. The primitive of transformers.", "intermediate", ["neural-networks"], ["transformers"], "transformers", "neural-net"],
  ["transformers", "deep-learning", "Transformers", "Stacked attention and MLPs, with residual connections. The architecture of modern language models.", "advanced", ["attention"], ["tokenization", "pretraining"], "tokens"],
  ["tokens", "llm", "Tokens", "The atomic pieces a language model reads and writes. Not always words.", "beginner", ["transformers"], ["tokenization"], "tokenization"],
  ["tokenization", "llm", "Tokenization", "BPE, WordPiece, Unigram. The tokenizer is part of the model.", "intermediate", ["tokens"], ["embeddings"], "embeddings"],
  ["embeddings", "llm", "Embeddings", "Vectors that put related items nearby. Token, sentence, and document flavors.", "intermediate", ["tokenization"], ["vector-databases"], "context-windows"],
  ["context-windows", "llm", "Context Windows", "How much prefix the model can attend to. Quadratic cost, and the tricks around it.", "intermediate", ["transformers"], ["positional-encoding"], "positional-encoding"],
  ["positional-encoding", "llm", "Positional Encoding", "How a transformer knows order: sinusoids, learned, RoPE.", "advanced", ["transformers"], ["attention"], "pretraining"],
  ["pretraining", "llm", "Pretraining", "Next-token (or masked) prediction on a large corpus. The expensive part.", "advanced", ["transformers"], ["fine-tuning"], "fine-tuning"],
  ["fine-tuning", "llm", "Fine-tuning", "Continuing training on a narrower distribution. Full, LoRA, and instruction variants.", "intermediate", ["pretraining"], ["rlhf"], "rlhf"],
  ["rlhf", "llm", "RLHF", "Using preference data and a reward model to steer generations. Alignment as optimization.", "advanced", ["fine-tuning"], ["evaluation-llm"], "inference"],
  ["inference", "llm", "Inference", "Generating tokens: KV cache, sampling, batching, and the hardware it runs on.", "intermediate", ["pretraining"], ["quantization"], "quantization"],
  ["quantization", "llm", "Quantization", "Fewer bits per weight (and sometimes activation). A quality/cost knob, not a free lunch.", "advanced", ["inference"], ["inference"], "rag"],
  ["rag", "llm", "RAG", "Retrieve then generate. Grounding a model in documents it did not memorize.", "intermediate", ["embeddings", "inference"], ["vector-databases"], "vector-databases"],
  ["vector-databases", "llm", "Vector Databases", "Indexes for nearest-neighbor search over embeddings: HNSW, IVF, product quantization.", "intermediate", ["embeddings"], ["rag", "semantic-search"], "ai-agents"],
  ["ai-agents", "llm", "AI Agents", "Models that plan, use tools, and loop. The hard part is still reliability.", "advanced", ["inference", "tool-calling"], ["tool-calling"], "tool-calling"],
  ["tool-calling", "llm", "Tool Calling", "Structured calls out to APIs, decided by the model, executed by the host.", "intermediate", ["inference"], ["ai-agents"], "evaluation-llm"],
  ["evaluation-llm", "llm", "LLM Evaluation", "Benchmarks, judges, and the fact that fluency is not truth.", "intermediate", ["evaluation-ml"], ["ai-system-design"], "ai-system-design"],
  ["ai-system-design", "llm", "AI System Design", "Serving, retrieval, eval, fallbacks, and cost. A language model is a component.", "advanced", ["inference", "rag"], ["system-design"], "computer-graphics-fundamentals"],

  // —— Graphics / CV / NLP / IR / Parallel / Robotics / Mobile / Research
  ["computer-graphics-fundamentals", "graphics", "Graphics Fundamentals", "Making images from models: geometry, cameras, lights, and a pipeline to pixels.", "beginner", ["cpu"], ["pixels", "rendering-pipeline"], "pixels"],
  ["pixels", "graphics", "Pixels", "Picture elements. Color spaces, alpha, and the framebuffer as a 2D array.", "beginner", ["computer-graphics-fundamentals"], ["coordinates"], "coordinates"],
  ["coordinates", "graphics", "Coordinates", "Object, world, view, clip, screen. Every bug is a space you forgot.", "beginner", ["pixels"], ["vectors-gfx"], "vectors-gfx"],
  ["vectors-gfx", "graphics", "Vectors (Graphics)", "Directions and points, dot and cross, and the geometry of lighting.", "beginner", ["coordinates"], ["matrices-gfx"], "matrices-gfx"],
  ["matrices-gfx", "graphics", "Matrices (Graphics)", "Linear maps and homogeneous coordinates. Why 4×4 is the real 3D matrix.", "intermediate", ["vectors-gfx"], ["transforms"], "transforms"],
  ["transforms", "graphics", "Transforms", "Translate, rotate, scale, and the composition order that surprises you.", "intermediate", ["matrices-gfx"], ["rendering-pipeline"], "rendering-pipeline"],
  ["rendering-pipeline", "graphics", "Rendering Pipeline", "Vertex to fragment: clip, rasterize, test, blend. What the GPU actually does.", "intermediate", ["transforms"], ["rasterization", "shaders"], "rasterization"],
  ["rasterization", "graphics", "Rasterization", "Turning primitives into fragments. The algorithm behind real-time graphics.", "intermediate", ["rendering-pipeline"], ["shaders"], "shaders"],
  ["shaders", "graphics", "Shaders", "Small programs on the GPU: vertex, fragment, compute. The programmable pipeline.", "intermediate", ["rendering-pipeline", "gpu"], ["lighting"], "lighting"],
  ["lighting", "graphics", "Lighting", "Lambert, Phong, PBR. Energy, BRDFs, and why a sphere tells you if the shader works.", "intermediate", ["shaders"], ["gpu"], "gpu-gfx"],
  ["gpu-gfx", "graphics", "GPU (Graphics)", "The same processor as in architecture, used here as a raster and compute engine.", "intermediate", ["gpu", "shaders"], ["simd"], "2d-graphics"],
  ["2d-graphics", "graphics", "2D Graphics", "Sprites, text, immediate-mode UI, and a transform stack.", "beginner", ["pixels"], ["3d-graphics"], "3d-graphics"],
  ["3d-graphics", "graphics", "3D Graphics", "Meshes, cameras, depth, and the pipeline that makes a scene a frame.", "intermediate", ["rendering-pipeline"], ["2d-graphics"], "computer-vision-fundamentals"],
  ["computer-vision-fundamentals", "vision", "Vision Fundamentals", "Making machines interpret images: pixels in, structure and labels out.", "beginner", ["pixels"], ["convolution", "image-classification"], "images-cv"],
  ["images-cv", "vision", "Images", "Arrays of intensity. Resolution, channels, and the sampling theorem you ignore at your peril.", "beginner", ["pixels"], ["convolution"], "convolution"],
  ["convolution", "vision", "Convolution", "A local weighted sum. Filters, CNNs, and the Fourier view for those who want it.", "intermediate", ["images-cv"], ["filters-cv", "cnn"], "filters-cv"],
  ["filters-cv", "vision", "Filters", "Blur, edge, sharpen. Convolution kernels as the vocabulary of early vision.", "beginner", ["convolution"], ["feature-detection"], "feature-detection"],
  ["feature-detection", "vision", "Feature Detection", "Corners, SIFT, ORB — finding points that survive viewpoint change.", "intermediate", ["filters-cv"], ["image-classification"], "image-classification"],
  ["image-classification", "vision", "Image Classification", "One label per image. The ImageNet era, and CNNs as the default answer.", "intermediate", ["cnn"], ["object-detection"], "object-detection"],
  ["object-detection", "vision", "Object Detection", "Boxes and labels. Two-stage vs one-stage, and the NMS footnote.", "advanced", ["image-classification"], ["segmentation"], "segmentation"],
  ["segmentation", "vision", "Segmentation", "A label per pixel (or per instance). U-Nets and the datasets that made them.", "advanced", ["object-detection"], ["cnn"], "text-processing"],
  ["text-processing", "nlp", "Text Processing", "The unglamorous front: encoding, normalization, sentence splitting, and noise.", "beginner", ["strings-ds"], ["tokenization-nlp"], "tokenization-nlp"],
  ["tokenization-nlp", "nlp", "Tokenization (NLP)", "Words, subwords, sentences. The first modeling decision, often invisible.", "beginner", ["text-processing", "tokenization"], ["embeddings-nlp"], "embeddings-nlp"],
  ["embeddings-nlp", "nlp", "Embeddings (NLP)", "Distributional vectors: word2vec, GloVe, and contextual models that replaced them.", "intermediate", ["embeddings", "tokenization-nlp"], ["language-models"], "language-models"],
  ["language-models", "nlp", "Language Models", "Distributions over sequences. n-gram, neural, and the transformer takeover.", "intermediate", ["embeddings-nlp"], ["sequence-models"], "sequence-models"],
  ["sequence-models", "nlp", "Sequence Models", "RNNs, then attention, then transformers. Alignment and transduction.", "intermediate", ["rnn", "language-models"], ["attention"], "text-classification"],
  ["text-classification", "nlp", "Text Classification", "Labels on documents or spans. Still the most common NLP production task.", "beginner", ["language-models"], ["information-extraction"], "information-extraction"],
  ["information-extraction", "nlp", "Information Extraction", "Entities, relations, events. From regex to span models.", "intermediate", ["text-classification"], ["search-nlp"], "search-nlp"],
  ["search-nlp", "nlp", "Search (NLP)", "Using language models to rank or rewrite queries. Hybrid with classical IR.", "intermediate", ["language-models", "ir-fundamentals"], ["semantic-search"], "ir-fundamentals"],
  ["ir-fundamentals", "ir", "IR Fundamentals", "Finding documents relevant to a query. Precision, recall, and the user in the loop.", "beginner", [], ["web-crawlers", "inverted-index"], "web-crawlers"],
  ["web-crawlers", "ir", "Web Crawlers", "Fetch, parse, enqueue. Politeness, canonicalization, and the frontier.", "intermediate", ["ir-fundamentals", "http"], ["indexing-ir"], "indexing-ir"],
  ["indexing-ir", "ir", "Indexing", "Building the structures a query will hit. Inverted indexes, shards, and freshness.", "intermediate", ["web-crawlers"], ["inverted-index"], "inverted-index"],
  ["inverted-index", "ir", "Inverted Index", "Term → postings. Compression, skip lists, and the reason search is fast.", "intermediate", ["indexing-ir"], ["tf-idf", "bm25"], "ranking"],
  ["ranking", "ir", "Ranking", "Ordering hits. Learning to rank sits on top of a candidate generator.", "intermediate", ["inverted-index"], ["tf-idf", "bm25"], "tf-idf"],
  ["tf-idf", "ir", "TF-IDF", "Term frequency times inverse document frequency. The classic sparse vector.", "beginner", ["inverted-index"], ["bm25"], "bm25"],
  ["bm25", "ir", "BM25", "A better TF-IDF: saturation and document-length normalization. Still the sparse baseline.", "intermediate", ["tf-idf"], ["vector-search"], "vector-search"],
  ["vector-search", "ir", "Vector Search", "Nearest neighbors in embedding space. ANN indexes make it serveable.", "intermediate", ["embeddings", "vector-databases"], ["semantic-search"], "semantic-search"],
  ["semantic-search", "ir", "Semantic Search", "Matching meaning, not terms. Usually hybrid with BM25 because both miss things.", "intermediate", ["vector-search", "bm25"], ["hybrid-search"], "hybrid-search"],
  ["hybrid-search", "ir", "Hybrid Search", "Fusing sparse and dense retrieval. Reciprocal rank fusion as the simple thing that works.", "advanced", ["semantic-search", "bm25"], ["ranking"], "concurrency"],
  ["concurrency", "parallel", "Concurrency", "More than one task in progress. Not the same as parallelism.", "intermediate", ["threads"], ["parallelism", "race-conditions"], "parallelism"],
  ["parallelism", "parallel", "Parallelism", "Doing several operations at the same instant. Hardware is the limit; algorithms are the art.", "intermediate", ["concurrency", "multicore"], ["parallel-algorithms"], "locks-par"],
  ["locks-par", "parallel", "Locks (Parallel)", "Mutexes, rwlocks, and the contention that makes them scale badly.", "intermediate", ["mutex", "concurrency"], ["atomics"], "atomics"],
  ["atomics", "parallel", "Atomics", "Hardware-supported indivisible operations. The memory model is the real API.", "advanced", ["locks-par"], ["race-conditions"], "parallel-algorithms"],
  ["parallel-algorithms", "parallel", "Parallel Algorithms", "Prefix sums, parallel sorts, and work/span analysis.", "advanced", ["parallelism", "asymptotic-notation"], ["mapreduce"], "gpu-computing"],
  ["gpu-computing", "parallel", "GPU Computing", "SIMT, occupancy, and memory coalescing. CUDA/OpenCL as the programming model.", "advanced", ["gpu", "simd"], ["parallel-algorithms"], "mapreduce"],
  ["mapreduce", "parallel", "MapReduce", "Map, shuffle, reduce. A programming model that hid a distributed sort.", "intermediate", ["parallel-algorithms"], ["distributed-fundamentals"], "sensors"],
  ["sensors", "robotics", "Sensors", "The robot's input: cameras, IMU, lidar, encoders — each with a noise model.", "beginner", [], ["actuators"], "actuators"],
  ["actuators", "robotics", "Actuators", "Motors, servos, hydraulics. How intention becomes force.", "beginner", ["sensors"], ["control"], "control"],
  ["control", "robotics", "Control", "PID, state-space, and the loop that keeps a system near a reference.", "intermediate", ["actuators"], ["localization"], "localization"],
  ["localization", "robotics", "Localization", "Where is the robot? Filters over pose, and the map they need.", "advanced", ["control", "probability"], ["mapping"], "mapping"],
  ["mapping", "robotics", "Mapping", "Building a model of space. Occupancy grids, SLAM as the joint problem.", "advanced", ["localization"], ["path-planning"], "path-planning"],
  ["path-planning", "robotics", "Path Planning", "A collision-free path. Graphs, sampling, and optimization.", "intermediate", ["search-ai", "mapping"], ["motion-planning"], "robot-perception"],
  ["robot-perception", "robotics", "Robot Perception", "Vision, lidar, and fusion for a body that moves. Latency is a safety issue.", "advanced", ["computer-vision-fundamentals", "sensors"], ["motion-planning"], "motion-planning"],
  ["motion-planning", "robotics", "Motion Planning", "From a path to a trajectory the actuators can track, with dynamics in the loop.", "advanced", ["path-planning", "control"], ["path-planning"], "android"],
  ["android", "mobile", "Android", "A Linux-based OS with a managed runtime, a component model, and a permission system.", "intermediate", ["linux-fundamentals", "java"], ["ios", "app-lifecycle"], "ios"],
  ["ios", "mobile", "iOS", "A Unix descendant with UIKit/SwiftUI, sandboxing, and a review-gated distribution model.", "intermediate", ["swift"], ["android", "app-lifecycle"], "app-lifecycle"],
  ["app-lifecycle", "mobile", "App Lifecycle", "Foreground, background, killed. State you must persist because the OS will reclaim you.", "beginner", ["android", "ios"], ["mobile-networking"], "mobile-networking"],
  ["mobile-networking", "mobile", "Mobile Networking", "Radios that come and go. Retries, reachability, and battery as a constraint.", "intermediate", ["http", "app-lifecycle"], ["local-storage-mobile"], "local-storage-mobile"],
  ["local-storage-mobile", "mobile", "Local Storage (Mobile)", "SQLite, files, keychain/keystore. On-device is not the same as secure.", "beginner", ["app-lifecycle"], ["mobile-security"], "notifications"],
  ["notifications", "mobile", "Notifications", "OS-mediated push. Tokens, permissions, and the server that fans out.", "beginner", ["notification-system"], ["app-lifecycle"], "authentication-mobile"],
  ["authentication-mobile", "mobile", "Mobile Authentication", "Biometrics, secure enclave, OAuth on a public client, and token storage.", "intermediate", ["oauth", "authentication"], ["mobile-security"], "mobile-security"],
  ["mobile-security", "mobile", "Mobile Security", "Sandbox, permissions, attestation, and the threat of a lost phone.", "intermediate", ["authentication-mobile"], ["performance-mobile"], "performance-mobile"],
  ["performance-mobile", "mobile", "Mobile Performance", "Frame budget, cold start, and radios that cost joules. Profile on device.", "intermediate", ["app-lifecycle"], ["rendering"], "how-to-read-papers"],
  ["how-to-read-papers", "research", "How to Read Papers", "Three passes: gist, argument, details. Notes that you can find later.", "beginner", [], ["literature-review"], "literature-review"],
  ["literature-review", "research", "Literature Review", "A map of prior work: who claimed what, with what evidence, and where the gap is.", "beginner", ["how-to-read-papers"], ["research-methodology"], "experiments"],
  ["experiments", "research", "Experiments", "A hypothesis, a protocol, and a result that could have gone the other way.", "intermediate", ["evaluation-ml"], ["benchmarks"], "benchmarks"],
  ["benchmarks", "research", "Benchmarks", "Shared tasks and datasets. Useful, gameable, and not a substitute for a question.", "intermediate", ["experiments"], ["reproducibility"], "reproducibility"],
  ["reproducibility", "research", "Reproducibility", "Someone else, with your artifacts, should get a compatible answer.", "intermediate", ["experiments"], ["technical-writing"], "research-methodology"],
  ["research-methodology", "research", "Research Methodology", "Problem, related work, method, evaluation, threats. The shape of a paper.", "beginner", ["literature-review"], ["technical-writing"], "technical-writing"],
  ["technical-writing", "research", "Technical Writing", "Claims in the first sentence, evidence after. Figures that argue.", "beginner", ["documentation-se"], ["how-to-read-papers"], "research-areas"],
  ["research-areas", "research", "Research Areas", "Where CS is moving: systems, ML, theory, HCI, security, and the seams between them.", "beginner", ["research-methodology"], ["interview-guide"], "interview-guide"],

  // —— Interview hub
  ["interview-guide", "interview", "Interview Guide", "What interviews measure: problem solving, communication, and the systems you claim.", "beginner", [], ["dsa-interview", "systems-interview"], "dsa-interview"],
  ["dsa-interview", "interview", "DSA Interviews", "Arrays, hashes, trees, graphs, DP — and talking while you do it.", "intermediate", ["arrays", "graphs"], ["behavioral"], "systems-interview"],
  ["systems-interview", "interview", "Systems Interviews", "OS, networks, databases, and a design on the whiteboard.", "intermediate", ["processes", "tcp", "indexes"], ["dsa-interview"], "behavioral"],
  ["behavioral", "interview", "Behavioral Interviews", "Stories with a situation, a decision, and a result. Specifics beat slogans.", "beginner", ["interview-guide"], ["dsa-interview"], "coding-interviews"],
  ["coding-interviews", "interview", "Coding Interviews", "A function, a few examples, complexity, and tests you invent before the interviewer asks.", "beginner", ["dsa-interview"], ["system-design-interviews"], "system-design-interviews"],
  ["system-design-interviews", "interview", "System Design Interviews", "Requirements, capacity, API, data, the drawing, then the failures.", "advanced", ["url-shortener", "cap-theorem"], ["systems-interview"], "arrays"],

  // —— Dangling-link pages (referenced from the rest of the atlas)
  ["jvm", "languages", "JVM", "A bytecode VM with a JIT, a GC, and a class loader — the machine Java, Kotlin, and Scala share.", "intermediate", ["java"], ["java", "garbage-collection"], "python"],
  ["wifi", "networks", "Wi-Fi", "802.11: association, airtime, and a MAC that is nothing like a switched Ethernet.", "beginner", ["access-point", "l2-data-link"], ["ethernet", "wireless-phy"], "firewall"],
  ["bgp", "networks", "BGP", "The internet's inter-domain routing protocol: path vectors, policy, and the default-free zone.", "advanced", ["routing-protocols"], ["ospf", "routing"], "tcp"],
  ["ospf", "networks", "OSPF", "A link-state IGP: flood LSAs, run Dijkstra, install routes in the RIB.", "advanced", ["routing-protocols", "dijkstra"], ["bgp", "routing"], "tcp"],
  ["stp", "networks", "Spanning Tree", "A loop-free active topology on a switched LAN. Without it, broadcasts amplify until the LAN dies.", "intermediate", ["switching"], ["vlan", "ethernet"], "arp"],
  ["fork", "os", "fork()", "Copy a process: the child gets 0, the parent gets a pid. Copy-on-write makes the copy cheap until a write.", "intermediate", ["processes"], ["linux-process-model", "linux-threads"], "linux-threads"],
  ["working-set", "os", "Working Set", "The pages a process is actually using. If they do not fit in RAM, the system thrashes.", "intermediate", ["virtual-memory"], ["thrashing", "page-replacement"], "file-systems"],
  ["pubsub", "oop", "Pub/Sub", "Publishers emit events on a topic; subscribers receive them. Observer at the scale of a bus.", "intermediate", ["observer"], ["message-queues", "event-driven"], "strategy"],
  ["vpc", "cloud", "VPC", "A virtual private cloud: isolated address space, subnets, route tables, and gateways as API objects.", "intermediate", ["cloud-networking"], ["iam", "routing"], "iam"],
  ["geo", "system-design", "Geospatial Indexing", "Cells, geohashes, and R-trees so 'nearby' is not a table scan.", "advanced", ["indexes"], ["uber", "ride-sharing"], "uber"],
  ["dropbox", "system-design", "Dropbox", "The named case study of file storage: chunked sync, metadata vs bytes, and conflict copies.", "advanced", ["file-storage"], ["object-storage"], "food-delivery"],
];

export const NAV_REST: NavTopic[] = ROWS.map(([slug, section, title, summary, level, prereqs, related, next, viz]) => ({
  slug,
  section,
  title,
  summary,
  level,
  prereqs,
  related,
  next,
  viz,
  lab: viz,
}));
